// Package agentapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package agentapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for IssueCertificateRequestKind.
const (
	Panel   IssueCertificateRequestKind = "panel"
	Website IssueCertificateRequestKind = "website"
)

// Valid indicates whether the value is a known member of the IssueCertificateRequestKind enum.
func (e IssueCertificateRequestKind) Valid() bool {
	switch e {
	case Panel:
		return true
	case Website:
		return true
	default:
		return false
	}
}

// Defines values for IssueCertificateRequestRuntimeVersion.
const (
	IssueCertificateRequestRuntimeVersionN83 IssueCertificateRequestRuntimeVersion = "8.3"
)

// Valid indicates whether the value is a known member of the IssueCertificateRequestRuntimeVersion enum.
func (e IssueCertificateRequestRuntimeVersion) Valid() bool {
	switch e {
	case IssueCertificateRequestRuntimeVersionN83:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteRequestKind.
const (
	Php WebsiteRequestKind = "php"
)

// Valid indicates whether the value is a known member of the WebsiteRequestKind enum.
func (e WebsiteRequestKind) Valid() bool {
	switch e {
	case Php:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteRequestRuntimeDriver.
const (
	Phpfpm WebsiteRequestRuntimeDriver = "phpfpm"
)

// Valid indicates whether the value is a known member of the WebsiteRequestRuntimeDriver enum.
func (e WebsiteRequestRuntimeDriver) Valid() bool {
	switch e {
	case Phpfpm:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteRequestRuntimeVersion.
const (
	WebsiteRequestRuntimeVersionN83 WebsiteRequestRuntimeVersion = "8.3"
)

// Valid indicates whether the value is a known member of the WebsiteRequestRuntimeVersion enum.
func (e WebsiteRequestRuntimeVersion) Valid() bool {
	switch e {
	case WebsiteRequestRuntimeVersionN83:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteRequestWebDriver.
const (
	Nginx WebsiteRequestWebDriver = "nginx"
)

// Valid indicates whether the value is a known member of the WebsiteRequestWebDriver enum.
func (e WebsiteRequestWebDriver) Valid() bool {
	switch e {
	case Nginx:
		return true
	default:
		return false
	}
}

// AccountActionRequest defines model for AccountActionRequest.
type AccountActionRequest struct {
	AccountId  string `json:"accountId"`
	SystemUser string `json:"systemUser"`
}

// BackupArtifactRequest defines model for BackupArtifactRequest.
type BackupArtifactRequest struct {
	AccountId string `json:"accountId"`
	Checksum  string `json:"checksum"`
	Path      string `json:"path"`
}

// BackupArtifactResult defines model for BackupArtifactResult.
type BackupArtifactResult struct {
	Checksum string         `json:"checksum"`
	Manifest BackupManifest `json:"manifest"`
	Path     string         `json:"path"`
	Size     int64          `json:"size"`
}

// BackupEntry defines model for BackupEntry.
type BackupEntry struct {
	Checksum string `json:"checksum"`
	Path     string `json:"path"`
	Size     int64  `json:"size"`
}

// BackupManifest defines model for BackupManifest.
type BackupManifest struct {
	AccountId string        `json:"accountId"`
	CreatedAt time.Time     `json:"createdAt"`
	Databases bool          `json:"databases"`
	Entries   []BackupEntry `json:"entries"`
	Files     bool          `json:"files"`
	Metadata  bool          `json:"metadata"`
	RunId     string        `json:"runId"`
	Version   int           `json:"version"`
}

// CertificateResult defines model for CertificateResult.
type CertificateResult struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Names     []string  `json:"names"`
}

// CreateBackupRequest defines model for CreateBackupRequest.
type CreateBackupRequest struct {
	AccountId    string   `json:"accountId"`
	Databases    []string `json:"databases"`
	IncludeFiles bool     `json:"includeFiles"`
	Metadata     string   `json:"metadata"`
	RunId        string   `json:"runId"`
	SystemUser   string   `json:"systemUser"`
}

// CronEntry defines model for CronEntry.
type CronEntry struct {
	Command  string `json:"command"`
	Id       string `json:"id"`
	Schedule string `json:"schedule"`
}

// DatabaseGrantRequest defines model for DatabaseGrantRequest.
type DatabaseGrantRequest struct {
	Database string `json:"database"`
	User     string `json:"user"`
}

// DatabaseRequest defines model for DatabaseRequest.
type DatabaseRequest struct {
	Name string `json:"name"`
}

// DatabaseUserRequest defines model for DatabaseUserRequest.
type DatabaseUserRequest struct {
	Name     string  `json:"name"`
	Password *string `json:"password,omitempty"`
}

// EnsureAccountRequest defines model for EnsureAccountRequest.
type EnsureAccountRequest struct {
	AccountId  string `json:"accountId"`
	SystemUser string `json:"systemUser"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// ProtocolVersion Example: v1
	ProtocolVersion string `json:"protocolVersion"`

	// Service Example: webycp-agent
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`

	// Version Example: dev
	Version string `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IssueCertificateRequest defines model for IssueCertificateRequest.
type IssueCertificateRequest struct {
	AccountId      *string                                `json:"accountId,omitempty"`
	CertificateId  string                                 `json:"certificateId"`
	DocumentRoot   *string                                `json:"documentRoot,omitempty"`
	Email          openapi_types.Email                    `json:"email"`
	Kind           IssueCertificateRequestKind            `json:"kind"`
	Name           string                                 `json:"name"`
	Names          []string                               `json:"names"`
	RedirectHttps  bool                                   `json:"redirectHttps"`
	RuntimeVersion *IssueCertificateRequestRuntimeVersion `json:"runtimeVersion,omitempty"`
	SystemUser     *string                                `json:"systemUser,omitempty"`
	WebsiteId      *string                                `json:"websiteId,omitempty"`
}

// IssueCertificateRequestKind defines model for IssueCertificateRequest.Kind.
type IssueCertificateRequestKind string

// IssueCertificateRequestRuntimeVersion defines model for IssueCertificateRequest.RuntimeVersion.
type IssueCertificateRequestRuntimeVersion string

// RestoreBackupRequest defines model for RestoreBackupRequest.
type RestoreBackupRequest struct {
	AccountId  string `json:"accountId"`
	Checksum   string `json:"checksum"`
	Databases  bool   `json:"databases"`
	Files      bool   `json:"files"`
	Metadata   bool   `json:"metadata"`
	Path       string `json:"path"`
	SystemUser string `json:"systemUser"`
}

// RestoreBackupResult defines model for RestoreBackupResult.
type RestoreBackupResult struct {
	Metadata string `json:"metadata"`
}

// SyncCronRequest defines model for SyncCronRequest.
type SyncCronRequest struct {
	AccountId  string      `json:"accountId"`
	Entries    []CronEntry `json:"entries"`
	SystemUser string      `json:"systemUser"`
}

// WebsiteRequest defines model for WebsiteRequest.
type WebsiteRequest struct {
	AccountId      string                       `json:"accountId"`
	Aliases        []string                     `json:"aliases"`
	DocumentRoot   string                       `json:"documentRoot"`
	Kind           WebsiteRequestKind           `json:"kind"`
	PrimaryDomain  string                       `json:"primaryDomain"`
	RuntimeDriver  WebsiteRequestRuntimeDriver  `json:"runtimeDriver"`
	RuntimeVersion WebsiteRequestRuntimeVersion `json:"runtimeVersion"`
	SystemUser     string                       `json:"systemUser"`
	WebDriver      WebsiteRequestWebDriver      `json:"webDriver"`
	WebsiteId      string                       `json:"websiteId"`
}

// WebsiteRequestKind defines model for WebsiteRequest.Kind.
type WebsiteRequestKind string

// WebsiteRequestRuntimeDriver defines model for WebsiteRequest.RuntimeDriver.
type WebsiteRequestRuntimeDriver string

// WebsiteRequestRuntimeVersion defines model for WebsiteRequest.RuntimeVersion.
type WebsiteRequestRuntimeVersion string

// WebsiteRequestWebDriver defines model for WebsiteRequest.WebDriver.
type WebsiteRequestWebDriver string

// EnsureAccountJSONRequestBody defines body for EnsureAccount for application/json ContentType.
type EnsureAccountJSONRequestBody = EnsureAccountRequest

// DeleteAccountJSONRequestBody defines body for DeleteAccount for application/json ContentType.
type DeleteAccountJSONRequestBody = AccountActionRequest

// DisableAccountJSONRequestBody defines body for DisableAccount for application/json ContentType.
type DisableAccountJSONRequestBody = AccountActionRequest

// EnableAccountJSONRequestBody defines body for EnableAccount for application/json ContentType.
type EnableAccountJSONRequestBody = AccountActionRequest

// DeleteBackupJSONRequestBody defines body for DeleteBackup for application/json ContentType.
type DeleteBackupJSONRequestBody = BackupArtifactRequest

// CreateBackupJSONRequestBody defines body for CreateBackup for application/json ContentType.
type CreateBackupJSONRequestBody = CreateBackupRequest

// PreviewBackupJSONRequestBody defines body for PreviewBackup for application/json ContentType.
type PreviewBackupJSONRequestBody = BackupArtifactRequest

// RestoreBackupJSONRequestBody defines body for RestoreBackup for application/json ContentType.
type RestoreBackupJSONRequestBody = RestoreBackupRequest

// IssueCertificateJSONRequestBody defines body for IssueCertificate for application/json ContentType.
type IssueCertificateJSONRequestBody = IssueCertificateRequest

// SyncCronJSONRequestBody defines body for SyncCron for application/json ContentType.
type SyncCronJSONRequestBody = SyncCronRequest

// DeleteDatabaseGrantJSONRequestBody defines body for DeleteDatabaseGrant for application/json ContentType.
type DeleteDatabaseGrantJSONRequestBody = DatabaseGrantRequest

// EnsureDatabaseGrantJSONRequestBody defines body for EnsureDatabaseGrant for application/json ContentType.
type EnsureDatabaseGrantJSONRequestBody = DatabaseGrantRequest

// DeleteDatabaseUserJSONRequestBody defines body for DeleteDatabaseUser for application/json ContentType.
type DeleteDatabaseUserJSONRequestBody = DatabaseUserRequest

// EnsureDatabaseUserJSONRequestBody defines body for EnsureDatabaseUser for application/json ContentType.
type EnsureDatabaseUserJSONRequestBody = DatabaseUserRequest

// DeleteDatabaseJSONRequestBody defines body for DeleteDatabase for application/json ContentType.
type DeleteDatabaseJSONRequestBody = DatabaseRequest

// EnsureDatabaseJSONRequestBody defines body for EnsureDatabase for application/json ContentType.
type EnsureDatabaseJSONRequestBody = DatabaseRequest

// EnsureWebsiteJSONRequestBody defines body for EnsureWebsite for application/json ContentType.
type EnsureWebsiteJSONRequestBody = WebsiteRequest

// DeleteWebsiteJSONRequestBody defines body for DeleteWebsite for application/json ContentType.
type DeleteWebsiteJSONRequestBody = WebsiteRequest

// DisableWebsiteJSONRequestBody defines body for DisableWebsite for application/json ContentType.
type DisableWebsiteJSONRequestBody = WebsiteRequest
