// Package agentapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package agentapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EnsureDomainRequestPhpVersion.
const (
	EnsureDomainRequestPhpVersionN83 EnsureDomainRequestPhpVersion = "8.3"
)

// Valid indicates whether the value is a known member of the EnsureDomainRequestPhpVersion enum.
func (e EnsureDomainRequestPhpVersion) Valid() bool {
	switch e {
	case EnsureDomainRequestPhpVersionN83:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for IssueCertificateRequestKind.
const (
	Domain IssueCertificateRequestKind = "domain"
	Panel  IssueCertificateRequestKind = "panel"
)

// Valid indicates whether the value is a known member of the IssueCertificateRequestKind enum.
func (e IssueCertificateRequestKind) Valid() bool {
	switch e {
	case Domain:
		return true
	case Panel:
		return true
	default:
		return false
	}
}

// Defines values for IssueCertificateRequestPhpVersion.
const (
	IssueCertificateRequestPhpVersionN83 IssueCertificateRequestPhpVersion = "8.3"
)

// Valid indicates whether the value is a known member of the IssueCertificateRequestPhpVersion enum.
func (e IssueCertificateRequestPhpVersion) Valid() bool {
	switch e {
	case IssueCertificateRequestPhpVersionN83:
		return true
	default:
		return false
	}
}

// Defines values for RenameDomainRequestPhpVersion.
const (
	RenameDomainRequestPhpVersionN83 RenameDomainRequestPhpVersion = "8.3"
)

// Valid indicates whether the value is a known member of the RenameDomainRequestPhpVersion enum.
func (e RenameDomainRequestPhpVersion) Valid() bool {
	switch e {
	case RenameDomainRequestPhpVersionN83:
		return true
	default:
		return false
	}
}

// AccountActionRequest defines model for AccountActionRequest.
type AccountActionRequest struct {
	AccountId  string `json:"accountId"`
	SystemUser string `json:"systemUser"`
}

// BackupArtifactRequest defines model for BackupArtifactRequest.
type BackupArtifactRequest struct {
	AccountId string `json:"accountId"`
	Checksum  string `json:"checksum"`
	Path      string `json:"path"`
}

// BackupArtifactResult defines model for BackupArtifactResult.
type BackupArtifactResult struct {
	Checksum string         `json:"checksum"`
	Manifest BackupManifest `json:"manifest"`
	Path     string         `json:"path"`
	Size     int64          `json:"size"`
}

// BackupEntry defines model for BackupEntry.
type BackupEntry struct {
	Checksum string `json:"checksum"`
	Path     string `json:"path"`
	Size     int64  `json:"size"`
}

// BackupManifest defines model for BackupManifest.
type BackupManifest struct {
	AccountId string        `json:"accountId"`
	CreatedAt time.Time     `json:"createdAt"`
	Databases bool          `json:"databases"`
	Entries   []BackupEntry `json:"entries"`
	Files     bool          `json:"files"`
	Metadata  bool          `json:"metadata"`
	RunId     string        `json:"runId"`
	Version   int           `json:"version"`
}

// CertificateResult defines model for CertificateResult.
type CertificateResult struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Names     []string  `json:"names"`
}

// CreateBackupRequest defines model for CreateBackupRequest.
type CreateBackupRequest struct {
	AccountId    string   `json:"accountId"`
	Databases    []string `json:"databases"`
	IncludeFiles bool     `json:"includeFiles"`
	Metadata     string   `json:"metadata"`
	RunId        string   `json:"runId"`
	SystemUser   string   `json:"systemUser"`
}

// CronEntry defines model for CronEntry.
type CronEntry struct {
	Command  string `json:"command"`
	Id       string `json:"id"`
	Schedule string `json:"schedule"`
}

// DatabaseGrantRequest defines model for DatabaseGrantRequest.
type DatabaseGrantRequest struct {
	Database string `json:"database"`
	User     string `json:"user"`
}

// DatabaseRequest defines model for DatabaseRequest.
type DatabaseRequest struct {
	Name string `json:"name"`
}

// DatabaseUserRequest defines model for DatabaseUserRequest.
type DatabaseUserRequest struct {
	Name     string  `json:"name"`
	Password *string `json:"password,omitempty"`
}

// DeleteDomainRequest defines model for DeleteDomainRequest.
type DeleteDomainRequest struct {
	AccountId  string `json:"accountId"`
	DomainId   string `json:"domainId"`
	Name       string `json:"name"`
	SystemUser string `json:"systemUser"`
}

// DisableDomainRequest defines model for DisableDomainRequest.
type DisableDomainRequest struct {
	AccountId  string `json:"accountId"`
	DomainId   string `json:"domainId"`
	SystemUser string `json:"systemUser"`
}

// EnsureAccountRequest defines model for EnsureAccountRequest.
type EnsureAccountRequest struct {
	AccountId  string `json:"accountId"`
	SystemUser string `json:"systemUser"`
}

// EnsureDomainRequest defines model for EnsureDomainRequest.
type EnsureDomainRequest struct {
	AccountId  string                        `json:"accountId"`
	Aliases    []string                      `json:"aliases"`
	DomainId   string                        `json:"domainId"`
	Name       string                        `json:"name"`
	PhpVersion EnsureDomainRequestPhpVersion `json:"phpVersion"`
	SystemUser string                        `json:"systemUser"`
}

// EnsureDomainRequestPhpVersion defines model for EnsureDomainRequest.PhpVersion.
type EnsureDomainRequestPhpVersion string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// ProtocolVersion Example: v1
	ProtocolVersion string `json:"protocolVersion"`

	// Service Example: webycp-agent
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`

	// Version Example: dev
	Version string `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IssueCertificateRequest defines model for IssueCertificateRequest.
type IssueCertificateRequest struct {
	AccountId     *string                            `json:"accountId,omitempty"`
	CertificateId string                             `json:"certificateId"`
	DomainId      *string                            `json:"domainId,omitempty"`
	Email         openapi_types.Email                `json:"email"`
	Kind          IssueCertificateRequestKind        `json:"kind"`
	Name          string                             `json:"name"`
	Names         []string                           `json:"names"`
	PhpVersion    *IssueCertificateRequestPhpVersion `json:"phpVersion,omitempty"`
	RedirectHttps bool                               `json:"redirectHttps"`
	SystemUser    *string                            `json:"systemUser,omitempty"`
}

// IssueCertificateRequestKind defines model for IssueCertificateRequest.Kind.
type IssueCertificateRequestKind string

// IssueCertificateRequestPhpVersion defines model for IssueCertificateRequest.PhpVersion.
type IssueCertificateRequestPhpVersion string

// RenameDomainRequest defines model for RenameDomainRequest.
type RenameDomainRequest struct {
	AccountId   string                        `json:"accountId"`
	Aliases     []string                      `json:"aliases"`
	CurrentName string                        `json:"currentName"`
	DomainId    string                        `json:"domainId"`
	Name        string                        `json:"name"`
	PhpVersion  RenameDomainRequestPhpVersion `json:"phpVersion"`
	SystemUser  string                        `json:"systemUser"`
}

// RenameDomainRequestPhpVersion defines model for RenameDomainRequest.PhpVersion.
type RenameDomainRequestPhpVersion string

// RestoreBackupRequest defines model for RestoreBackupRequest.
type RestoreBackupRequest struct {
	AccountId  string `json:"accountId"`
	Checksum   string `json:"checksum"`
	Databases  bool   `json:"databases"`
	Files      bool   `json:"files"`
	Metadata   bool   `json:"metadata"`
	Path       string `json:"path"`
	SystemUser string `json:"systemUser"`
}

// RestoreBackupResult defines model for RestoreBackupResult.
type RestoreBackupResult struct {
	Metadata string `json:"metadata"`
}

// SyncCronRequest defines model for SyncCronRequest.
type SyncCronRequest struct {
	AccountId  string      `json:"accountId"`
	Entries    []CronEntry `json:"entries"`
	SystemUser string      `json:"systemUser"`
}

// EnsureAccountJSONRequestBody defines body for EnsureAccount for application/json ContentType.
type EnsureAccountJSONRequestBody = EnsureAccountRequest

// DeleteAccountJSONRequestBody defines body for DeleteAccount for application/json ContentType.
type DeleteAccountJSONRequestBody = AccountActionRequest

// DisableAccountJSONRequestBody defines body for DisableAccount for application/json ContentType.
type DisableAccountJSONRequestBody = AccountActionRequest

// EnableAccountJSONRequestBody defines body for EnableAccount for application/json ContentType.
type EnableAccountJSONRequestBody = AccountActionRequest

// DeleteBackupJSONRequestBody defines body for DeleteBackup for application/json ContentType.
type DeleteBackupJSONRequestBody = BackupArtifactRequest

// CreateBackupJSONRequestBody defines body for CreateBackup for application/json ContentType.
type CreateBackupJSONRequestBody = CreateBackupRequest

// PreviewBackupJSONRequestBody defines body for PreviewBackup for application/json ContentType.
type PreviewBackupJSONRequestBody = BackupArtifactRequest

// RestoreBackupJSONRequestBody defines body for RestoreBackup for application/json ContentType.
type RestoreBackupJSONRequestBody = RestoreBackupRequest

// IssueCertificateJSONRequestBody defines body for IssueCertificate for application/json ContentType.
type IssueCertificateJSONRequestBody = IssueCertificateRequest

// SyncCronJSONRequestBody defines body for SyncCron for application/json ContentType.
type SyncCronJSONRequestBody = SyncCronRequest

// DeleteDatabaseGrantJSONRequestBody defines body for DeleteDatabaseGrant for application/json ContentType.
type DeleteDatabaseGrantJSONRequestBody = DatabaseGrantRequest

// EnsureDatabaseGrantJSONRequestBody defines body for EnsureDatabaseGrant for application/json ContentType.
type EnsureDatabaseGrantJSONRequestBody = DatabaseGrantRequest

// DeleteDatabaseUserJSONRequestBody defines body for DeleteDatabaseUser for application/json ContentType.
type DeleteDatabaseUserJSONRequestBody = DatabaseUserRequest

// EnsureDatabaseUserJSONRequestBody defines body for EnsureDatabaseUser for application/json ContentType.
type EnsureDatabaseUserJSONRequestBody = DatabaseUserRequest

// DeleteDatabaseJSONRequestBody defines body for DeleteDatabase for application/json ContentType.
type DeleteDatabaseJSONRequestBody = DatabaseRequest

// EnsureDatabaseJSONRequestBody defines body for EnsureDatabase for application/json ContentType.
type EnsureDatabaseJSONRequestBody = DatabaseRequest

// EnsureDomainJSONRequestBody defines body for EnsureDomain for application/json ContentType.
type EnsureDomainJSONRequestBody = EnsureDomainRequest

// DeleteDomainJSONRequestBody defines body for DeleteDomain for application/json ContentType.
type DeleteDomainJSONRequestBody = DeleteDomainRequest

// DisableDomainJSONRequestBody defines body for DisableDomain for application/json ContentType.
type DisableDomainJSONRequestBody = DisableDomainRequest

// RenameDomainJSONRequestBody defines body for RenameDomain for application/json ContentType.
type RenameDomainJSONRequestBody = RenameDomainRequest
