// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"database/sql"
)

const accountMemberExists = `-- name: AccountMemberExists :one
SELECT EXISTS(
    SELECT 1 FROM account_members WHERE account_id = ? AND user_id = ?
)
`

type AccountMemberExistsParams struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) AccountMemberExists(ctx context.Context, arg AccountMemberExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountMemberExists, arg.AccountID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountNameExists = `-- name: AccountNameExists :one
SELECT EXISTS(
    SELECT 1 FROM accounts WHERE name = ? COLLATE NOCASE
)
`

func (q *Queries) AccountNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountResourceCount = `-- name: AccountResourceCount :one
SELECT
    (SELECT COUNT(*) FROM websites WHERE websites.account_id = ?1) +
    (SELECT COUNT(*) FROM databases WHERE databases.account_id = ?1) +
    (SELECT COUNT(*) FROM database_users WHERE database_users.account_id = ?1) +
    (SELECT COUNT(*) FROM scheduled_tasks WHERE scheduled_tasks.account_id = ?1) +
    (SELECT COUNT(*) FROM backup_plans WHERE backup_plans.account_id = ?1) +
    (SELECT COUNT(*) FROM backup_artifacts WHERE backup_artifacts.account_id = ?1) +
    (SELECT COUNT(*) FROM dns_zones WHERE dns_zones.account_id = ?1)
`

func (q *Queries) AccountResourceCount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, accountResourceCount, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const addAccountMember = `-- name: AddAccountMember :exec
INSERT INTO account_members (
    account_id,
    user_id,
    role,
    created_at
) VALUES (?, ?, 'owner', ?)
`

type AddAccountMemberParams struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) AddAccountMember(ctx context.Context, arg AddAccountMemberParams) error {
	_, err := q.db.ExecContext(ctx, addAccountMember, arg.AccountID, arg.UserID, arg.CreatedAt)
	return err
}

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserAccounts = `-- name: CountUserAccounts :one
SELECT COUNT(*)
FROM accounts
JOIN account_members ON account_members.account_id = accounts.id
WHERE account_members.user_id = ?
`

func (q *Queries) CountUserAccounts(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAccounts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    node_id,
    name,
    system_user,
    status,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, 'pending', ?, ?)
RETURNING id, node_id, name, system_user, status, created_at, updated_at, enabled
`

type CreateAccountParams struct {
	ID         string         `json:"id"`
	NodeID     sql.NullString `json:"node_id"`
	Name       string         `json:"name"`
	SystemUser string         `json:"system_user"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.NodeID,
		arg.Name,
		arg.SystemUser,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SystemUser,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, node_id, name, system_user, status, created_at, updated_at, enabled FROM accounts WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SystemUser,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, node_id, name, system_user, status, created_at, updated_at, enabled FROM accounts ORDER BY created_at ASC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.SystemUser,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsPage = `-- name: ListAccountsPage :many
SELECT id, node_id, name, system_user, status, created_at, updated_at, enabled FROM accounts
ORDER BY created_at ASC
LIMIT ?2 OFFSET ?1
`

type ListAccountsPageParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

func (q *Queries) ListAccountsPage(ctx context.Context, arg ListAccountsPageParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsPage, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.SystemUser,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccounts = `-- name: ListUserAccounts :many
SELECT accounts.id, accounts.node_id, accounts.name, accounts.system_user, accounts.status, accounts.created_at, accounts.updated_at, accounts.enabled
FROM accounts
JOIN account_members ON account_members.account_id = accounts.id
WHERE account_members.user_id = ?
ORDER BY accounts.created_at ASC
`

func (q *Queries) ListUserAccounts(ctx context.Context, userID string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listUserAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.SystemUser,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccountsPage = `-- name: ListUserAccountsPage :many
SELECT accounts.id, accounts.node_id, accounts.name, accounts.system_user, accounts.status, accounts.created_at, accounts.updated_at, accounts.enabled
FROM accounts
JOIN account_members ON account_members.account_id = accounts.id
WHERE account_members.user_id = ?1
ORDER BY accounts.created_at ASC
LIMIT ?3 OFFSET ?2
`

type ListUserAccountsPageParams struct {
	UserID     string `json:"user_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) ListUserAccountsPage(ctx context.Context, arg ListUserAccountsPageParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listUserAccountsPage, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.SystemUser,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueAccountAction = `-- name: QueueAccountAction :one
UPDATE accounts
SET enabled = ?, status = 'pending', updated_at = ?
WHERE id = ? AND status != 'pending'
RETURNING id, node_id, name, system_user, status, created_at, updated_at, enabled
`

type QueueAccountActionParams struct {
	Enabled   int64  `json:"enabled"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueAccountAction(ctx context.Context, arg QueueAccountActionParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, queueAccountAction, arg.Enabled, arg.UpdatedAt, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SystemUser,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateAccountStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
