// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    id,
    user_id,
    action,
    resource_type,
    resource_id,
    result,
    metadata,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditEventParams struct {
	ID           string         `json:"id"`
	UserID       sql.NullString `json:"user_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
	Result       string         `json:"result"`
	Metadata     string         `json:"metadata"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEvent,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
