// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"database/sql"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*) FROM audit_events
WHERE ?1 = '' OR job_id = ?1
`

func (q *Queries) CountAuditEvents(ctx context.Context, jobID interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditEvents, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    id,
    user_id,
    action,
    resource_type,
    resource_id,
    result,
    metadata,
    created_at,
    job_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditEventParams struct {
	ID           string         `json:"id"`
	UserID       sql.NullString `json:"user_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
	Result       string         `json:"result"`
	Metadata     string         `json:"metadata"`
	CreatedAt    int64          `json:"created_at"`
	JobID        sql.NullString `json:"job_id"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEvent,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.Metadata,
		arg.CreatedAt,
		arg.JobID,
	)
	return err
}

const listAuditEventsPage = `-- name: ListAuditEventsPage :many
SELECT id, user_id, action, resource_type, resource_id, result, created_at, job_id FROM audit_events
WHERE ?1 = '' OR job_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListAuditEventsPageParams struct {
	JobID      interface{} `json:"job_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

type ListAuditEventsPageRow struct {
	ID           string         `json:"id"`
	UserID       sql.NullString `json:"user_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
	Result       string         `json:"result"`
	CreatedAt    int64          `json:"created_at"`
	JobID        sql.NullString `json:"job_id"`
}

func (q *Queries) ListAuditEventsPage(ctx context.Context, arg ListAuditEventsPageParams) ([]ListAuditEventsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsPage, arg.JobID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsPageRow{}
	for rows.Next() {
		var i ListAuditEventsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Result,
			&i.CreatedAt,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
