// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package dbgen

import (
	"context"
	"database/sql"
)

const backupRunPending = `-- name: BackupRunPending :one
SELECT EXISTS(SELECT 1 FROM backup_runs WHERE plan_id = ? AND status IN ('queued', 'running'))
`

func (q *Queries) BackupRunPending(ctx context.Context, planID sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, backupRunPending, planID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countBackupArtifacts = `-- name: CountBackupArtifacts :one
SELECT COUNT(DISTINCT backup_artifacts.id) FROM backup_artifacts
JOIN account_members ON account_members.account_id = backup_artifacts.account_id
WHERE ?1 OR account_members.user_id = ?2
`

type CountBackupArtifactsParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountBackupArtifacts(ctx context.Context, arg CountBackupArtifactsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBackupArtifacts, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBackupPlans = `-- name: CountBackupPlans :one
SELECT COUNT(DISTINCT backup_plans.id) FROM backup_plans
JOIN account_members ON account_members.account_id = backup_plans.account_id
WHERE ?1 OR account_members.user_id = ?2
`

type CountBackupPlansParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountBackupPlans(ctx context.Context, arg CountBackupPlansParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBackupPlans, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBackupRuns = `-- name: CountBackupRuns :one
SELECT COUNT(DISTINCT backup_runs.id) FROM backup_runs
JOIN account_members ON account_members.account_id = backup_runs.account_id
WHERE ?1 OR account_members.user_id = ?2
`

type CountBackupRunsParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountBackupRuns(ctx context.Context, arg CountBackupRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBackupRuns, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBackupArtifact = `-- name: CreateBackupArtifact :one
INSERT INTO backup_artifacts (
    id, run_id, account_id, node_id, storage_driver, path, checksum, size_bytes, manifest, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, run_id, account_id, node_id, path, checksum, size_bytes, manifest, created_at, storage_driver
`

type CreateBackupArtifactParams struct {
	ID            string `json:"id"`
	RunID         string `json:"run_id"`
	AccountID     string `json:"account_id"`
	NodeID        string `json:"node_id"`
	StorageDriver string `json:"storage_driver"`
	Path          string `json:"path"`
	Checksum      string `json:"checksum"`
	SizeBytes     int64  `json:"size_bytes"`
	Manifest      string `json:"manifest"`
	CreatedAt     int64  `json:"created_at"`
}

func (q *Queries) CreateBackupArtifact(ctx context.Context, arg CreateBackupArtifactParams) (BackupArtifact, error) {
	row := q.db.QueryRowContext(ctx, createBackupArtifact,
		arg.ID,
		arg.RunID,
		arg.AccountID,
		arg.NodeID,
		arg.StorageDriver,
		arg.Path,
		arg.Checksum,
		arg.SizeBytes,
		arg.Manifest,
		arg.CreatedAt,
	)
	var i BackupArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AccountID,
		&i.NodeID,
		&i.Path,
		&i.Checksum,
		&i.SizeBytes,
		&i.Manifest,
		&i.CreatedAt,
		&i.StorageDriver,
	)
	return i, err
}

const createBackupPlan = `-- name: CreateBackupPlan :one
INSERT INTO backup_plans (
    id, account_id, node_id, name, schedule, retention_count,
    storage_driver, include_files, include_databases, enabled, next_run_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, account_id, node_id, name, schedule, retention_count, include_files, include_databases, enabled, last_run_at, next_run_at, created_at, updated_at, storage_driver
`

type CreateBackupPlanParams struct {
	ID               string        `json:"id"`
	AccountID        string        `json:"account_id"`
	NodeID           string        `json:"node_id"`
	Name             string        `json:"name"`
	Schedule         string        `json:"schedule"`
	RetentionCount   int64         `json:"retention_count"`
	StorageDriver    string        `json:"storage_driver"`
	IncludeFiles     int64         `json:"include_files"`
	IncludeDatabases int64         `json:"include_databases"`
	Enabled          int64         `json:"enabled"`
	NextRunAt        sql.NullInt64 `json:"next_run_at"`
	CreatedAt        int64         `json:"created_at"`
	UpdatedAt        int64         `json:"updated_at"`
}

func (q *Queries) CreateBackupPlan(ctx context.Context, arg CreateBackupPlanParams) (BackupPlan, error) {
	row := q.db.QueryRowContext(ctx, createBackupPlan,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.Schedule,
		arg.RetentionCount,
		arg.StorageDriver,
		arg.IncludeFiles,
		arg.IncludeDatabases,
		arg.Enabled,
		arg.NextRunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BackupPlan
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.RetentionCount,
		&i.IncludeFiles,
		&i.IncludeDatabases,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageDriver,
	)
	return i, err
}

const createBackupRun = `-- name: CreateBackupRun :one
INSERT INTO backup_runs (
    id, plan_id, account_id, node_id, storage_driver, status, created_at
) VALUES (?, ?, ?, ?, ?, 'queued', ?)
RETURNING id, plan_id, account_id, node_id, status, error, created_at, started_at, finished_at, storage_driver
`

type CreateBackupRunParams struct {
	ID            string         `json:"id"`
	PlanID        sql.NullString `json:"plan_id"`
	AccountID     string         `json:"account_id"`
	NodeID        string         `json:"node_id"`
	StorageDriver string         `json:"storage_driver"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) CreateBackupRun(ctx context.Context, arg CreateBackupRunParams) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, createBackupRun,
		arg.ID,
		arg.PlanID,
		arg.AccountID,
		arg.NodeID,
		arg.StorageDriver,
		arg.CreatedAt,
	)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.AccountID,
		&i.NodeID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.StorageDriver,
	)
	return i, err
}

const deleteBackupArtifact = `-- name: DeleteBackupArtifact :exec
DELETE FROM backup_artifacts WHERE id = ?
`

func (q *Queries) DeleteBackupArtifact(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupArtifact, id)
	return err
}

const deleteBackupPlan = `-- name: DeleteBackupPlan :exec
DELETE FROM backup_plans WHERE id = ?
`

func (q *Queries) DeleteBackupPlan(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBackupPlan, id)
	return err
}

const getBackupArtifact = `-- name: GetBackupArtifact :one
SELECT id, run_id, account_id, node_id, path, checksum, size_bytes, manifest, created_at, storage_driver FROM backup_artifacts WHERE id = ? LIMIT 1
`

func (q *Queries) GetBackupArtifact(ctx context.Context, id string) (BackupArtifact, error) {
	row := q.db.QueryRowContext(ctx, getBackupArtifact, id)
	var i BackupArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AccountID,
		&i.NodeID,
		&i.Path,
		&i.Checksum,
		&i.SizeBytes,
		&i.Manifest,
		&i.CreatedAt,
		&i.StorageDriver,
	)
	return i, err
}

const getBackupPlan = `-- name: GetBackupPlan :one
SELECT id, account_id, node_id, name, schedule, retention_count, include_files, include_databases, enabled, last_run_at, next_run_at, created_at, updated_at, storage_driver FROM backup_plans WHERE id = ? LIMIT 1
`

func (q *Queries) GetBackupPlan(ctx context.Context, id string) (BackupPlan, error) {
	row := q.db.QueryRowContext(ctx, getBackupPlan, id)
	var i BackupPlan
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.RetentionCount,
		&i.IncludeFiles,
		&i.IncludeDatabases,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageDriver,
	)
	return i, err
}

const getBackupRun = `-- name: GetBackupRun :one
SELECT id, plan_id, account_id, node_id, status, error, created_at, started_at, finished_at, storage_driver FROM backup_runs WHERE id = ? LIMIT 1
`

func (q *Queries) GetBackupRun(ctx context.Context, id string) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, getBackupRun, id)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.AccountID,
		&i.NodeID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.StorageDriver,
	)
	return i, err
}

const listBackupArtifacts = `-- name: ListBackupArtifacts :many
SELECT backup_artifacts.id, backup_artifacts.run_id, backup_artifacts.account_id, backup_artifacts.node_id, backup_artifacts.path, backup_artifacts.checksum, backup_artifacts.size_bytes, backup_artifacts.manifest, backup_artifacts.created_at, backup_artifacts.storage_driver FROM backup_artifacts
JOIN account_members ON account_members.account_id = backup_artifacts.account_id
WHERE ? OR account_members.user_id = ?
GROUP BY backup_artifacts.id
ORDER BY backup_artifacts.created_at DESC
`

type ListBackupArtifactsParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListBackupArtifacts(ctx context.Context, arg ListBackupArtifactsParams) ([]BackupArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listBackupArtifacts, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupArtifact{}
	for rows.Next() {
		var i BackupArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AccountID,
			&i.NodeID,
			&i.Path,
			&i.Checksum,
			&i.SizeBytes,
			&i.Manifest,
			&i.CreatedAt,
			&i.StorageDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupArtifactsPage = `-- name: ListBackupArtifactsPage :many
SELECT backup_artifacts.id, backup_artifacts.run_id, backup_artifacts.account_id, backup_artifacts.node_id, backup_artifacts.path, backup_artifacts.checksum, backup_artifacts.size_bytes, backup_artifacts.manifest, backup_artifacts.created_at, backup_artifacts.storage_driver FROM backup_artifacts
JOIN account_members ON account_members.account_id = backup_artifacts.account_id
WHERE ?1 OR account_members.user_id = ?2
GROUP BY backup_artifacts.id
ORDER BY backup_artifacts.created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListBackupArtifactsPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListBackupArtifactsPage(ctx context.Context, arg ListBackupArtifactsPageParams) ([]BackupArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listBackupArtifactsPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupArtifact{}
	for rows.Next() {
		var i BackupArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AccountID,
			&i.NodeID,
			&i.Path,
			&i.Checksum,
			&i.SizeBytes,
			&i.Manifest,
			&i.CreatedAt,
			&i.StorageDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupPlans = `-- name: ListBackupPlans :many
SELECT backup_plans.id, backup_plans.account_id, backup_plans.node_id, backup_plans.name, backup_plans.schedule, backup_plans.retention_count, backup_plans.include_files, backup_plans.include_databases, backup_plans.enabled, backup_plans.last_run_at, backup_plans.next_run_at, backup_plans.created_at, backup_plans.updated_at, backup_plans.storage_driver FROM backup_plans
JOIN account_members ON account_members.account_id = backup_plans.account_id
WHERE ? OR account_members.user_id = ?
GROUP BY backup_plans.id
ORDER BY backup_plans.created_at ASC
`

type ListBackupPlansParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListBackupPlans(ctx context.Context, arg ListBackupPlansParams) ([]BackupPlan, error) {
	rows, err := q.db.QueryContext(ctx, listBackupPlans, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupPlan{}
	for rows.Next() {
		var i BackupPlan
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.RetentionCount,
			&i.IncludeFiles,
			&i.IncludeDatabases,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupPlansPage = `-- name: ListBackupPlansPage :many
SELECT backup_plans.id, backup_plans.account_id, backup_plans.node_id, backup_plans.name, backup_plans.schedule, backup_plans.retention_count, backup_plans.include_files, backup_plans.include_databases, backup_plans.enabled, backup_plans.last_run_at, backup_plans.next_run_at, backup_plans.created_at, backup_plans.updated_at, backup_plans.storage_driver FROM backup_plans
JOIN account_members ON account_members.account_id = backup_plans.account_id
WHERE ?1 OR account_members.user_id = ?2
GROUP BY backup_plans.id
ORDER BY backup_plans.created_at ASC
LIMIT ?4 OFFSET ?3
`

type ListBackupPlansPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListBackupPlansPage(ctx context.Context, arg ListBackupPlansPageParams) ([]BackupPlan, error) {
	rows, err := q.db.QueryContext(ctx, listBackupPlansPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupPlan{}
	for rows.Next() {
		var i BackupPlan
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.RetentionCount,
			&i.IncludeFiles,
			&i.IncludeDatabases,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupRuns = `-- name: ListBackupRuns :many
SELECT backup_runs.id, backup_runs.plan_id, backup_runs.account_id, backup_runs.node_id, backup_runs.status, backup_runs.error, backup_runs.created_at, backup_runs.started_at, backup_runs.finished_at, backup_runs.storage_driver FROM backup_runs
JOIN account_members ON account_members.account_id = backup_runs.account_id
WHERE ? OR account_members.user_id = ?
GROUP BY backup_runs.id
ORDER BY backup_runs.created_at DESC
`

type ListBackupRunsParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListBackupRuns(ctx context.Context, arg ListBackupRunsParams) ([]BackupRun, error) {
	rows, err := q.db.QueryContext(ctx, listBackupRuns, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupRun{}
	for rows.Next() {
		var i BackupRun
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.AccountID,
			&i.NodeID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.StorageDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupRunsPage = `-- name: ListBackupRunsPage :many
SELECT backup_runs.id, backup_runs.plan_id, backup_runs.account_id, backup_runs.node_id, backup_runs.status, backup_runs.error, backup_runs.created_at, backup_runs.started_at, backup_runs.finished_at, backup_runs.storage_driver FROM backup_runs
JOIN account_members ON account_members.account_id = backup_runs.account_id
WHERE ?1 OR account_members.user_id = ?2
GROUP BY backup_runs.id
ORDER BY backup_runs.created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListBackupRunsPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListBackupRunsPage(ctx context.Context, arg ListBackupRunsPageParams) ([]BackupRun, error) {
	rows, err := q.db.QueryContext(ctx, listBackupRunsPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupRun{}
	for rows.Next() {
		var i BackupRun
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.AccountID,
			&i.NodeID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.StorageDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueBackupPlans = `-- name: ListDueBackupPlans :many
SELECT id, account_id, node_id, name, schedule, retention_count, include_files, include_databases, enabled, last_run_at, next_run_at, created_at, updated_at, storage_driver FROM backup_plans
WHERE enabled = 1 AND schedule <> '' AND next_run_at IS NOT NULL AND next_run_at <= ?
ORDER BY next_run_at
`

func (q *Queries) ListDueBackupPlans(ctx context.Context, nextRunAt sql.NullInt64) ([]BackupPlan, error) {
	rows, err := q.db.QueryContext(ctx, listDueBackupPlans, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupPlan{}
	for rows.Next() {
		var i BackupPlan
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.RetentionCount,
			&i.IncludeFiles,
			&i.IncludeDatabases,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredBackupArtifacts = `-- name: ListExpiredBackupArtifacts :many
SELECT backup_artifacts.id, backup_artifacts.run_id, backup_artifacts.account_id, backup_artifacts.node_id, backup_artifacts.path, backup_artifacts.checksum, backup_artifacts.size_bytes, backup_artifacts.manifest, backup_artifacts.created_at, backup_artifacts.storage_driver FROM backup_artifacts
JOIN backup_runs ON backup_runs.id = backup_artifacts.run_id
WHERE backup_runs.plan_id = ?
ORDER BY backup_artifacts.created_at DESC
LIMIT -1 OFFSET ?
`

type ListExpiredBackupArtifactsParams struct {
	PlanID sql.NullString `json:"plan_id"`
	Offset int64          `json:"offset"`
}

func (q *Queries) ListExpiredBackupArtifacts(ctx context.Context, arg ListExpiredBackupArtifactsParams) ([]BackupArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredBackupArtifacts, arg.PlanID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupArtifact{}
	for rows.Next() {
		var i BackupArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AccountID,
			&i.NodeID,
			&i.Path,
			&i.Checksum,
			&i.SizeBytes,
			&i.Manifest,
			&i.CreatedAt,
			&i.StorageDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupPlanRun = `-- name: MarkBackupPlanRun :exec
UPDATE backup_plans SET last_run_at = ?, next_run_at = ?, updated_at = ? WHERE id = ?
`

type MarkBackupPlanRunParams struct {
	LastRunAt sql.NullInt64 `json:"last_run_at"`
	NextRunAt sql.NullInt64 `json:"next_run_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) MarkBackupPlanRun(ctx context.Context, arg MarkBackupPlanRunParams) error {
	_, err := q.db.ExecContext(ctx, markBackupPlanRun,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateBackupPlan = `-- name: UpdateBackupPlan :one
UPDATE backup_plans SET
    name = ?, schedule = ?, retention_count = ?, include_files = ?,
    include_databases = ?, storage_driver = ?, enabled = ?, next_run_at = ?, updated_at = ?
WHERE id = ?
RETURNING id, account_id, node_id, name, schedule, retention_count, include_files, include_databases, enabled, last_run_at, next_run_at, created_at, updated_at, storage_driver
`

type UpdateBackupPlanParams struct {
	Name             string        `json:"name"`
	Schedule         string        `json:"schedule"`
	RetentionCount   int64         `json:"retention_count"`
	IncludeFiles     int64         `json:"include_files"`
	IncludeDatabases int64         `json:"include_databases"`
	StorageDriver    string        `json:"storage_driver"`
	Enabled          int64         `json:"enabled"`
	NextRunAt        sql.NullInt64 `json:"next_run_at"`
	UpdatedAt        int64         `json:"updated_at"`
	ID               string        `json:"id"`
}

func (q *Queries) UpdateBackupPlan(ctx context.Context, arg UpdateBackupPlanParams) (BackupPlan, error) {
	row := q.db.QueryRowContext(ctx, updateBackupPlan,
		arg.Name,
		arg.Schedule,
		arg.RetentionCount,
		arg.IncludeFiles,
		arg.IncludeDatabases,
		arg.StorageDriver,
		arg.Enabled,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i BackupPlan
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.RetentionCount,
		&i.IncludeFiles,
		&i.IncludeDatabases,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageDriver,
	)
	return i, err
}

const updateBackupRun = `-- name: UpdateBackupRun :exec
UPDATE backup_runs SET status = ?, error = ?,
    started_at = COALESCE(?, started_at), finished_at = COALESCE(?, finished_at)
WHERE id = ?
`

type UpdateBackupRunParams struct {
	Status     string        `json:"status"`
	Error      string        `json:"error"`
	StartedAt  sql.NullInt64 `json:"started_at"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateBackupRun(ctx context.Context, arg UpdateBackupRunParams) error {
	_, err := q.db.ExecContext(ctx, updateBackupRun,
		arg.Status,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const upsertRestoredDatabase = `-- name: UpsertRestoredDatabase :exec
INSERT INTO databases (id, account_id, node_id, name, system_name, driver, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, 'active', ?, ?)
ON CONFLICT(id) DO UPDATE SET name = excluded.name, system_name = excluded.system_name,
    driver = excluded.driver, status = 'active', updated_at = excluded.updated_at
`

type UpsertRestoredDatabaseParams struct {
	ID         string `json:"id"`
	AccountID  string `json:"account_id"`
	NodeID     string `json:"node_id"`
	Name       string `json:"name"`
	SystemName string `json:"system_name"`
	Driver     string `json:"driver"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) UpsertRestoredDatabase(ctx context.Context, arg UpsertRestoredDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestoredDatabase,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.SystemName,
		arg.Driver,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertRestoredScheduledTask = `-- name: UpsertRestoredScheduledTask :exec
INSERT INTO scheduled_tasks (id, account_id, node_id, name, schedule, command, scheduler_driver, kind, enabled, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CASE WHEN ? = 1 THEN 'active' ELSE 'disabled' END, ?, ?)
ON CONFLICT(id) DO UPDATE SET name = excluded.name, schedule = excluded.schedule,
    command = excluded.command, scheduler_driver = excluded.scheduler_driver, kind = excluded.kind, enabled = excluded.enabled,
    status = CASE WHEN excluded.enabled = 1 THEN 'active' ELSE 'disabled' END,
    updated_at = excluded.updated_at
`

type UpsertRestoredScheduledTaskParams struct {
	ID              string      `json:"id"`
	AccountID       string      `json:"account_id"`
	NodeID          string      `json:"node_id"`
	Name            string      `json:"name"`
	Schedule        string      `json:"schedule"`
	Command         string      `json:"command"`
	SchedulerDriver string      `json:"scheduler_driver"`
	Kind            string      `json:"kind"`
	Enabled         int64       `json:"enabled"`
	Column10        interface{} `json:"column_10"`
	CreatedAt       int64       `json:"created_at"`
	UpdatedAt       int64       `json:"updated_at"`
}

func (q *Queries) UpsertRestoredScheduledTask(ctx context.Context, arg UpsertRestoredScheduledTaskParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestoredScheduledTask,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.SchedulerDriver,
		arg.Kind,
		arg.Enabled,
		arg.Column10,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertRestoredWebsite = `-- name: UpsertRestoredWebsite :exec
INSERT INTO websites (
    id, account_id, node_id, name, kind, document_root, web_driver,
    runtime_driver, runtime_version, status, enabled, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CASE WHEN ? = 1 THEN 'active' ELSE 'disabled' END, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET name = excluded.name, kind = excluded.kind,
    document_root = excluded.document_root, web_driver = excluded.web_driver,
    runtime_driver = excluded.runtime_driver, runtime_version = excluded.runtime_version,
    status = excluded.status, enabled = excluded.enabled, updated_at = excluded.updated_at
`

type UpsertRestoredWebsiteParams struct {
	ID             string      `json:"id"`
	AccountID      string      `json:"account_id"`
	NodeID         string      `json:"node_id"`
	Name           string      `json:"name"`
	Kind           string      `json:"kind"`
	DocumentRoot   string      `json:"document_root"`
	WebDriver      string      `json:"web_driver"`
	RuntimeDriver  string      `json:"runtime_driver"`
	RuntimeVersion string      `json:"runtime_version"`
	Column10       interface{} `json:"column_10"`
	Enabled        int64       `json:"enabled"`
	CreatedAt      int64       `json:"created_at"`
	UpdatedAt      int64       `json:"updated_at"`
}

func (q *Queries) UpsertRestoredWebsite(ctx context.Context, arg UpsertRestoredWebsiteParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestoredWebsite,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.Kind,
		arg.DocumentRoot,
		arg.WebDriver,
		arg.RuntimeDriver,
		arg.RuntimeVersion,
		arg.Column10,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertRestoredWebsiteDomain = `-- name: UpsertRestoredWebsiteDomain :exec
INSERT INTO website_domains (
    id, website_id, hostname, kind, status, enabled, created_at, updated_at
)
VALUES (?, ?, ?, ?, CASE WHEN ? = 1 THEN 'active' ELSE 'disabled' END, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET hostname = excluded.hostname, kind = excluded.kind,
    status = excluded.status, enabled = excluded.enabled, updated_at = excluded.updated_at
`

type UpsertRestoredWebsiteDomainParams struct {
	ID        string      `json:"id"`
	WebsiteID string      `json:"website_id"`
	Hostname  string      `json:"hostname"`
	Kind      string      `json:"kind"`
	Column5   interface{} `json:"column_5"`
	Enabled   int64       `json:"enabled"`
	CreatedAt int64       `json:"created_at"`
	UpdatedAt int64       `json:"updated_at"`
}

func (q *Queries) UpsertRestoredWebsiteDomain(ctx context.Context, arg UpsertRestoredWebsiteDomainParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestoredWebsiteDomain,
		arg.ID,
		arg.WebsiteID,
		arg.Hostname,
		arg.Kind,
		arg.Column5,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
