// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package dbgen

import (
	"context"
	"database/sql"
)

const certificatePendingJobExists = `-- name: CertificatePendingJobExists :one
SELECT EXISTS(
    SELECT 1 FROM jobs
    WHERE kind = 'certificate.renew' AND status IN ('queued', 'running')
      AND json_extract(payload, '$.certificateId') = ?
)
`

func (q *Queries) CertificatePendingJobExists(ctx context.Context, payload string) (bool, error) {
	row := q.db.QueryRowContext(ctx, certificatePendingJobExists, payload)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (
    id, domain_id, node_id, kind, name, email, status, redirect_https,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?)
RETURNING id, domain_id, node_id, kind, name, email, status, redirect_https, expires_at, renew_after, error, created_at, updated_at
`

type CreateCertificateParams struct {
	ID            string         `json:"id"`
	DomainID      sql.NullString `json:"domain_id"`
	NodeID        string         `json:"node_id"`
	Kind          string         `json:"kind"`
	Name          string         `json:"name"`
	Email         string         `json:"email"`
	RedirectHttps int64          `json:"redirect_https"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCertificate,
		arg.ID,
		arg.DomainID,
		arg.NodeID,
		arg.Kind,
		arg.Name,
		arg.Email,
		arg.RedirectHttps,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.NodeID,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.RedirectHttps,
		&i.ExpiresAt,
		&i.RenewAfter,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCertificate = `-- name: DeleteCertificate :exec
DELETE FROM certificates WHERE id = ?
`

func (q *Queries) DeleteCertificate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCertificate, id)
	return err
}

const deleteCertificateNames = `-- name: DeleteCertificateNames :exec
DELETE FROM certificate_names WHERE certificate_id = ?
`

func (q *Queries) DeleteCertificateNames(ctx context.Context, certificateID string) error {
	_, err := q.db.ExecContext(ctx, deleteCertificateNames, certificateID)
	return err
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, domain_id, node_id, kind, name, email, status, redirect_https, expires_at, renew_after, error, created_at, updated_at FROM certificates WHERE id = ? LIMIT 1
`

func (q *Queries) GetCertificate(ctx context.Context, id string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificate, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.NodeID,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.RedirectHttps,
		&i.ExpiresAt,
		&i.RenewAfter,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainCertificate = `-- name: GetDomainCertificate :one
SELECT id, domain_id, node_id, kind, name, email, status, redirect_https, expires_at, renew_after, error, created_at, updated_at FROM certificates WHERE domain_id = ? LIMIT 1
`

func (q *Queries) GetDomainCertificate(ctx context.Context, domainID sql.NullString) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getDomainCertificate, domainID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.NodeID,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.RedirectHttps,
		&i.ExpiresAt,
		&i.RenewAfter,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPanelCertificate = `-- name: GetPanelCertificate :one
SELECT id, domain_id, node_id, kind, name, email, status, redirect_https, expires_at, renew_after, error, created_at, updated_at FROM certificates WHERE kind = 'panel' LIMIT 1
`

func (q *Queries) GetPanelCertificate(ctx context.Context) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getPanelCertificate)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.NodeID,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.RedirectHttps,
		&i.ExpiresAt,
		&i.RenewAfter,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertificateNames = `-- name: ListCertificateNames :many
SELECT name FROM certificate_names WHERE certificate_id = ? ORDER BY name
`

func (q *Queries) ListCertificateNames(ctx context.Context, certificateID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCertificateNames, certificateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificates = `-- name: ListCertificates :many
SELECT certificates.id, certificates.domain_id, certificates.node_id, certificates.kind, certificates.name, certificates.email, certificates.status, certificates.redirect_https, certificates.expires_at, certificates.renew_after, certificates.error, certificates.created_at, certificates.updated_at FROM certificates
LEFT JOIN domains ON domains.id = certificates.domain_id
LEFT JOIN account_members ON account_members.account_id = domains.account_id
WHERE ? OR certificates.kind = 'panel' OR account_members.user_id = ?
GROUP BY certificates.id
ORDER BY certificates.created_at DESC
`

type ListCertificatesParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, listCertificates, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.NodeID,
			&i.Kind,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.RedirectHttps,
			&i.ExpiresAt,
			&i.RenewAfter,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCertificates = `-- name: ListDueCertificates :many
SELECT id, domain_id, node_id, kind, name, email, status, redirect_https, expires_at, renew_after, error, created_at, updated_at FROM certificates
WHERE status = 'active' AND renew_after IS NOT NULL AND renew_after <= ?
ORDER BY renew_after ASC
`

func (q *Queries) ListDueCertificates(ctx context.Context, renewAfter sql.NullInt64) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, listDueCertificates, renewAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.NodeID,
			&i.Kind,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.RedirectHttps,
			&i.ExpiresAt,
			&i.RenewAfter,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueCertificate = `-- name: QueueCertificate :exec
UPDATE certificates
SET name = ?, email = ?, redirect_https = ?, status = 'pending', error = '', updated_at = ?
WHERE id = ?
`

type QueueCertificateParams struct {
	Name          string `json:"name"`
	Email         string `json:"email"`
	RedirectHttps int64  `json:"redirect_https"`
	UpdatedAt     int64  `json:"updated_at"`
	ID            string `json:"id"`
}

func (q *Queries) QueueCertificate(ctx context.Context, arg QueueCertificateParams) error {
	_, err := q.db.ExecContext(ctx, queueCertificate,
		arg.Name,
		arg.Email,
		arg.RedirectHttps,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const replaceCertificateName = `-- name: ReplaceCertificateName :exec
INSERT OR IGNORE INTO certificate_names (certificate_id, name) VALUES (?, ?)
`

type ReplaceCertificateNameParams struct {
	CertificateID string `json:"certificate_id"`
	Name          string `json:"name"`
}

func (q *Queries) ReplaceCertificateName(ctx context.Context, arg ReplaceCertificateNameParams) error {
	_, err := q.db.ExecContext(ctx, replaceCertificateName, arg.CertificateID, arg.Name)
	return err
}

const setCertificateResult = `-- name: SetCertificateResult :exec
UPDATE certificates
SET status = ?, expires_at = ?, renew_after = ?, error = ?, updated_at = ?
WHERE id = ?
`

type SetCertificateResultParams struct {
	Status     string        `json:"status"`
	ExpiresAt  sql.NullInt64 `json:"expires_at"`
	RenewAfter sql.NullInt64 `json:"renew_after"`
	Error      string        `json:"error"`
	UpdatedAt  int64         `json:"updated_at"`
	ID         string        `json:"id"`
}

func (q *Queries) SetCertificateResult(ctx context.Context, arg SetCertificateResultParams) error {
	_, err := q.db.ExecContext(ctx, setCertificateResult,
		arg.Status,
		arg.ExpiresAt,
		arg.RenewAfter,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
