// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cron.sql

package dbgen

import (
	"context"
)

const countCronJobs = `-- name: CountCronJobs :one
SELECT COUNT(DISTINCT cron_jobs.id) FROM cron_jobs
JOIN account_members ON account_members.account_id = cron_jobs.account_id
WHERE ?1 OR account_members.user_id = ?2
`

type CountCronJobsParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountCronJobs(ctx context.Context, arg CountCronJobsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCronJobs, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCronJob = `-- name: CreateCronJob :one
INSERT INTO cron_jobs (
    id, account_id, node_id, name, schedule, command, scheduler_driver, enabled, status,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)
RETURNING id, account_id, node_id, name, schedule, command, enabled, status, created_at, updated_at, scheduler_driver
`

type CreateCronJobParams struct {
	ID              string `json:"id"`
	AccountID       string `json:"account_id"`
	NodeID          string `json:"node_id"`
	Name            string `json:"name"`
	Schedule        string `json:"schedule"`
	Command         string `json:"command"`
	SchedulerDriver string `json:"scheduler_driver"`
	Enabled         int64  `json:"enabled"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) CreateCronJob(ctx context.Context, arg CreateCronJobParams) (CronJob, error) {
	row := q.db.QueryRowContext(ctx, createCronJob,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.SchedulerDriver,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchedulerDriver,
	)
	return i, err
}

const deleteCronJob = `-- name: DeleteCronJob :exec
DELETE FROM cron_jobs WHERE id = ?
`

func (q *Queries) DeleteCronJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCronJob, id)
	return err
}

const getCronJob = `-- name: GetCronJob :one
SELECT id, account_id, node_id, name, schedule, command, enabled, status, created_at, updated_at, scheduler_driver FROM cron_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetCronJob(ctx context.Context, id string) (CronJob, error) {
	row := q.db.QueryRowContext(ctx, getCronJob, id)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchedulerDriver,
	)
	return i, err
}

const listAccountCronJobs = `-- name: ListAccountCronJobs :many
SELECT id, account_id, node_id, name, schedule, command, enabled, status, created_at, updated_at, scheduler_driver FROM cron_jobs WHERE account_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListAccountCronJobs(ctx context.Context, accountID string) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listAccountCronJobs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.Enabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchedulerDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronJobs = `-- name: ListCronJobs :many
SELECT cron_jobs.id, cron_jobs.account_id, cron_jobs.node_id, cron_jobs.name, cron_jobs.schedule, cron_jobs.command, cron_jobs.enabled, cron_jobs.status, cron_jobs.created_at, cron_jobs.updated_at, cron_jobs.scheduler_driver FROM cron_jobs
JOIN account_members ON account_members.account_id = cron_jobs.account_id
WHERE ? OR account_members.user_id = ?
GROUP BY cron_jobs.id
ORDER BY cron_jobs.created_at ASC
`

type ListCronJobsParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListCronJobs(ctx context.Context, arg ListCronJobsParams) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listCronJobs, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.Enabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchedulerDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronJobsPage = `-- name: ListCronJobsPage :many
SELECT cron_jobs.id, cron_jobs.account_id, cron_jobs.node_id, cron_jobs.name, cron_jobs.schedule, cron_jobs.command, cron_jobs.enabled, cron_jobs.status, cron_jobs.created_at, cron_jobs.updated_at, cron_jobs.scheduler_driver FROM cron_jobs
JOIN account_members ON account_members.account_id = cron_jobs.account_id
WHERE ?1 OR account_members.user_id = ?2
GROUP BY cron_jobs.id
ORDER BY cron_jobs.created_at ASC
LIMIT ?4 OFFSET ?3
`

type ListCronJobsPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListCronJobsPage(ctx context.Context, arg ListCronJobsPageParams) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listCronJobsPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.Enabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchedulerDriver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountCronStatuses = `-- name: UpdateAccountCronStatuses :exec
UPDATE cron_jobs
SET status = CASE WHEN enabled = 1 THEN ? ELSE ? END, updated_at = ?
WHERE account_id = ?
`

type UpdateAccountCronStatusesParams struct {
	Status    string `json:"status"`
	Status_2  string `json:"status_2"`
	UpdatedAt int64  `json:"updated_at"`
	AccountID string `json:"account_id"`
}

func (q *Queries) UpdateAccountCronStatuses(ctx context.Context, arg UpdateAccountCronStatusesParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountCronStatuses,
		arg.Status,
		arg.Status_2,
		arg.UpdatedAt,
		arg.AccountID,
	)
	return err
}

const updateCronJob = `-- name: UpdateCronJob :one
UPDATE cron_jobs
SET name = ?, schedule = ?, command = ?, scheduler_driver = ?, enabled = ?, status = 'pending', updated_at = ?
WHERE id = ?
RETURNING id, account_id, node_id, name, schedule, command, enabled, status, created_at, updated_at, scheduler_driver
`

type UpdateCronJobParams struct {
	Name            string `json:"name"`
	Schedule        string `json:"schedule"`
	Command         string `json:"command"`
	SchedulerDriver string `json:"scheduler_driver"`
	Enabled         int64  `json:"enabled"`
	UpdatedAt       int64  `json:"updated_at"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateCronJob(ctx context.Context, arg UpdateCronJobParams) (CronJob, error) {
	row := q.db.QueryRowContext(ctx, updateCronJob,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.SchedulerDriver,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchedulerDriver,
	)
	return i, err
}

const updateCronJobStatus = `-- name: UpdateCronJobStatus :exec
UPDATE cron_jobs SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateCronJobStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateCronJobStatus(ctx context.Context, arg UpdateCronJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCronJobStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
