// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: databases.sql

package dbgen

import (
	"context"
)

const countDatabaseGrants = `-- name: CountDatabaseGrants :one
SELECT COUNT(*) FROM (
    SELECT database_grants.database_id, database_grants.database_user_id
    FROM database_grants
    JOIN databases ON databases.id = database_grants.database_id
    JOIN account_members ON account_members.account_id = databases.account_id
    WHERE ?1 OR account_members.user_id = ?2
    GROUP BY database_grants.database_id, database_grants.database_user_id
)
`

type CountDatabaseGrantsParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountDatabaseGrants(ctx context.Context, arg CountDatabaseGrantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDatabaseGrants, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDatabaseUsers = `-- name: CountDatabaseUsers :one
SELECT COUNT(DISTINCT database_users.id) FROM database_users
JOIN account_members ON account_members.account_id = database_users.account_id
WHERE ?1 OR account_members.user_id = ?2
`

type CountDatabaseUsersParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountDatabaseUsers(ctx context.Context, arg CountDatabaseUsersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDatabaseUsers, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDatabases = `-- name: CountDatabases :one
SELECT COUNT(DISTINCT databases.id) FROM databases
JOIN account_members ON account_members.account_id = databases.account_id
WHERE ?1 OR account_members.user_id = ?2
`

type CountDatabasesParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountDatabases(ctx context.Context, arg CountDatabasesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDatabases, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (
    id, account_id, node_id, name, system_name, status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)
RETURNING id, account_id, node_id, name, system_name, status, created_at, updated_at
`

type CreateDatabaseParams struct {
	ID         string `json:"id"`
	AccountID  string `json:"account_id"`
	NodeID     string `json:"node_id"`
	Name       string `json:"name"`
	SystemName string `json:"system_name"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRowContext(ctx, createDatabase,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.SystemName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.SystemName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDatabaseUser = `-- name: CreateDatabaseUser :one
INSERT INTO database_users (
    id, account_id, node_id, name, system_name, status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)
RETURNING id, account_id, node_id, name, system_name, status, created_at, updated_at
`

type CreateDatabaseUserParams struct {
	ID         string `json:"id"`
	AccountID  string `json:"account_id"`
	NodeID     string `json:"node_id"`
	Name       string `json:"name"`
	SystemName string `json:"system_name"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) CreateDatabaseUser(ctx context.Context, arg CreateDatabaseUserParams) (DatabaseUser, error) {
	row := q.db.QueryRowContext(ctx, createDatabaseUser,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.SystemName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DatabaseUser
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.SystemName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const databaseNameExists = `-- name: DatabaseNameExists :one
SELECT EXISTS(SELECT 1 FROM databases WHERE account_id = ? AND name = ? COLLATE NOCASE)
`

type DatabaseNameExistsParams struct {
	AccountID string `json:"account_id"`
	Name      string `json:"name"`
}

func (q *Queries) DatabaseNameExists(ctx context.Context, arg DatabaseNameExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, databaseNameExists, arg.AccountID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const databaseUserNameExists = `-- name: DatabaseUserNameExists :one
SELECT EXISTS(SELECT 1 FROM database_users WHERE account_id = ? AND name = ? COLLATE NOCASE)
`

type DatabaseUserNameExistsParams struct {
	AccountID string `json:"account_id"`
	Name      string `json:"name"`
}

func (q *Queries) DatabaseUserNameExists(ctx context.Context, arg DatabaseUserNameExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, databaseUserNameExists, arg.AccountID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE FROM databases WHERE id = ?
`

func (q *Queries) DeleteDatabase(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDatabase, id)
	return err
}

const deleteDatabaseGrant = `-- name: DeleteDatabaseGrant :exec
DELETE FROM database_grants WHERE database_id = ? AND database_user_id = ?
`

type DeleteDatabaseGrantParams struct {
	DatabaseID     string `json:"database_id"`
	DatabaseUserID string `json:"database_user_id"`
}

func (q *Queries) DeleteDatabaseGrant(ctx context.Context, arg DeleteDatabaseGrantParams) error {
	_, err := q.db.ExecContext(ctx, deleteDatabaseGrant, arg.DatabaseID, arg.DatabaseUserID)
	return err
}

const deleteDatabaseUser = `-- name: DeleteDatabaseUser :exec
DELETE FROM database_users WHERE id = ?
`

func (q *Queries) DeleteDatabaseUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDatabaseUser, id)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, account_id, node_id, name, system_name, status, created_at, updated_at FROM databases WHERE id = ? LIMIT 1
`

func (q *Queries) GetDatabase(ctx context.Context, id string) (Database, error) {
	row := q.db.QueryRowContext(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.SystemName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseGrant = `-- name: GetDatabaseGrant :one
SELECT database_id, database_user_id, status, created_at, updated_at FROM database_grants WHERE database_id = ? AND database_user_id = ? LIMIT 1
`

type GetDatabaseGrantParams struct {
	DatabaseID     string `json:"database_id"`
	DatabaseUserID string `json:"database_user_id"`
}

func (q *Queries) GetDatabaseGrant(ctx context.Context, arg GetDatabaseGrantParams) (DatabaseGrant, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseGrant, arg.DatabaseID, arg.DatabaseUserID)
	var i DatabaseGrant
	err := row.Scan(
		&i.DatabaseID,
		&i.DatabaseUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDatabaseUser = `-- name: GetDatabaseUser :one
SELECT id, account_id, node_id, name, system_name, status, created_at, updated_at FROM database_users WHERE id = ? LIMIT 1
`

func (q *Queries) GetDatabaseUser(ctx context.Context, id string) (DatabaseUser, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseUser, id)
	var i DatabaseUser
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.SystemName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountDatabaseSystemNames = `-- name: ListAccountDatabaseSystemNames :many
SELECT system_name FROM databases
WHERE account_id = ? AND status = 'active'
ORDER BY system_name
`

func (q *Queries) ListAccountDatabaseSystemNames(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAccountDatabaseSystemNames, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var system_name string
		if err := rows.Scan(&system_name); err != nil {
			return nil, err
		}
		items = append(items, system_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabaseGrants = `-- name: ListDatabaseGrants :many
SELECT database_grants.database_id, database_grants.database_user_id, database_grants.status, database_grants.created_at, database_grants.updated_at FROM database_grants
JOIN databases ON databases.id = database_grants.database_id
JOIN account_members ON account_members.account_id = databases.account_id
WHERE ? OR account_members.user_id = ?
GROUP BY database_grants.database_id, database_grants.database_user_id
ORDER BY database_grants.created_at ASC
`

type ListDatabaseGrantsParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListDatabaseGrants(ctx context.Context, arg ListDatabaseGrantsParams) ([]DatabaseGrant, error) {
	rows, err := q.db.QueryContext(ctx, listDatabaseGrants, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseGrant{}
	for rows.Next() {
		var i DatabaseGrant
		if err := rows.Scan(
			&i.DatabaseID,
			&i.DatabaseUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabaseGrantsPage = `-- name: ListDatabaseGrantsPage :many
SELECT database_grants.database_id, database_grants.database_user_id, database_grants.status, database_grants.created_at, database_grants.updated_at FROM database_grants
JOIN databases ON databases.id = database_grants.database_id
JOIN account_members ON account_members.account_id = databases.account_id
WHERE ?1 OR account_members.user_id = ?2
GROUP BY database_grants.database_id, database_grants.database_user_id
ORDER BY database_grants.created_at ASC
LIMIT ?4 OFFSET ?3
`

type ListDatabaseGrantsPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListDatabaseGrantsPage(ctx context.Context, arg ListDatabaseGrantsPageParams) ([]DatabaseGrant, error) {
	rows, err := q.db.QueryContext(ctx, listDatabaseGrantsPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseGrant{}
	for rows.Next() {
		var i DatabaseGrant
		if err := rows.Scan(
			&i.DatabaseID,
			&i.DatabaseUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabaseUsers = `-- name: ListDatabaseUsers :many
SELECT database_users.id, database_users.account_id, database_users.node_id, database_users.name, database_users.system_name, database_users.status, database_users.created_at, database_users.updated_at FROM database_users
JOIN account_members ON account_members.account_id = database_users.account_id
WHERE ? OR account_members.user_id = ?
GROUP BY database_users.id
ORDER BY database_users.created_at ASC
`

type ListDatabaseUsersParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListDatabaseUsers(ctx context.Context, arg ListDatabaseUsersParams) ([]DatabaseUser, error) {
	rows, err := q.db.QueryContext(ctx, listDatabaseUsers, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseUser{}
	for rows.Next() {
		var i DatabaseUser
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.SystemName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabaseUsersPage = `-- name: ListDatabaseUsersPage :many
SELECT database_users.id, database_users.account_id, database_users.node_id, database_users.name, database_users.system_name, database_users.status, database_users.created_at, database_users.updated_at FROM database_users
JOIN account_members ON account_members.account_id = database_users.account_id
WHERE ?1 OR account_members.user_id = ?2
GROUP BY database_users.id
ORDER BY database_users.created_at ASC
LIMIT ?4 OFFSET ?3
`

type ListDatabaseUsersPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListDatabaseUsersPage(ctx context.Context, arg ListDatabaseUsersPageParams) ([]DatabaseUser, error) {
	rows, err := q.db.QueryContext(ctx, listDatabaseUsersPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseUser{}
	for rows.Next() {
		var i DatabaseUser
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.SystemName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabases = `-- name: ListDatabases :many
SELECT databases.id, databases.account_id, databases.node_id, databases.name, databases.system_name, databases.status, databases.created_at, databases.updated_at FROM databases
JOIN account_members ON account_members.account_id = databases.account_id
WHERE ? OR account_members.user_id = ?
GROUP BY databases.id
ORDER BY databases.created_at ASC
`

type ListDatabasesParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListDatabases(ctx context.Context, arg ListDatabasesParams) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabases, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.SystemName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesPage = `-- name: ListDatabasesPage :many
SELECT databases.id, databases.account_id, databases.node_id, databases.name, databases.system_name, databases.status, databases.created_at, databases.updated_at FROM databases
JOIN account_members ON account_members.account_id = databases.account_id
WHERE ?1 OR account_members.user_id = ?2
GROUP BY databases.id
ORDER BY databases.created_at ASC
LIMIT ?4 OFFSET ?3
`

type ListDatabasesPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListDatabasesPage(ctx context.Context, arg ListDatabasesPageParams) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabasesPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.SystemName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueDatabaseDelete = `-- name: QueueDatabaseDelete :one
UPDATE databases SET status = 'pending', updated_at = ? WHERE id = ? RETURNING id, account_id, node_id, name, system_name, status, created_at, updated_at
`

type QueueDatabaseDeleteParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDatabaseDelete(ctx context.Context, arg QueueDatabaseDeleteParams) (Database, error) {
	row := q.db.QueryRowContext(ctx, queueDatabaseDelete, arg.UpdatedAt, arg.ID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.SystemName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueDatabaseGrantDelete = `-- name: QueueDatabaseGrantDelete :one
UPDATE database_grants SET status = 'pending', updated_at = ?
WHERE database_id = ? AND database_user_id = ?
RETURNING database_id, database_user_id, status, created_at, updated_at
`

type QueueDatabaseGrantDeleteParams struct {
	UpdatedAt      int64  `json:"updated_at"`
	DatabaseID     string `json:"database_id"`
	DatabaseUserID string `json:"database_user_id"`
}

func (q *Queries) QueueDatabaseGrantDelete(ctx context.Context, arg QueueDatabaseGrantDeleteParams) (DatabaseGrant, error) {
	row := q.db.QueryRowContext(ctx, queueDatabaseGrantDelete, arg.UpdatedAt, arg.DatabaseID, arg.DatabaseUserID)
	var i DatabaseGrant
	err := row.Scan(
		&i.DatabaseID,
		&i.DatabaseUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueDatabaseUserDelete = `-- name: QueueDatabaseUserDelete :one
UPDATE database_users SET status = 'pending', updated_at = ? WHERE id = ? RETURNING id, account_id, node_id, name, system_name, status, created_at, updated_at
`

type QueueDatabaseUserDeleteParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDatabaseUserDelete(ctx context.Context, arg QueueDatabaseUserDeleteParams) (DatabaseUser, error) {
	row := q.db.QueryRowContext(ctx, queueDatabaseUserDelete, arg.UpdatedAt, arg.ID)
	var i DatabaseUser
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.SystemName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDatabaseGrantStatus = `-- name: UpdateDatabaseGrantStatus :exec
UPDATE database_grants SET status = ?, updated_at = ?
WHERE database_id = ? AND database_user_id = ?
`

type UpdateDatabaseGrantStatusParams struct {
	Status         string `json:"status"`
	UpdatedAt      int64  `json:"updated_at"`
	DatabaseID     string `json:"database_id"`
	DatabaseUserID string `json:"database_user_id"`
}

func (q *Queries) UpdateDatabaseGrantStatus(ctx context.Context, arg UpdateDatabaseGrantStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDatabaseGrantStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.DatabaseID,
		arg.DatabaseUserID,
	)
	return err
}

const updateDatabaseStatus = `-- name: UpdateDatabaseStatus :exec
UPDATE databases SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateDatabaseStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDatabaseStatus(ctx context.Context, arg UpdateDatabaseStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDatabaseStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateDatabaseUserStatus = `-- name: UpdateDatabaseUserStatus :exec
UPDATE database_users SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateDatabaseUserStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDatabaseUserStatus(ctx context.Context, arg UpdateDatabaseUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDatabaseUserStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const upsertDatabaseGrant = `-- name: UpsertDatabaseGrant :one
INSERT INTO database_grants (
    database_id, database_user_id, status, created_at, updated_at
) VALUES (?, ?, 'pending', ?, ?)
ON CONFLICT(database_id, database_user_id) DO UPDATE SET
    status = 'pending', updated_at = excluded.updated_at
RETURNING database_id, database_user_id, status, created_at, updated_at
`

type UpsertDatabaseGrantParams struct {
	DatabaseID     string `json:"database_id"`
	DatabaseUserID string `json:"database_user_id"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) UpsertDatabaseGrant(ctx context.Context, arg UpsertDatabaseGrantParams) (DatabaseGrant, error) {
	row := q.db.QueryRowContext(ctx, upsertDatabaseGrant,
		arg.DatabaseID,
		arg.DatabaseUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DatabaseGrant
	err := row.Scan(
		&i.DatabaseID,
		&i.DatabaseUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
