// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dns.sql

package dbgen

import (
	"context"
)

const completeDNSRecordSync = `-- name: CompleteDNSRecordSync :exec
UPDATE dns_records
SET status = 'active', synced_name = name, synced_type = type, updated_at = ?
WHERE id = ?
`

type CompleteDNSRecordSyncParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteDNSRecordSync(ctx context.Context, arg CompleteDNSRecordSyncParams) error {
	_, err := q.db.ExecContext(ctx, completeDNSRecordSync, arg.UpdatedAt, arg.ID)
	return err
}

const countDNSRecords = `-- name: CountDNSRecords :one
SELECT COUNT(*) FROM dns_records WHERE zone_id = ?
`

func (q *Queries) CountDNSRecords(ctx context.Context, zoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDNSRecords, zoneID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDNSZones = `-- name: CountDNSZones :one
SELECT COUNT(*) FROM dns_zones
`

func (q *Queries) CountDNSZones(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDNSZones)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserDNSZones = `-- name: CountUserDNSZones :one
SELECT COUNT(*) FROM dns_zones
WHERE EXISTS (
    SELECT 1 FROM account_members
    WHERE account_members.account_id = dns_zones.account_id
      AND account_members.user_id = ?
)
`

func (q *Queries) CountUserDNSZones(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserDNSZones, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDNSRecord = `-- name: CreateDNSRecord :one
INSERT INTO dns_records (
    id, zone_id, name, type, content, ttl, priority, synced_name, synced_type,
    status, created_at, updated_at
)
SELECT ?, ?, ?, ?, ?, ?, ?, '', '', 'pending', ?, ?
WHERE EXISTS (
    SELECT 1 FROM dns_zones
    WHERE dns_zones.id = ?10 AND dns_zones.status = 'active'
)
RETURNING id, zone_id, name, type, content, ttl, priority, synced_name, synced_type, status, created_at, updated_at
`

type CreateDNSRecordParams struct {
	ID        string `json:"id"`
	ZoneID    string `json:"zone_id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Content   string `json:"content"`
	Ttl       int64  `json:"ttl"`
	Priority  int64  `json:"priority"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateDNSRecord(ctx context.Context, arg CreateDNSRecordParams) (DnsRecord, error) {
	row := q.db.QueryRowContext(ctx, createDNSRecord,
		arg.ID,
		arg.ZoneID,
		arg.Name,
		arg.Type,
		arg.Content,
		arg.Ttl,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ZoneID,
	)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.Ttl,
		&i.Priority,
		&i.SyncedName,
		&i.SyncedType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDNSZone = `-- name: CreateDNSZone :one
INSERT INTO dns_zones (
    id, account_id, node_id, provider_id, name, primary_nameserver,
    secondary_nameserver, status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)
RETURNING id, account_id, node_id, provider_id, name, primary_nameserver, secondary_nameserver, status, created_at, updated_at
`

type CreateDNSZoneParams struct {
	ID                  string `json:"id"`
	AccountID           string `json:"account_id"`
	NodeID              string `json:"node_id"`
	ProviderID          string `json:"provider_id"`
	Name                string `json:"name"`
	PrimaryNameserver   string `json:"primary_nameserver"`
	SecondaryNameserver string `json:"secondary_nameserver"`
	CreatedAt           int64  `json:"created_at"`
	UpdatedAt           int64  `json:"updated_at"`
}

func (q *Queries) CreateDNSZone(ctx context.Context, arg CreateDNSZoneParams) (DnsZone, error) {
	row := q.db.QueryRowContext(ctx, createDNSZone,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.ProviderID,
		arg.Name,
		arg.PrimaryNameserver,
		arg.SecondaryNameserver,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DnsZone
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.ProviderID,
		&i.Name,
		&i.PrimaryNameserver,
		&i.SecondaryNameserver,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDNSRecord = `-- name: DeleteDNSRecord :exec
DELETE FROM dns_records WHERE id = ?
`

func (q *Queries) DeleteDNSRecord(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDNSRecord, id)
	return err
}

const deleteDNSZone = `-- name: DeleteDNSZone :exec
DELETE FROM dns_zones WHERE id = ?
`

func (q *Queries) DeleteDNSZone(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDNSZone, id)
	return err
}

const ensureDNSProvider = `-- name: EnsureDNSProvider :one
INSERT INTO dns_providers (
    id, node_id, name, driver, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (node_id, driver) DO UPDATE SET name = excluded.name
RETURNING id, node_id, name, driver, created_at, updated_at
`

type EnsureDNSProviderParams struct {
	ID        string `json:"id"`
	NodeID    string `json:"node_id"`
	Name      string `json:"name"`
	Driver    string `json:"driver"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) EnsureDNSProvider(ctx context.Context, arg EnsureDNSProviderParams) (DnsProvider, error) {
	row := q.db.QueryRowContext(ctx, ensureDNSProvider,
		arg.ID,
		arg.NodeID,
		arg.Name,
		arg.Driver,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Driver,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSProvider = `-- name: GetDNSProvider :one
SELECT id, node_id, name, driver, created_at, updated_at FROM dns_providers WHERE id = ? LIMIT 1
`

func (q *Queries) GetDNSProvider(ctx context.Context, id string) (DnsProvider, error) {
	row := q.db.QueryRowContext(ctx, getDNSProvider, id)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Driver,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSRecord = `-- name: GetDNSRecord :one
SELECT id, zone_id, name, type, content, ttl, priority, synced_name, synced_type, status, created_at, updated_at FROM dns_records WHERE id = ? LIMIT 1
`

func (q *Queries) GetDNSRecord(ctx context.Context, id string) (DnsRecord, error) {
	row := q.db.QueryRowContext(ctx, getDNSRecord, id)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.Ttl,
		&i.Priority,
		&i.SyncedName,
		&i.SyncedType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSSettings = `-- name: GetDNSSettings :one
SELECT id, primary_nameserver, secondary_nameserver, default_ttl, updated_at FROM dns_settings WHERE id = 1
`

func (q *Queries) GetDNSSettings(ctx context.Context) (DnsSetting, error) {
	row := q.db.QueryRowContext(ctx, getDNSSettings)
	var i DnsSetting
	err := row.Scan(
		&i.ID,
		&i.PrimaryNameserver,
		&i.SecondaryNameserver,
		&i.DefaultTtl,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSZone = `-- name: GetDNSZone :one
SELECT id, account_id, node_id, provider_id, name, primary_nameserver, secondary_nameserver, status, created_at, updated_at FROM dns_zones WHERE id = ? LIMIT 1
`

func (q *Queries) GetDNSZone(ctx context.Context, id string) (DnsZone, error) {
	row := q.db.QueryRowContext(ctx, getDNSZone, id)
	var i DnsZone
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.ProviderID,
		&i.Name,
		&i.PrimaryNameserver,
		&i.SecondaryNameserver,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDNSProviders = `-- name: ListDNSProviders :many
SELECT id, node_id, name, driver, created_at, updated_at FROM dns_providers ORDER BY created_at ASC
`

func (q *Queries) ListDNSProviders(ctx context.Context) ([]DnsProvider, error) {
	rows, err := q.db.QueryContext(ctx, listDNSProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsProvider{}
	for rows.Next() {
		var i DnsProvider
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Driver,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSRecords = `-- name: ListDNSRecords :many
SELECT id, zone_id, name, type, content, ttl, priority, synced_name, synced_type, status, created_at, updated_at FROM dns_records
WHERE zone_id = ?
ORDER BY name ASC, type ASC, content ASC
`

func (q *Queries) ListDNSRecords(ctx context.Context, zoneID string) ([]DnsRecord, error) {
	rows, err := q.db.QueryContext(ctx, listDNSRecords, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Name,
			&i.Type,
			&i.Content,
			&i.Ttl,
			&i.Priority,
			&i.SyncedName,
			&i.SyncedType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSRecordsByName = `-- name: ListDNSRecordsByName :many
SELECT id, zone_id, name, type, content, ttl, priority, synced_name, synced_type, status, created_at, updated_at FROM dns_records
WHERE zone_id = ? AND name = ? COLLATE NOCASE
`

type ListDNSRecordsByNameParams struct {
	ZoneID string `json:"zone_id"`
	Name   string `json:"name"`
}

func (q *Queries) ListDNSRecordsByName(ctx context.Context, arg ListDNSRecordsByNameParams) ([]DnsRecord, error) {
	rows, err := q.db.QueryContext(ctx, listDNSRecordsByName, arg.ZoneID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Name,
			&i.Type,
			&i.Content,
			&i.Ttl,
			&i.Priority,
			&i.SyncedName,
			&i.SyncedType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSRecordsPage = `-- name: ListDNSRecordsPage :many
SELECT id, zone_id, name, type, content, ttl, priority, synced_name, synced_type, status, created_at, updated_at FROM dns_records
WHERE zone_id = ?1
ORDER BY name ASC, type ASC, content ASC
LIMIT ?3 OFFSET ?2
`

type ListDNSRecordsPageParams struct {
	ZoneID     string `json:"zone_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) ListDNSRecordsPage(ctx context.Context, arg ListDNSRecordsPageParams) ([]DnsRecord, error) {
	rows, err := q.db.QueryContext(ctx, listDNSRecordsPage, arg.ZoneID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Name,
			&i.Type,
			&i.Content,
			&i.Ttl,
			&i.Priority,
			&i.SyncedName,
			&i.SyncedType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSZonesPage = `-- name: ListDNSZonesPage :many
SELECT id, account_id, node_id, provider_id, name, primary_nameserver, secondary_nameserver, status, created_at, updated_at FROM dns_zones
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListDNSZonesPageParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

func (q *Queries) ListDNSZonesPage(ctx context.Context, arg ListDNSZonesPageParams) ([]DnsZone, error) {
	rows, err := q.db.QueryContext(ctx, listDNSZonesPage, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsZone{}
	for rows.Next() {
		var i DnsZone
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.ProviderID,
			&i.Name,
			&i.PrimaryNameserver,
			&i.SecondaryNameserver,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDNSZonesPage = `-- name: ListUserDNSZonesPage :many
SELECT id, account_id, node_id, provider_id, name, primary_nameserver, secondary_nameserver, status, created_at, updated_at FROM dns_zones
WHERE EXISTS (
    SELECT 1 FROM account_members
    WHERE account_members.account_id = dns_zones.account_id
      AND account_members.user_id = ?1
)
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListUserDNSZonesPageParams struct {
	UserID     string `json:"user_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) ListUserDNSZonesPage(ctx context.Context, arg ListUserDNSZonesPageParams) ([]DnsZone, error) {
	rows, err := q.db.QueryContext(ctx, listUserDNSZonesPage, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsZone{}
	for rows.Next() {
		var i DnsZone
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.ProviderID,
			&i.Name,
			&i.PrimaryNameserver,
			&i.SecondaryNameserver,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueDNSRecordDelete = `-- name: QueueDNSRecordDelete :one
UPDATE dns_records
SET status = 'deleting', updated_at = ?
WHERE dns_records.id = ?
  AND dns_records.status NOT IN ('pending', 'deleting')
  AND EXISTS (
      SELECT 1 FROM dns_zones
      WHERE dns_zones.id = dns_records.zone_id AND dns_zones.status = 'active'
  )
RETURNING id, zone_id, name, type, content, ttl, priority, synced_name, synced_type, status, created_at, updated_at
`

type QueueDNSRecordDeleteParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDNSRecordDelete(ctx context.Context, arg QueueDNSRecordDeleteParams) (DnsRecord, error) {
	row := q.db.QueryRowContext(ctx, queueDNSRecordDelete, arg.UpdatedAt, arg.ID)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.Ttl,
		&i.Priority,
		&i.SyncedName,
		&i.SyncedType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueDNSRecordUpdate = `-- name: QueueDNSRecordUpdate :one
UPDATE dns_records
SET name = ?, type = ?, content = ?, ttl = ?, priority = ?, status = 'pending', updated_at = ?
WHERE dns_records.id = ?
  AND dns_records.status NOT IN ('pending', 'deleting')
  AND EXISTS (
      SELECT 1 FROM dns_zones
      WHERE dns_zones.id = dns_records.zone_id AND dns_zones.status = 'active'
  )
RETURNING id, zone_id, name, type, content, ttl, priority, synced_name, synced_type, status, created_at, updated_at
`

type QueueDNSRecordUpdateParams struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Content   string `json:"content"`
	Ttl       int64  `json:"ttl"`
	Priority  int64  `json:"priority"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDNSRecordUpdate(ctx context.Context, arg QueueDNSRecordUpdateParams) (DnsRecord, error) {
	row := q.db.QueryRowContext(ctx, queueDNSRecordUpdate,
		arg.Name,
		arg.Type,
		arg.Content,
		arg.Ttl,
		arg.Priority,
		arg.UpdatedAt,
		arg.ID,
	)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.Ttl,
		&i.Priority,
		&i.SyncedName,
		&i.SyncedType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueDNSZoneDelete = `-- name: QueueDNSZoneDelete :one
UPDATE dns_zones
SET status = 'deleting', updated_at = ?
WHERE dns_zones.id = ?
  AND dns_zones.status NOT IN ('pending', 'deleting')
  AND NOT EXISTS (
      SELECT 1 FROM dns_records
      WHERE dns_records.zone_id = dns_zones.id
        AND dns_records.status IN ('pending', 'deleting')
  )
RETURNING id, account_id, node_id, provider_id, name, primary_nameserver, secondary_nameserver, status, created_at, updated_at
`

type QueueDNSZoneDeleteParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDNSZoneDelete(ctx context.Context, arg QueueDNSZoneDeleteParams) (DnsZone, error) {
	row := q.db.QueryRowContext(ctx, queueDNSZoneDelete, arg.UpdatedAt, arg.ID)
	var i DnsZone
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.ProviderID,
		&i.Name,
		&i.PrimaryNameserver,
		&i.SecondaryNameserver,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDNSRecordStatus = `-- name: UpdateDNSRecordStatus :exec
UPDATE dns_records SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateDNSRecordStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDNSRecordStatus(ctx context.Context, arg UpdateDNSRecordStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDNSRecordStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateDNSSettings = `-- name: UpdateDNSSettings :one
UPDATE dns_settings
SET primary_nameserver = ?, secondary_nameserver = ?, default_ttl = ?, updated_at = ?
WHERE id = 1
RETURNING id, primary_nameserver, secondary_nameserver, default_ttl, updated_at
`

type UpdateDNSSettingsParams struct {
	PrimaryNameserver   string `json:"primary_nameserver"`
	SecondaryNameserver string `json:"secondary_nameserver"`
	DefaultTtl          int64  `json:"default_ttl"`
	UpdatedAt           int64  `json:"updated_at"`
}

func (q *Queries) UpdateDNSSettings(ctx context.Context, arg UpdateDNSSettingsParams) (DnsSetting, error) {
	row := q.db.QueryRowContext(ctx, updateDNSSettings,
		arg.PrimaryNameserver,
		arg.SecondaryNameserver,
		arg.DefaultTtl,
		arg.UpdatedAt,
	)
	var i DnsSetting
	err := row.Scan(
		&i.ID,
		&i.PrimaryNameserver,
		&i.SecondaryNameserver,
		&i.DefaultTtl,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDNSZoneStatus = `-- name: UpdateDNSZoneStatus :exec
UPDATE dns_zones SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateDNSZoneStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDNSZoneStatus(ctx context.Context, arg UpdateDNSZoneStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDNSZoneStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
