// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package dbgen

import (
	"context"
)

const completeDomainAliasRename = `-- name: CompleteDomainAliasRename :exec
UPDATE domain_aliases
SET previous_name = NULL,
    status = CASE WHEN enabled = 1 THEN 'active' ELSE 'disabled' END,
    updated_at = ?
WHERE id = ?
`

type CompleteDomainAliasRenameParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteDomainAliasRename(ctx context.Context, arg CompleteDomainAliasRenameParams) error {
	_, err := q.db.ExecContext(ctx, completeDomainAliasRename, arg.UpdatedAt, arg.ID)
	return err
}

const completeDomainRename = `-- name: CompleteDomainRename :exec
UPDATE domains
SET previous_name = NULL, status = 'active', updated_at = ?
WHERE id = ?
`

type CompleteDomainRenameParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteDomainRename(ctx context.Context, arg CompleteDomainRenameParams) error {
	_, err := q.db.ExecContext(ctx, completeDomainRename, arg.UpdatedAt, arg.ID)
	return err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (
    id,
    account_id,
    node_id,
    name,
    status,
    php_version,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, 'pending', ?, ?, ?)
RETURNING id, account_id, node_id, name, status, php_version, created_at, updated_at, enabled, previous_name
`

type CreateDomainParams struct {
	ID         string `json:"id"`
	AccountID  string `json:"account_id"`
	NodeID     string `json:"node_id"`
	Name       string `json:"name"`
	PhpVersion string `json:"php_version"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.PhpVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Status,
		&i.PhpVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PreviousName,
	)
	return i, err
}

const createDomainAlias = `-- name: CreateDomainAlias :one
INSERT INTO domain_aliases (
    id,
    domain_id,
    name,
    status,
    created_at,
    updated_at
) VALUES (?, ?, ?, 'pending', ?, ?)
RETURNING id, domain_id, name, status, created_at, updated_at, enabled, previous_name
`

type CreateDomainAliasParams struct {
	ID        string `json:"id"`
	DomainID  string `json:"domain_id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateDomainAlias(ctx context.Context, arg CreateDomainAliasParams) (DomainAlias, error) {
	row := q.db.QueryRowContext(ctx, createDomainAlias,
		arg.ID,
		arg.DomainID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DomainAlias
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PreviousName,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = ?
`

func (q *Queries) DeleteDomain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const deleteDomainAlias = `-- name: DeleteDomainAlias :exec
DELETE FROM domain_aliases WHERE id = ?
`

func (q *Queries) DeleteDomainAlias(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDomainAlias, id)
	return err
}

const domainNameExists = `-- name: DomainNameExists :one
SELECT EXISTS(
    SELECT 1
    FROM domains
    WHERE domains.name = ?1 COLLATE NOCASE
       OR domains.previous_name = ?1 COLLATE NOCASE
    UNION ALL
    SELECT 1
    FROM domain_aliases
    WHERE domain_aliases.name = ?1 COLLATE NOCASE
       OR domain_aliases.previous_name = ?1 COLLATE NOCASE
)
`

func (q *Queries) DomainNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, domainNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const failDomainAliasRename = `-- name: FailDomainAliasRename :exec
UPDATE domain_aliases
SET name = COALESCE(previous_name, name), previous_name = NULL,
    status = 'error', updated_at = ?
WHERE id = ?
`

type FailDomainAliasRenameParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) FailDomainAliasRename(ctx context.Context, arg FailDomainAliasRenameParams) error {
	_, err := q.db.ExecContext(ctx, failDomainAliasRename, arg.UpdatedAt, arg.ID)
	return err
}

const failDomainRename = `-- name: FailDomainRename :exec
UPDATE domains
SET name = COALESCE(previous_name, name), previous_name = NULL,
    status = 'error', updated_at = ?
WHERE id = ?
`

type FailDomainRenameParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) FailDomainRename(ctx context.Context, arg FailDomainRenameParams) error {
	_, err := q.db.ExecContext(ctx, failDomainRename, arg.UpdatedAt, arg.ID)
	return err
}

const getDomain = `-- name: GetDomain :one
SELECT id, account_id, node_id, name, status, php_version, created_at, updated_at, enabled, previous_name FROM domains WHERE id = ? LIMIT 1
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Status,
		&i.PhpVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PreviousName,
	)
	return i, err
}

const getDomainAlias = `-- name: GetDomainAlias :one
SELECT id, domain_id, name, status, created_at, updated_at, enabled, previous_name FROM domain_aliases WHERE id = ? LIMIT 1
`

func (q *Queries) GetDomainAlias(ctx context.Context, id string) (DomainAlias, error) {
	row := q.db.QueryRowContext(ctx, getDomainAlias, id)
	var i DomainAlias
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PreviousName,
	)
	return i, err
}

const listDomainAliases = `-- name: ListDomainAliases :many
SELECT id, domain_id, name, status, created_at, updated_at, enabled, previous_name
FROM domain_aliases
WHERE domain_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListDomainAliases(ctx context.Context, domainID string) ([]DomainAlias, error) {
	rows, err := q.db.QueryContext(ctx, listDomainAliases, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainAlias{}
	for rows.Next() {
		var i DomainAlias
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.PreviousName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, account_id, node_id, name, status, php_version, created_at, updated_at, enabled, previous_name FROM domains ORDER BY created_at ASC
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Status,
			&i.PhpVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.PreviousName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDomainAliases = `-- name: ListEnabledDomainAliases :many
SELECT id, domain_id, name, status, created_at, updated_at, enabled, previous_name
FROM domain_aliases
WHERE domain_id = ? AND enabled = 1
ORDER BY name ASC
`

func (q *Queries) ListEnabledDomainAliases(ctx context.Context, domainID string) ([]DomainAlias, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDomainAliases, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainAlias{}
	for rows.Next() {
		var i DomainAlias
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.PreviousName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDomains = `-- name: ListUserDomains :many
SELECT domains.id, domains.account_id, domains.node_id, domains.name, domains.status, domains.php_version, domains.created_at, domains.updated_at, domains.enabled, domains.previous_name
FROM domains
JOIN account_members ON account_members.account_id = domains.account_id
WHERE account_members.user_id = ?
ORDER BY domains.created_at ASC
`

func (q *Queries) ListUserDomains(ctx context.Context, userID string) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listUserDomains, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Status,
			&i.PhpVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.PreviousName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueDomainAction = `-- name: QueueDomainAction :one
UPDATE domains
SET enabled = ?, status = 'pending', updated_at = ?
WHERE id = ? AND status != 'pending'
RETURNING id, account_id, node_id, name, status, php_version, created_at, updated_at, enabled, previous_name
`

type QueueDomainActionParams struct {
	Enabled   int64  `json:"enabled"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDomainAction(ctx context.Context, arg QueueDomainActionParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, queueDomainAction, arg.Enabled, arg.UpdatedAt, arg.ID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Status,
		&i.PhpVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PreviousName,
	)
	return i, err
}

const queueDomainAliasAction = `-- name: QueueDomainAliasAction :one
UPDATE domain_aliases
SET enabled = ?, status = 'pending', updated_at = ?
WHERE id = ? AND status != 'pending'
RETURNING id, domain_id, name, status, created_at, updated_at, enabled, previous_name
`

type QueueDomainAliasActionParams struct {
	Enabled   int64  `json:"enabled"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDomainAliasAction(ctx context.Context, arg QueueDomainAliasActionParams) (DomainAlias, error) {
	row := q.db.QueryRowContext(ctx, queueDomainAliasAction, arg.Enabled, arg.UpdatedAt, arg.ID)
	var i DomainAlias
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PreviousName,
	)
	return i, err
}

const queueDomainAliasRename = `-- name: QueueDomainAliasRename :one
UPDATE domain_aliases
SET previous_name = name, name = ?, status = 'pending', updated_at = ?
WHERE id = ? AND status != 'pending'
RETURNING id, domain_id, name, status, created_at, updated_at, enabled, previous_name
`

type QueueDomainAliasRenameParams struct {
	Name      string `json:"name"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDomainAliasRename(ctx context.Context, arg QueueDomainAliasRenameParams) (DomainAlias, error) {
	row := q.db.QueryRowContext(ctx, queueDomainAliasRename, arg.Name, arg.UpdatedAt, arg.ID)
	var i DomainAlias
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PreviousName,
	)
	return i, err
}

const queueDomainRename = `-- name: QueueDomainRename :one
UPDATE domains
SET previous_name = name, name = ?, status = 'pending', updated_at = ?
WHERE id = ? AND status = 'active'
RETURNING id, account_id, node_id, name, status, php_version, created_at, updated_at, enabled, previous_name
`

type QueueDomainRenameParams struct {
	Name      string `json:"name"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueDomainRename(ctx context.Context, arg QueueDomainRenameParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, queueDomainRename, arg.Name, arg.UpdatedAt, arg.ID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Status,
		&i.PhpVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PreviousName,
	)
	return i, err
}

const updateDomainAliasStatus = `-- name: UpdateDomainAliasStatus :exec
UPDATE domain_aliases
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateDomainAliasStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDomainAliasStatus(ctx context.Context, arg UpdateDomainAliasStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDomainAliasStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateDomainStatus = `-- name: UpdateDomainStatus :exec
UPDATE domains
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateDomainStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDomainStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
