// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ftp.sql

package dbgen

import (
	"context"
)

const accountFTP = `-- name: AccountFTP :many
SELECT id, account_id, node_id, username, password_hash, enabled, deleting, status, created_at, updated_at, account_name, system_user, account_status FROM ftp_overviews WHERE account_id = ? ORDER BY created_at, id
`

func (q *Queries) AccountFTP(ctx context.Context, accountID string) ([]FtpOverview, error) {
	rows, err := q.db.QueryContext(ctx, accountFTP, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FtpOverview{}
	for rows.Next() {
		var i FtpOverview
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Username,
			&i.PasswordHash,
			&i.Enabled,
			&i.Deleting,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
			&i.SystemUser,
			&i.AccountStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFTP = `-- name: CountFTP :one
SELECT COUNT(*) FROM ftp_accounts
WHERE ?1 OR EXISTS (
    SELECT 1 FROM account_members
    WHERE account_members.account_id = ftp_accounts.account_id AND user_id = ?2
)
`

type CountFTPParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountFTP(ctx context.Context, arg CountFTPParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFTP, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFTP = `-- name: CreateFTP :exec
INSERT INTO ftp_accounts (id, account_id, node_id, username, password_hash, enabled, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, 'pending', ?, ?)
`

type CreateFTPParams struct {
	ID           string `json:"id"`
	AccountID    string `json:"account_id"`
	NodeID       string `json:"node_id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Enabled      int64  `json:"enabled"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) CreateFTP(ctx context.Context, arg CreateFTPParams) error {
	_, err := q.db.ExecContext(ctx, createFTP,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Username,
		arg.PasswordHash,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFTP = `-- name: DeleteFTP :exec
DELETE FROM ftp_accounts WHERE account_id = ? AND deleting = 1
`

func (q *Queries) DeleteFTP(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, deleteFTP, accountID)
	return err
}

const fTPBusy = `-- name: FTPBusy :one
SELECT EXISTS (
    SELECT 1 FROM jobs WHERE kind = 'ftp.sync' AND status IN ('queued', 'running')
    AND json_extract(payload, '$.accountId') = ?1
)
`

func (q *Queries) FTPBusy(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, fTPBusy, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const fTPNameExists = `-- name: FTPNameExists :one
SELECT EXISTS (
    SELECT 1 FROM ftp_accounts
    WHERE node_id = ? AND username = ? COLLATE NOCASE AND id != ?
)
`

type FTPNameExistsParams struct {
	NodeID   string `json:"node_id"`
	Username string `json:"username"`
	ID       string `json:"id"`
}

func (q *Queries) FTPNameExists(ctx context.Context, arg FTPNameExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, fTPNameExists, arg.NodeID, arg.Username, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFTP = `-- name: GetFTP :one
SELECT id, account_id, node_id, username, password_hash, enabled, deleting, status, created_at, updated_at, account_name, system_user, account_status FROM ftp_overviews WHERE id = ?
`

func (q *Queries) GetFTP(ctx context.Context, id string) (FtpOverview, error) {
	row := q.db.QueryRowContext(ctx, getFTP, id)
	var i FtpOverview
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Username,
		&i.PasswordHash,
		&i.Enabled,
		&i.Deleting,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountName,
		&i.SystemUser,
		&i.AccountStatus,
	)
	return i, err
}

const listFTPPage = `-- name: ListFTPPage :many
SELECT id, account_id, node_id, username, password_hash, enabled, deleting, status, created_at, updated_at, account_name, system_user, account_status FROM ftp_overviews
WHERE ?1 OR EXISTS (
    SELECT 1 FROM account_members
    WHERE account_members.account_id = ftp_overviews.account_id AND user_id = ?2
)
ORDER BY created_at, id
LIMIT ?4 OFFSET ?3
`

type ListFTPPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListFTPPage(ctx context.Context, arg ListFTPPageParams) ([]FtpOverview, error) {
	rows, err := q.db.QueryContext(ctx, listFTPPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FtpOverview{}
	for rows.Next() {
		var i FtpOverview
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Username,
			&i.PasswordHash,
			&i.Enabled,
			&i.Deleting,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
			&i.SystemUser,
			&i.AccountStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFTPStatuses = `-- name: SetFTPStatuses :exec
UPDATE ftp_accounts SET status = CASE
    WHEN CAST(?1 AS INTEGER) = 1 THEN 'error'
    WHEN enabled = 1 THEN 'active' ELSE 'disabled' END, updated_at = ?2
WHERE account_id = ?3
`

type SetFTPStatusesParams struct {
	Failed    int64  `json:"failed"`
	UpdatedAt int64  `json:"updated_at"`
	AccountID string `json:"account_id"`
}

func (q *Queries) SetFTPStatuses(ctx context.Context, arg SetFTPStatusesParams) error {
	_, err := q.db.ExecContext(ctx, setFTPStatuses, arg.Failed, arg.UpdatedAt, arg.AccountID)
	return err
}

const updateFTP = `-- name: UpdateFTP :exec
UPDATE ftp_accounts SET username = ?, password_hash = ?, enabled = ?, deleting = ?,
    status = 'pending', updated_at = ? WHERE id = ?
`

type UpdateFTPParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Enabled      int64  `json:"enabled"`
	Deleting     int64  `json:"deleting"`
	UpdatedAt    int64  `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateFTP(ctx context.Context, arg UpdateFTPParams) error {
	_, err := q.db.ExecContext(ctx, updateFTP,
		arg.Username,
		arg.PasswordHash,
		arg.Enabled,
		arg.Deleting,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
