// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
	"database/sql"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running', attempts = attempts + 1, started_at = ?, error = NULL
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'queued' AND attempts < max_attempts
    ORDER BY created_at ASC
    LIMIT 1
)
RETURNING id, node_id, user_id, kind, status, payload, attempts, max_attempts, error, created_at, started_at, finished_at
`

func (q *Queries) ClaimJob(ctx context.Context, startedAt sql.NullInt64) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, startedAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET status = 'succeeded', finished_at = ?, error = NULL,
    payload = json_remove(payload, '$.password')
WHERE id = ? AND status = 'running'
`

type CompleteJobParams struct {
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.FinishedAt, arg.ID)
	return err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id,
    node_id,
    user_id,
    kind,
    status,
    payload,
    attempts,
    max_attempts,
    created_at
) VALUES (?, ?, ?, ?, 'queued', ?, 0, ?, ?)
RETURNING id, node_id, user_id, kind, status, payload, attempts, max_attempts, error, created_at, started_at, finished_at
`

type CreateJobParams struct {
	ID          string         `json:"id"`
	NodeID      sql.NullString `json:"node_id"`
	UserID      sql.NullString `json:"user_id"`
	Kind        string         `json:"kind"`
	Payload     string         `json:"payload"`
	MaxAttempts int64          `json:"max_attempts"`
	CreatedAt   int64          `json:"created_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.NodeID,
		arg.UserID,
		arg.Kind,
		arg.Payload,
		arg.MaxAttempts,
		arg.CreatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createJobStep = `-- name: CreateJobStep :one
INSERT INTO job_steps (
    id,
    job_id,
    name,
    status,
    message,
    started_at
) VALUES (?, ?, ?, 'running', '', ?)
RETURNING id, job_id, name, status, message, started_at, finished_at
`

type CreateJobStepParams struct {
	ID        string `json:"id"`
	JobID     string `json:"job_id"`
	Name      string `json:"name"`
	StartedAt int64  `json:"started_at"`
}

func (q *Queries) CreateJobStep(ctx context.Context, arg CreateJobStepParams) (JobStep, error) {
	row := q.db.QueryRowContext(ctx, createJobStep,
		arg.ID,
		arg.JobID,
		arg.Name,
		arg.StartedAt,
	)
	var i JobStep
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET status = 'failed', finished_at = ?, error = ?,
    payload = json_remove(payload, '$.password')
WHERE id = ? AND status = 'running'
`

type FailJobParams struct {
	FinishedAt sql.NullInt64  `json:"finished_at"`
	Error      sql.NullString `json:"error"`
	ID         string         `json:"id"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.ExecContext(ctx, failJob, arg.FinishedAt, arg.Error, arg.ID)
	return err
}

const finishJobStep = `-- name: FinishJobStep :exec
UPDATE job_steps
SET status = ?, message = ?, finished_at = ?
WHERE id = ?
`

type FinishJobStepParams struct {
	Status     string        `json:"status"`
	Message    string        `json:"message"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) FinishJobStep(ctx context.Context, arg FinishJobStepParams) error {
	_, err := q.db.ExecContext(ctx, finishJobStep,
		arg.Status,
		arg.Message,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, node_id, user_id, kind, status, payload, attempts, max_attempts, error, created_at, started_at, finished_at FROM jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobSteps = `-- name: ListJobSteps :many
SELECT id, job_id, name, status, message, started_at, finished_at FROM job_steps WHERE job_id = ? ORDER BY started_at ASC
`

func (q *Queries) ListJobSteps(ctx context.Context, jobID string) ([]JobStep, error) {
	rows, err := q.db.QueryContext(ctx, listJobSteps, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobStep{}
	for rows.Next() {
		var i JobStep
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Status,
			&i.Message,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, node_id, user_id, kind, status, payload, attempts, max_attempts, error, created_at, started_at, finished_at FROM jobs
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListJobs(ctx context.Context, limit int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverJobs = `-- name: RecoverJobs :execrows
UPDATE jobs
SET status = 'queued',
    attempts = CASE WHEN attempts > 0 THEN attempts - 1 ELSE 0 END,
    started_at = NULL,
    error = NULL
WHERE status = 'running'
`

func (q *Queries) RecoverJobs(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs
SET status = 'queued', started_at = NULL, finished_at = NULL, error = ?
WHERE id = ? AND status = 'running' AND attempts < max_attempts
`

type RetryJobParams struct {
	Error sql.NullString `json:"error"`
	ID    string         `json:"id"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.ExecContext(ctx, retryJob, arg.Error, arg.ID)
	return err
}
