// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Account struct {
	ID         string         `json:"id"`
	NodeID     sql.NullString `json:"node_id"`
	Name       string         `json:"name"`
	SystemUser string         `json:"system_user"`
	Status     string         `json:"status"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	Enabled    int64          `json:"enabled"`
}

type AccountMember struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	CreatedAt int64  `json:"created_at"`
}

type AuditEvent struct {
	ID           string         `json:"id"`
	UserID       sql.NullString `json:"user_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
	Result       string         `json:"result"`
	Metadata     string         `json:"metadata"`
	CreatedAt    int64          `json:"created_at"`
}

type BackupArtifact struct {
	ID        string `json:"id"`
	RunID     string `json:"run_id"`
	AccountID string `json:"account_id"`
	NodeID    string `json:"node_id"`
	Path      string `json:"path"`
	Checksum  string `json:"checksum"`
	SizeBytes int64  `json:"size_bytes"`
	Manifest  string `json:"manifest"`
	CreatedAt int64  `json:"created_at"`
}

type BackupPlan struct {
	ID               string        `json:"id"`
	AccountID        string        `json:"account_id"`
	NodeID           string        `json:"node_id"`
	Name             string        `json:"name"`
	Schedule         string        `json:"schedule"`
	RetentionCount   int64         `json:"retention_count"`
	IncludeFiles     int64         `json:"include_files"`
	IncludeDatabases int64         `json:"include_databases"`
	Enabled          int64         `json:"enabled"`
	LastRunAt        sql.NullInt64 `json:"last_run_at"`
	NextRunAt        sql.NullInt64 `json:"next_run_at"`
	CreatedAt        int64         `json:"created_at"`
	UpdatedAt        int64         `json:"updated_at"`
}

type BackupRun struct {
	ID         string         `json:"id"`
	PlanID     sql.NullString `json:"plan_id"`
	AccountID  string         `json:"account_id"`
	NodeID     string         `json:"node_id"`
	Status     string         `json:"status"`
	Error      string         `json:"error"`
	CreatedAt  int64          `json:"created_at"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type Certificate struct {
	ID            string         `json:"id"`
	DomainID      sql.NullString `json:"domain_id"`
	NodeID        string         `json:"node_id"`
	Kind          string         `json:"kind"`
	Name          string         `json:"name"`
	Email         string         `json:"email"`
	Status        string         `json:"status"`
	RedirectHttps int64          `json:"redirect_https"`
	ExpiresAt     sql.NullInt64  `json:"expires_at"`
	RenewAfter    sql.NullInt64  `json:"renew_after"`
	Error         string         `json:"error"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type CertificateName struct {
	CertificateID string `json:"certificate_id"`
	Name          string `json:"name"`
}

type CronJob struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	NodeID    string `json:"node_id"`
	Name      string `json:"name"`
	Schedule  string `json:"schedule"`
	Command   string `json:"command"`
	Enabled   int64  `json:"enabled"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Database struct {
	ID         string `json:"id"`
	AccountID  string `json:"account_id"`
	NodeID     string `json:"node_id"`
	Name       string `json:"name"`
	SystemName string `json:"system_name"`
	Status     string `json:"status"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type DatabaseGrant struct {
	DatabaseID     string `json:"database_id"`
	DatabaseUserID string `json:"database_user_id"`
	Status         string `json:"status"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type DatabaseUser struct {
	ID         string `json:"id"`
	AccountID  string `json:"account_id"`
	NodeID     string `json:"node_id"`
	Name       string `json:"name"`
	SystemName string `json:"system_name"`
	Status     string `json:"status"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type Domain struct {
	ID           string         `json:"id"`
	AccountID    string         `json:"account_id"`
	NodeID       string         `json:"node_id"`
	Name         string         `json:"name"`
	Status       string         `json:"status"`
	PhpVersion   string         `json:"php_version"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	Enabled      int64          `json:"enabled"`
	PreviousName sql.NullString `json:"previous_name"`
}

type DomainAlias struct {
	ID           string         `json:"id"`
	DomainID     string         `json:"domain_id"`
	Name         string         `json:"name"`
	Status       string         `json:"status"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	Enabled      int64          `json:"enabled"`
	PreviousName sql.NullString `json:"previous_name"`
}

type Job struct {
	ID          string         `json:"id"`
	NodeID      sql.NullString `json:"node_id"`
	UserID      sql.NullString `json:"user_id"`
	Kind        string         `json:"kind"`
	Status      string         `json:"status"`
	Payload     string         `json:"payload"`
	Attempts    int64          `json:"attempts"`
	MaxAttempts int64          `json:"max_attempts"`
	Error       sql.NullString `json:"error"`
	CreatedAt   int64          `json:"created_at"`
	StartedAt   sql.NullInt64  `json:"started_at"`
	FinishedAt  sql.NullInt64  `json:"finished_at"`
}

type JobStep struct {
	ID         string        `json:"id"`
	JobID      string        `json:"job_id"`
	Name       string        `json:"name"`
	Status     string        `json:"status"`
	Message    string        `json:"message"`
	StartedAt  int64         `json:"started_at"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
}

type Node struct {
	ID         string        `json:"id"`
	Name       string        `json:"name"`
	Kind       string        `json:"kind"`
	Endpoint   string        `json:"endpoint"`
	Status     string        `json:"status"`
	LastSeenAt sql.NullInt64 `json:"last_seen_at"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	CsrfToken string `json:"csrf_token"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type User struct {
	ID                 string `json:"id"`
	Email              string `json:"email"`
	Name               string `json:"name"`
	PasswordHash       string `json:"password_hash"`
	Role               string `json:"role"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
	Username           string `json:"username"`
	MustChangePassword int64  `json:"must_change_password"`
	Timezone           string `json:"timezone"`
}
