// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Account struct {
	ID         string         `json:"id"`
	NodeID     sql.NullString `json:"node_id"`
	Name       string         `json:"name"`
	SystemUser string         `json:"system_user"`
	Status     string         `json:"status"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	Enabled    int64          `json:"enabled"`
}

type AccountMember struct {
	AccountID string `json:"account_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	CreatedAt int64  `json:"created_at"`
}

type AccountOverview struct {
	ID                  string         `json:"id"`
	NodeID              sql.NullString `json:"node_id"`
	Name                string         `json:"name"`
	SystemUser          string         `json:"system_user"`
	Status              string         `json:"status"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
	Enabled             int64          `json:"enabled"`
	PackageID           string         `json:"package_id"`
	PackageName         string         `json:"package_name"`
	PackageCreatedAt    int64          `json:"package_created_at"`
	PackageUpdatedAt    int64          `json:"package_updated_at"`
	PackageAccountCount int64          `json:"package_account_count"`
	MaxWebsites         int64          `json:"max_websites"`
	MaxDomains          int64          `json:"max_domains"`
	MaxAliases          int64          `json:"max_aliases"`
	MaxDatabases        int64          `json:"max_databases"`
	MaxDatabaseUsers    int64          `json:"max_database_users"`
	MaxScheduledTasks   int64          `json:"max_scheduled_tasks"`
	MaxBackupPlans      int64          `json:"max_backup_plans"`
	MaxBackupRetention  int64          `json:"max_backup_retention"`
	MaxFtpAccounts      int64          `json:"max_ftp_accounts"`
	UsedWebsites        int64          `json:"used_websites"`
	UsedDomains         int64          `json:"used_domains"`
	UsedAliases         int64          `json:"used_aliases"`
	UsedDatabases       int64          `json:"used_databases"`
	UsedDatabaseUsers   int64          `json:"used_database_users"`
	UsedScheduledTasks  int64          `json:"used_scheduled_tasks"`
	UsedBackupPlans     int64          `json:"used_backup_plans"`
	UsedFtpAccounts     int64          `json:"used_ftp_accounts"`
}

type AccountPackage struct {
	AccountID string `json:"account_id"`
	PackageID string `json:"package_id"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type AuditEvent struct {
	ID           string         `json:"id"`
	UserID       sql.NullString `json:"user_id"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
	Result       string         `json:"result"`
	Metadata     string         `json:"metadata"`
	CreatedAt    int64          `json:"created_at"`
	JobID        sql.NullString `json:"job_id"`
}

type BackupArtifact struct {
	ID            string `json:"id"`
	RunID         string `json:"run_id"`
	AccountID     string `json:"account_id"`
	NodeID        string `json:"node_id"`
	Path          string `json:"path"`
	Checksum      string `json:"checksum"`
	SizeBytes     int64  `json:"size_bytes"`
	Manifest      string `json:"manifest"`
	CreatedAt     int64  `json:"created_at"`
	StorageDriver string `json:"storage_driver"`
}

type BackupPlan struct {
	ID               string        `json:"id"`
	AccountID        string        `json:"account_id"`
	NodeID           string        `json:"node_id"`
	Name             string        `json:"name"`
	Schedule         string        `json:"schedule"`
	RetentionCount   int64         `json:"retention_count"`
	IncludeFiles     int64         `json:"include_files"`
	IncludeDatabases int64         `json:"include_databases"`
	Enabled          int64         `json:"enabled"`
	LastRunAt        sql.NullInt64 `json:"last_run_at"`
	NextRunAt        sql.NullInt64 `json:"next_run_at"`
	CreatedAt        int64         `json:"created_at"`
	UpdatedAt        int64         `json:"updated_at"`
	StorageDriver    string        `json:"storage_driver"`
}

type BackupRun struct {
	ID            string         `json:"id"`
	PlanID        sql.NullString `json:"plan_id"`
	AccountID     string         `json:"account_id"`
	NodeID        string         `json:"node_id"`
	Status        string         `json:"status"`
	Error         string         `json:"error"`
	CreatedAt     int64          `json:"created_at"`
	StartedAt     sql.NullInt64  `json:"started_at"`
	FinishedAt    sql.NullInt64  `json:"finished_at"`
	StorageDriver string         `json:"storage_driver"`
}

type Certificate struct {
	ID            string         `json:"id"`
	WebsiteID     sql.NullString `json:"website_id"`
	NodeID        string         `json:"node_id"`
	Kind          string         `json:"kind"`
	Name          string         `json:"name"`
	Email         string         `json:"email"`
	Status        string         `json:"status"`
	RedirectHttps int64          `json:"redirect_https"`
	ExpiresAt     sql.NullInt64  `json:"expires_at"`
	RenewAfter    sql.NullInt64  `json:"renew_after"`
	Error         string         `json:"error"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type CertificateName struct {
	CertificateID string `json:"certificate_id"`
	Name          string `json:"name"`
}

type Database struct {
	ID         string `json:"id"`
	AccountID  string `json:"account_id"`
	NodeID     string `json:"node_id"`
	Name       string `json:"name"`
	SystemName string `json:"system_name"`
	Status     string `json:"status"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
	Driver     string `json:"driver"`
}

type DatabaseGrant struct {
	DatabaseID     string `json:"database_id"`
	DatabaseUserID string `json:"database_user_id"`
	Status         string `json:"status"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type DatabaseUser struct {
	ID         string `json:"id"`
	AccountID  string `json:"account_id"`
	NodeID     string `json:"node_id"`
	Name       string `json:"name"`
	SystemName string `json:"system_name"`
	Status     string `json:"status"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
	Driver     string `json:"driver"`
}

type DnsProvider struct {
	ID        string `json:"id"`
	NodeID    string `json:"node_id"`
	Name      string `json:"name"`
	Driver    string `json:"driver"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type DnsRecord struct {
	ID         string `json:"id"`
	ZoneID     string `json:"zone_id"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	Content    string `json:"content"`
	Ttl        int64  `json:"ttl"`
	Priority   int64  `json:"priority"`
	SyncedName string `json:"synced_name"`
	SyncedType string `json:"synced_type"`
	Status     string `json:"status"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type DnsSetting struct {
	ID                  int64  `json:"id"`
	PrimaryNameserver   string `json:"primary_nameserver"`
	SecondaryNameserver string `json:"secondary_nameserver"`
	DefaultTtl          int64  `json:"default_ttl"`
	UpdatedAt           int64  `json:"updated_at"`
}

type DnsZone struct {
	ID                  string `json:"id"`
	AccountID           string `json:"account_id"`
	NodeID              string `json:"node_id"`
	ProviderID          string `json:"provider_id"`
	Name                string `json:"name"`
	PrimaryNameserver   string `json:"primary_nameserver"`
	SecondaryNameserver string `json:"secondary_nameserver"`
	Status              string `json:"status"`
	CreatedAt           int64  `json:"created_at"`
	UpdatedAt           int64  `json:"updated_at"`
}

type FtpAccount struct {
	ID           string `json:"id"`
	AccountID    string `json:"account_id"`
	NodeID       string `json:"node_id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Enabled      int64  `json:"enabled"`
	Deleting     int64  `json:"deleting"`
	Status       string `json:"status"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type FtpOverview struct {
	ID            string `json:"id"`
	AccountID     string `json:"account_id"`
	NodeID        string `json:"node_id"`
	Username      string `json:"username"`
	PasswordHash  string `json:"password_hash"`
	Enabled       int64  `json:"enabled"`
	Deleting      int64  `json:"deleting"`
	Status        string `json:"status"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
	AccountName   string `json:"account_name"`
	SystemUser    string `json:"system_user"`
	AccountStatus string `json:"account_status"`
}

type Job struct {
	ID          string         `json:"id"`
	NodeID      sql.NullString `json:"node_id"`
	UserID      sql.NullString `json:"user_id"`
	Kind        string         `json:"kind"`
	Status      string         `json:"status"`
	Payload     string         `json:"payload"`
	Attempts    int64          `json:"attempts"`
	MaxAttempts int64          `json:"max_attempts"`
	Error       sql.NullString `json:"error"`
	CreatedAt   int64          `json:"created_at"`
	StartedAt   sql.NullInt64  `json:"started_at"`
	FinishedAt  sql.NullInt64  `json:"finished_at"`
}

type JobStep struct {
	ID         string        `json:"id"`
	JobID      string        `json:"job_id"`
	Name       string        `json:"name"`
	Status     string        `json:"status"`
	Message    string        `json:"message"`
	StartedAt  int64         `json:"started_at"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
}

type Node struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Kind           string         `json:"kind"`
	Endpoint       string         `json:"endpoint"`
	Status         string         `json:"status"`
	LastSeenAt     sql.NullInt64  `json:"last_seen_at"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	Capabilities   sql.NullString `json:"capabilities"`
	CapabilitiesAt sql.NullInt64  `json:"capabilities_at"`
}

type Package struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	MaxWebsites        int64  `json:"max_websites"`
	MaxDomains         int64  `json:"max_domains"`
	MaxAliases         int64  `json:"max_aliases"`
	MaxDatabases       int64  `json:"max_databases"`
	MaxDatabaseUsers   int64  `json:"max_database_users"`
	MaxScheduledTasks  int64  `json:"max_scheduled_tasks"`
	MaxBackupPlans     int64  `json:"max_backup_plans"`
	MaxBackupRetention int64  `json:"max_backup_retention"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
	MaxFtpAccounts     int64  `json:"max_ftp_accounts"`
}

type PackageOverview struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	MaxWebsites        int64  `json:"max_websites"`
	MaxDomains         int64  `json:"max_domains"`
	MaxAliases         int64  `json:"max_aliases"`
	MaxDatabases       int64  `json:"max_databases"`
	MaxDatabaseUsers   int64  `json:"max_database_users"`
	MaxScheduledTasks  int64  `json:"max_scheduled_tasks"`
	MaxBackupPlans     int64  `json:"max_backup_plans"`
	MaxBackupRetention int64  `json:"max_backup_retention"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
	MaxFtpAccounts     int64  `json:"max_ftp_accounts"`
	AccountCount       int64  `json:"account_count"`
}

type ScheduledTask struct {
	ID              string `json:"id"`
	AccountID       string `json:"account_id"`
	NodeID          string `json:"node_id"`
	Name            string `json:"name"`
	Schedule        string `json:"schedule"`
	Command         string `json:"command"`
	Enabled         int64  `json:"enabled"`
	Status          string `json:"status"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
	SchedulerDriver string `json:"scheduler_driver"`
	Kind            string `json:"kind"`
}

type ServiceSetting struct {
	ID              int64  `json:"id"`
	WebDriver       string `json:"web_driver"`
	RuntimeDriver   string `json:"runtime_driver"`
	RuntimeVersion  string `json:"runtime_version"`
	DatabaseDriver  string `json:"database_driver"`
	SchedulerDriver string `json:"scheduler_driver"`
	BackupDriver    string `json:"backup_driver"`
	UpdatedAt       int64  `json:"updated_at"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	CsrfToken string `json:"csrf_token"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type User struct {
	ID                 string `json:"id"`
	Email              string `json:"email"`
	Name               string `json:"name"`
	PasswordHash       string `json:"password_hash"`
	Role               string `json:"role"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
	Username           string `json:"username"`
	MustChangePassword int64  `json:"must_change_password"`
	Timezone           string `json:"timezone"`
}

type Website struct {
	ID             string `json:"id"`
	AccountID      string `json:"account_id"`
	NodeID         string `json:"node_id"`
	Name           string `json:"name"`
	Kind           string `json:"kind"`
	DocumentRoot   string `json:"document_root"`
	WebDriver      string `json:"web_driver"`
	RuntimeDriver  string `json:"runtime_driver"`
	RuntimeVersion string `json:"runtime_version"`
	Status         string `json:"status"`
	Enabled        int64  `json:"enabled"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

type WebsiteDomain struct {
	ID               string         `json:"id"`
	WebsiteID        string         `json:"website_id"`
	Hostname         string         `json:"hostname"`
	Kind             string         `json:"kind"`
	Status           string         `json:"status"`
	Enabled          int64          `json:"enabled"`
	PreviousHostname sql.NullString `json:"previous_hostname"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}
