// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (
    id,
    name,
    kind,
    endpoint,
    status,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, kind, endpoint, status, last_seen_at, created_at, updated_at, capabilities, capabilities_at
`

type CreateNodeParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Kind      string `json:"kind"`
	Endpoint  string `json:"endpoint"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Endpoint,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesAt,
	)
	return i, err
}

const getLocalNode = `-- name: GetLocalNode :one
SELECT id, name, kind, endpoint, status, last_seen_at, created_at, updated_at, capabilities, capabilities_at FROM nodes WHERE kind = 'local' LIMIT 1
`

func (q *Queries) GetLocalNode(ctx context.Context) (Node, error) {
	row := q.db.QueryRowContext(ctx, getLocalNode)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, name, kind, endpoint, status, last_seen_at, created_at, updated_at, capabilities, capabilities_at FROM nodes WHERE id = ? LIMIT 1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, kind, endpoint, status, last_seen_at, created_at, updated_at, capabilities, capabilities_at FROM nodes ORDER BY created_at ASC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Endpoint,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Capabilities,
			&i.CapabilitiesAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocalNode = `-- name: UpdateLocalNode :one
UPDATE nodes
SET name = ?, endpoint = ?, updated_at = ?
WHERE kind = 'local'
RETURNING id, name, kind, endpoint, status, last_seen_at, created_at, updated_at, capabilities, capabilities_at
`

type UpdateLocalNodeParams struct {
	Name      string `json:"name"`
	Endpoint  string `json:"endpoint"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpdateLocalNode(ctx context.Context, arg UpdateLocalNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateLocalNode, arg.Name, arg.Endpoint, arg.UpdatedAt)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Endpoint,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesAt,
	)
	return i, err
}

const updateNodeProbe = `-- name: UpdateNodeProbe :exec
UPDATE nodes
SET status = ?1,
    last_seen_at = COALESCE(?2, last_seen_at),
    capabilities = COALESCE(?3, capabilities),
    capabilities_at = COALESCE(?4, capabilities_at),
    updated_at = ?5
WHERE id = ?6
`

type UpdateNodeProbeParams struct {
	Status         string         `json:"status"`
	LastSeenAt     sql.NullInt64  `json:"last_seen_at"`
	Capabilities   sql.NullString `json:"capabilities"`
	CapabilitiesAt sql.NullInt64  `json:"capabilities_at"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateNodeProbe(ctx context.Context, arg UpdateNodeProbeParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeProbe,
		arg.Status,
		arg.LastSeenAt,
		arg.Capabilities,
		arg.CapabilitiesAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
