// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package dbgen

import (
	"context"
)

const assignAccountPackage = `-- name: AssignAccountPackage :exec
INSERT INTO account_packages (account_id, package_id, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(account_id) DO UPDATE SET
    package_id = excluded.package_id,
    updated_at = excluded.updated_at
`

type AssignAccountPackageParams struct {
	AccountID string `json:"account_id"`
	PackageID string `json:"package_id"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) AssignAccountPackage(ctx context.Context, arg AssignAccountPackageParams) error {
	_, err := q.db.ExecContext(ctx, assignAccountPackage,
		arg.AccountID,
		arg.PackageID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const countPackages = `-- name: CountPackages :one
SELECT COUNT(*) FROM packages
`

func (q *Queries) CountPackages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPackages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (
    id, name, max_websites, max_domains, max_aliases, max_databases,
    max_database_users, max_scheduled_tasks, max_backup_plans,
    max_backup_retention, max_ftp_accounts, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, max_websites, max_domains, max_aliases, max_databases, max_database_users, max_scheduled_tasks, max_backup_plans, max_backup_retention, created_at, updated_at, max_ftp_accounts
`

type CreatePackageParams struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	MaxWebsites        int64  `json:"max_websites"`
	MaxDomains         int64  `json:"max_domains"`
	MaxAliases         int64  `json:"max_aliases"`
	MaxDatabases       int64  `json:"max_databases"`
	MaxDatabaseUsers   int64  `json:"max_database_users"`
	MaxScheduledTasks  int64  `json:"max_scheduled_tasks"`
	MaxBackupPlans     int64  `json:"max_backup_plans"`
	MaxBackupRetention int64  `json:"max_backup_retention"`
	MaxFtpAccounts     int64  `json:"max_ftp_accounts"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, createPackage,
		arg.ID,
		arg.Name,
		arg.MaxWebsites,
		arg.MaxDomains,
		arg.MaxAliases,
		arg.MaxDatabases,
		arg.MaxDatabaseUsers,
		arg.MaxScheduledTasks,
		arg.MaxBackupPlans,
		arg.MaxBackupRetention,
		arg.MaxFtpAccounts,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxWebsites,
		&i.MaxDomains,
		&i.MaxAliases,
		&i.MaxDatabases,
		&i.MaxDatabaseUsers,
		&i.MaxScheduledTasks,
		&i.MaxBackupPlans,
		&i.MaxBackupRetention,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxFtpAccounts,
	)
	return i, err
}

const deletePackage = `-- name: DeletePackage :execrows
DELETE FROM packages
WHERE id = ?
  AND NOT EXISTS (
      SELECT 1 FROM account_packages WHERE account_packages.package_id = packages.id
  )
`

func (q *Queries) DeletePackage(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePackage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccountOverview = `-- name: GetAccountOverview :one
SELECT id, node_id, name, system_user, status, created_at, updated_at, enabled, package_id, package_name, package_created_at, package_updated_at, package_account_count, max_websites, max_domains, max_aliases, max_databases, max_database_users, max_scheduled_tasks, max_backup_plans, max_backup_retention, max_ftp_accounts, used_websites, used_domains, used_aliases, used_databases, used_database_users, used_scheduled_tasks, used_backup_plans, used_ftp_accounts FROM account_overviews WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccountOverview(ctx context.Context, id string) (AccountOverview, error) {
	row := q.db.QueryRowContext(ctx, getAccountOverview, id)
	var i AccountOverview
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.SystemUser,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.PackageID,
		&i.PackageName,
		&i.PackageCreatedAt,
		&i.PackageUpdatedAt,
		&i.PackageAccountCount,
		&i.MaxWebsites,
		&i.MaxDomains,
		&i.MaxAliases,
		&i.MaxDatabases,
		&i.MaxDatabaseUsers,
		&i.MaxScheduledTasks,
		&i.MaxBackupPlans,
		&i.MaxBackupRetention,
		&i.MaxFtpAccounts,
		&i.UsedWebsites,
		&i.UsedDomains,
		&i.UsedAliases,
		&i.UsedDatabases,
		&i.UsedDatabaseUsers,
		&i.UsedScheduledTasks,
		&i.UsedBackupPlans,
		&i.UsedFtpAccounts,
	)
	return i, err
}

const getPackageOverview = `-- name: GetPackageOverview :one
SELECT id, name, max_websites, max_domains, max_aliases, max_databases, max_database_users, max_scheduled_tasks, max_backup_plans, max_backup_retention, created_at, updated_at, max_ftp_accounts, account_count FROM package_overviews WHERE id = ? LIMIT 1
`

func (q *Queries) GetPackageOverview(ctx context.Context, id string) (PackageOverview, error) {
	row := q.db.QueryRowContext(ctx, getPackageOverview, id)
	var i PackageOverview
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxWebsites,
		&i.MaxDomains,
		&i.MaxAliases,
		&i.MaxDatabases,
		&i.MaxDatabaseUsers,
		&i.MaxScheduledTasks,
		&i.MaxBackupPlans,
		&i.MaxBackupRetention,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxFtpAccounts,
		&i.AccountCount,
	)
	return i, err
}

const listAccountOverviewsPage = `-- name: ListAccountOverviewsPage :many
SELECT id, node_id, name, system_user, status, created_at, updated_at, enabled, package_id, package_name, package_created_at, package_updated_at, package_account_count, max_websites, max_domains, max_aliases, max_databases, max_database_users, max_scheduled_tasks, max_backup_plans, max_backup_retention, max_ftp_accounts, used_websites, used_domains, used_aliases, used_databases, used_database_users, used_scheduled_tasks, used_backup_plans, used_ftp_accounts FROM account_overviews
ORDER BY created_at ASC
LIMIT ?2 OFFSET ?1
`

type ListAccountOverviewsPageParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

func (q *Queries) ListAccountOverviewsPage(ctx context.Context, arg ListAccountOverviewsPageParams) ([]AccountOverview, error) {
	rows, err := q.db.QueryContext(ctx, listAccountOverviewsPage, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountOverview{}
	for rows.Next() {
		var i AccountOverview
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.SystemUser,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.PackageID,
			&i.PackageName,
			&i.PackageCreatedAt,
			&i.PackageUpdatedAt,
			&i.PackageAccountCount,
			&i.MaxWebsites,
			&i.MaxDomains,
			&i.MaxAliases,
			&i.MaxDatabases,
			&i.MaxDatabaseUsers,
			&i.MaxScheduledTasks,
			&i.MaxBackupPlans,
			&i.MaxBackupRetention,
			&i.MaxFtpAccounts,
			&i.UsedWebsites,
			&i.UsedDomains,
			&i.UsedAliases,
			&i.UsedDatabases,
			&i.UsedDatabaseUsers,
			&i.UsedScheduledTasks,
			&i.UsedBackupPlans,
			&i.UsedFtpAccounts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageOverviewsPage = `-- name: ListPackageOverviewsPage :many
SELECT id, name, max_websites, max_domains, max_aliases, max_databases, max_database_users, max_scheduled_tasks, max_backup_plans, max_backup_retention, created_at, updated_at, max_ftp_accounts, account_count FROM package_overviews
ORDER BY name COLLATE NOCASE ASC
LIMIT ?2 OFFSET ?1
`

type ListPackageOverviewsPageParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

func (q *Queries) ListPackageOverviewsPage(ctx context.Context, arg ListPackageOverviewsPageParams) ([]PackageOverview, error) {
	rows, err := q.db.QueryContext(ctx, listPackageOverviewsPage, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageOverview{}
	for rows.Next() {
		var i PackageOverview
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MaxWebsites,
			&i.MaxDomains,
			&i.MaxAliases,
			&i.MaxDatabases,
			&i.MaxDatabaseUsers,
			&i.MaxScheduledTasks,
			&i.MaxBackupPlans,
			&i.MaxBackupRetention,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxFtpAccounts,
			&i.AccountCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccountOverviewsPage = `-- name: ListUserAccountOverviewsPage :many
SELECT account_overviews.id, account_overviews.node_id, account_overviews.name, account_overviews.system_user, account_overviews.status, account_overviews.created_at, account_overviews.updated_at, account_overviews.enabled, account_overviews.package_id, account_overviews.package_name, account_overviews.package_created_at, account_overviews.package_updated_at, account_overviews.package_account_count, account_overviews.max_websites, account_overviews.max_domains, account_overviews.max_aliases, account_overviews.max_databases, account_overviews.max_database_users, account_overviews.max_scheduled_tasks, account_overviews.max_backup_plans, account_overviews.max_backup_retention, account_overviews.max_ftp_accounts, account_overviews.used_websites, account_overviews.used_domains, account_overviews.used_aliases, account_overviews.used_databases, account_overviews.used_database_users, account_overviews.used_scheduled_tasks, account_overviews.used_backup_plans, account_overviews.used_ftp_accounts
FROM account_overviews
JOIN account_members ON account_members.account_id = account_overviews.id
WHERE account_members.user_id = ?1
ORDER BY account_overviews.created_at ASC
LIMIT ?3 OFFSET ?2
`

type ListUserAccountOverviewsPageParams struct {
	UserID     string `json:"user_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) ListUserAccountOverviewsPage(ctx context.Context, arg ListUserAccountOverviewsPageParams) ([]AccountOverview, error) {
	rows, err := q.db.QueryContext(ctx, listUserAccountOverviewsPage, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountOverview{}
	for rows.Next() {
		var i AccountOverview
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.SystemUser,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.PackageID,
			&i.PackageName,
			&i.PackageCreatedAt,
			&i.PackageUpdatedAt,
			&i.PackageAccountCount,
			&i.MaxWebsites,
			&i.MaxDomains,
			&i.MaxAliases,
			&i.MaxDatabases,
			&i.MaxDatabaseUsers,
			&i.MaxScheduledTasks,
			&i.MaxBackupPlans,
			&i.MaxBackupRetention,
			&i.MaxFtpAccounts,
			&i.UsedWebsites,
			&i.UsedDomains,
			&i.UsedAliases,
			&i.UsedDatabases,
			&i.UsedDatabaseUsers,
			&i.UsedScheduledTasks,
			&i.UsedBackupPlans,
			&i.UsedFtpAccounts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const packageNameExists = `-- name: PackageNameExists :one
SELECT EXISTS(
    SELECT 1 FROM packages
    WHERE name = ?1 COLLATE NOCASE
      AND id != ?2
)
`

type PackageNameExistsParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) PackageNameExists(ctx context.Context, arg PackageNameExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, packageNameExists, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages
SET
    name = ?,
    max_websites = ?,
    max_domains = ?,
    max_aliases = ?,
    max_databases = ?,
    max_database_users = ?,
    max_scheduled_tasks = ?,
    max_backup_plans = ?,
    max_backup_retention = ?,
    max_ftp_accounts = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, max_websites, max_domains, max_aliases, max_databases, max_database_users, max_scheduled_tasks, max_backup_plans, max_backup_retention, created_at, updated_at, max_ftp_accounts
`

type UpdatePackageParams struct {
	Name               string `json:"name"`
	MaxWebsites        int64  `json:"max_websites"`
	MaxDomains         int64  `json:"max_domains"`
	MaxAliases         int64  `json:"max_aliases"`
	MaxDatabases       int64  `json:"max_databases"`
	MaxDatabaseUsers   int64  `json:"max_database_users"`
	MaxScheduledTasks  int64  `json:"max_scheduled_tasks"`
	MaxBackupPlans     int64  `json:"max_backup_plans"`
	MaxBackupRetention int64  `json:"max_backup_retention"`
	MaxFtpAccounts     int64  `json:"max_ftp_accounts"`
	UpdatedAt          int64  `json:"updated_at"`
	ID                 string `json:"id"`
}

func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, updatePackage,
		arg.Name,
		arg.MaxWebsites,
		arg.MaxDomains,
		arg.MaxAliases,
		arg.MaxDatabases,
		arg.MaxDatabaseUsers,
		arg.MaxScheduledTasks,
		arg.MaxBackupPlans,
		arg.MaxBackupRetention,
		arg.MaxFtpAccounts,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxWebsites,
		&i.MaxDomains,
		&i.MaxAliases,
		&i.MaxDatabases,
		&i.MaxDatabaseUsers,
		&i.MaxScheduledTasks,
		&i.MaxBackupPlans,
		&i.MaxBackupRetention,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxFtpAccounts,
	)
	return i, err
}
