// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package dbgen

import (
	"context"
)

const getServiceSettings = `-- name: GetServiceSettings :one
SELECT id, web_driver, runtime_driver, runtime_version, database_driver, scheduler_driver, backup_driver, updated_at FROM service_settings WHERE id = 1
`

func (q *Queries) GetServiceSettings(ctx context.Context) (ServiceSetting, error) {
	row := q.db.QueryRowContext(ctx, getServiceSettings)
	var i ServiceSetting
	err := row.Scan(
		&i.ID,
		&i.WebDriver,
		&i.RuntimeDriver,
		&i.RuntimeVersion,
		&i.DatabaseDriver,
		&i.SchedulerDriver,
		&i.BackupDriver,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceSettings = `-- name: UpdateServiceSettings :one
UPDATE service_settings
SET web_driver = ?,
    runtime_driver = ?,
    runtime_version = ?,
    database_driver = ?,
    scheduler_driver = ?,
    backup_driver = ?,
    updated_at = ?
WHERE id = 1
RETURNING id, web_driver, runtime_driver, runtime_version, database_driver, scheduler_driver, backup_driver, updated_at
`

type UpdateServiceSettingsParams struct {
	WebDriver       string `json:"web_driver"`
	RuntimeDriver   string `json:"runtime_driver"`
	RuntimeVersion  string `json:"runtime_version"`
	DatabaseDriver  string `json:"database_driver"`
	SchedulerDriver string `json:"scheduler_driver"`
	BackupDriver    string `json:"backup_driver"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) UpdateServiceSettings(ctx context.Context, arg UpdateServiceSettingsParams) (ServiceSetting, error) {
	row := q.db.QueryRowContext(ctx, updateServiceSettings,
		arg.WebDriver,
		arg.RuntimeDriver,
		arg.RuntimeVersion,
		arg.DatabaseDriver,
		arg.SchedulerDriver,
		arg.BackupDriver,
		arg.UpdatedAt,
	)
	var i ServiceSetting
	err := row.Scan(
		&i.ID,
		&i.WebDriver,
		&i.RuntimeDriver,
		&i.RuntimeVersion,
		&i.DatabaseDriver,
		&i.SchedulerDriver,
		&i.BackupDriver,
		&i.UpdatedAt,
	)
	return i, err
}
