// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package dbgen

import (
	"context"
)

const countScheduledTasks = `-- name: CountScheduledTasks :one
SELECT COUNT(DISTINCT scheduled_tasks.id) FROM scheduled_tasks
JOIN account_members ON account_members.account_id = scheduled_tasks.account_id
WHERE ?1 OR account_members.user_id = ?2
`

type CountScheduledTasksParams struct {
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountScheduledTasks(ctx context.Context, arg CountScheduledTasksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScheduledTasks, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduledTask = `-- name: CreateScheduledTask :one
INSERT INTO scheduled_tasks (
    id, account_id, node_id, name, schedule, command, scheduler_driver, kind, enabled, status,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)
RETURNING id, account_id, node_id, name, schedule, command, enabled, status, created_at, updated_at, scheduler_driver, kind
`

type CreateScheduledTaskParams struct {
	ID              string `json:"id"`
	AccountID       string `json:"account_id"`
	NodeID          string `json:"node_id"`
	Name            string `json:"name"`
	Schedule        string `json:"schedule"`
	Command         string `json:"command"`
	SchedulerDriver string `json:"scheduler_driver"`
	Kind            string `json:"kind"`
	Enabled         int64  `json:"enabled"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) CreateScheduledTask(ctx context.Context, arg CreateScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRowContext(ctx, createScheduledTask,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.SchedulerDriver,
		arg.Kind,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchedulerDriver,
		&i.Kind,
	)
	return i, err
}

const deleteScheduledTask = `-- name: DeleteScheduledTask :exec
DELETE FROM scheduled_tasks WHERE id = ?
`

func (q *Queries) DeleteScheduledTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteScheduledTask, id)
	return err
}

const getScheduledTask = `-- name: GetScheduledTask :one
SELECT id, account_id, node_id, name, schedule, command, enabled, status, created_at, updated_at, scheduler_driver, kind FROM scheduled_tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetScheduledTask(ctx context.Context, id string) (ScheduledTask, error) {
	row := q.db.QueryRowContext(ctx, getScheduledTask, id)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchedulerDriver,
		&i.Kind,
	)
	return i, err
}

const listAccountScheduledTasks = `-- name: ListAccountScheduledTasks :many
SELECT id, account_id, node_id, name, schedule, command, enabled, status, created_at, updated_at, scheduler_driver, kind FROM scheduled_tasks WHERE account_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListAccountScheduledTasks(ctx context.Context, accountID string) ([]ScheduledTask, error) {
	rows, err := q.db.QueryContext(ctx, listAccountScheduledTasks, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledTask{}
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.Enabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchedulerDriver,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledTasks = `-- name: ListScheduledTasks :many
SELECT scheduled_tasks.id, scheduled_tasks.account_id, scheduled_tasks.node_id, scheduled_tasks.name, scheduled_tasks.schedule, scheduled_tasks.command, scheduled_tasks.enabled, scheduled_tasks.status, scheduled_tasks.created_at, scheduled_tasks.updated_at, scheduled_tasks.scheduler_driver, scheduled_tasks.kind FROM scheduled_tasks
JOIN account_members ON account_members.account_id = scheduled_tasks.account_id
WHERE ? OR account_members.user_id = ?
GROUP BY scheduled_tasks.id
ORDER BY scheduled_tasks.created_at ASC
`

type ListScheduledTasksParams struct {
	Column1 interface{} `json:"column_1"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) ListScheduledTasks(ctx context.Context, arg ListScheduledTasksParams) ([]ScheduledTask, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledTasks, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledTask{}
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.Enabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchedulerDriver,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledTasksPage = `-- name: ListScheduledTasksPage :many
SELECT scheduled_tasks.id, scheduled_tasks.account_id, scheduled_tasks.node_id, scheduled_tasks.name, scheduled_tasks.schedule, scheduled_tasks.command, scheduled_tasks.enabled, scheduled_tasks.status, scheduled_tasks.created_at, scheduled_tasks.updated_at, scheduled_tasks.scheduler_driver, scheduled_tasks.kind FROM scheduled_tasks
JOIN account_members ON account_members.account_id = scheduled_tasks.account_id
WHERE ?1 OR account_members.user_id = ?2
GROUP BY scheduled_tasks.id
ORDER BY scheduled_tasks.created_at ASC
LIMIT ?4 OFFSET ?3
`

type ListScheduledTasksPageParams struct {
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListScheduledTasksPage(ctx context.Context, arg ListScheduledTasksPageParams) ([]ScheduledTask, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledTasksPage,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledTask{}
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.Enabled,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchedulerDriver,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountTaskStatuses = `-- name: UpdateAccountTaskStatuses :exec
UPDATE scheduled_tasks
SET status = CASE WHEN enabled = 1 THEN ? ELSE ? END, updated_at = ?
WHERE account_id = ?
`

type UpdateAccountTaskStatusesParams struct {
	Status    string `json:"status"`
	Status_2  string `json:"status_2"`
	UpdatedAt int64  `json:"updated_at"`
	AccountID string `json:"account_id"`
}

func (q *Queries) UpdateAccountTaskStatuses(ctx context.Context, arg UpdateAccountTaskStatusesParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountTaskStatuses,
		arg.Status,
		arg.Status_2,
		arg.UpdatedAt,
		arg.AccountID,
	)
	return err
}

const updateScheduledTask = `-- name: UpdateScheduledTask :one
UPDATE scheduled_tasks
SET name = ?, schedule = ?, command = ?, scheduler_driver = ?, kind = ?, enabled = ?, status = 'pending', updated_at = ?
WHERE id = ?
RETURNING id, account_id, node_id, name, schedule, command, enabled, status, created_at, updated_at, scheduler_driver, kind
`

type UpdateScheduledTaskParams struct {
	Name            string `json:"name"`
	Schedule        string `json:"schedule"`
	Command         string `json:"command"`
	SchedulerDriver string `json:"scheduler_driver"`
	Kind            string `json:"kind"`
	Enabled         int64  `json:"enabled"`
	UpdatedAt       int64  `json:"updated_at"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateScheduledTask(ctx context.Context, arg UpdateScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRowContext(ctx, updateScheduledTask,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.SchedulerDriver,
		arg.Kind,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchedulerDriver,
		&i.Kind,
	)
	return i, err
}

const updateScheduledTaskStatus = `-- name: UpdateScheduledTaskStatus :exec
UPDATE scheduled_tasks SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateScheduledTaskStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateScheduledTaskStatus(ctx context.Context, arg UpdateScheduledTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduledTaskStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
