// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: websites.sql

package dbgen

import (
	"context"
)

const completeWebsiteDomainRename = `-- name: CompleteWebsiteDomainRename :exec
UPDATE website_domains
SET previous_hostname = NULL,
    status = CASE WHEN enabled = 1 THEN 'active' ELSE 'disabled' END,
    updated_at = ?
WHERE id = ?
`

type CompleteWebsiteDomainRenameParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteWebsiteDomainRename(ctx context.Context, arg CompleteWebsiteDomainRenameParams) error {
	_, err := q.db.ExecContext(ctx, completeWebsiteDomainRename, arg.UpdatedAt, arg.ID)
	return err
}

const countUserWebsites = `-- name: CountUserWebsites :one
SELECT COUNT(*) FROM websites
JOIN account_members ON account_members.account_id = websites.account_id
WHERE account_members.user_id = ?
`

func (q *Queries) CountUserWebsites(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserWebsites, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebsiteDomainsByKind = `-- name: CountWebsiteDomainsByKind :one
SELECT COUNT(*) FROM website_domains
JOIN websites ON websites.id = website_domains.website_id
WHERE website_domains.kind = ?1
  AND (?2 OR EXISTS (
      SELECT 1 FROM account_members
      WHERE account_members.account_id = websites.account_id
        AND account_members.user_id = ?3
  ))
`

type CountWebsiteDomainsByKindParams struct {
	Kind    string      `json:"kind"`
	IsAdmin interface{} `json:"is_admin"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) CountWebsiteDomainsByKind(ctx context.Context, arg CountWebsiteDomainsByKindParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebsiteDomainsByKind, arg.Kind, arg.IsAdmin, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWebsites = `-- name: CountWebsites :one
SELECT COUNT(*) FROM websites
`

func (q *Queries) CountWebsites(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebsites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebsite = `-- name: CreateWebsite :one
INSERT INTO websites (
    id, account_id, node_id, name, kind, document_root, web_driver,
    runtime_driver, runtime_version, status, enabled, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', 1, ?, ?)
RETURNING id, account_id, node_id, name, kind, document_root, web_driver, runtime_driver, runtime_version, status, enabled, created_at, updated_at
`

type CreateWebsiteParams struct {
	ID             string `json:"id"`
	AccountID      string `json:"account_id"`
	NodeID         string `json:"node_id"`
	Name           string `json:"name"`
	Kind           string `json:"kind"`
	DocumentRoot   string `json:"document_root"`
	WebDriver      string `json:"web_driver"`
	RuntimeDriver  string `json:"runtime_driver"`
	RuntimeVersion string `json:"runtime_version"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Website, error) {
	row := q.db.QueryRowContext(ctx, createWebsite,
		arg.ID,
		arg.AccountID,
		arg.NodeID,
		arg.Name,
		arg.Kind,
		arg.DocumentRoot,
		arg.WebDriver,
		arg.RuntimeDriver,
		arg.RuntimeVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.DocumentRoot,
		&i.WebDriver,
		&i.RuntimeDriver,
		&i.RuntimeVersion,
		&i.Status,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebsiteDomain = `-- name: CreateWebsiteDomain :one
INSERT INTO website_domains (
    id, website_id, hostname, kind, status, enabled, created_at, updated_at
) VALUES (?, ?, ?, ?, 'pending', 1, ?, ?)
RETURNING id, website_id, hostname, kind, status, enabled, previous_hostname, created_at, updated_at
`

type CreateWebsiteDomainParams struct {
	ID        string `json:"id"`
	WebsiteID string `json:"website_id"`
	Hostname  string `json:"hostname"`
	Kind      string `json:"kind"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateWebsiteDomain(ctx context.Context, arg CreateWebsiteDomainParams) (WebsiteDomain, error) {
	row := q.db.QueryRowContext(ctx, createWebsiteDomain,
		arg.ID,
		arg.WebsiteID,
		arg.Hostname,
		arg.Kind,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i WebsiteDomain
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Hostname,
		&i.Kind,
		&i.Status,
		&i.Enabled,
		&i.PreviousHostname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebsite = `-- name: DeleteWebsite :exec
DELETE FROM websites WHERE id = ?
`

func (q *Queries) DeleteWebsite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWebsite, id)
	return err
}

const deleteWebsiteDomain = `-- name: DeleteWebsiteDomain :exec
DELETE FROM website_domains WHERE id = ? AND kind = 'alias'
`

func (q *Queries) DeleteWebsiteDomain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWebsiteDomain, id)
	return err
}

const failWebsiteDomainRename = `-- name: FailWebsiteDomainRename :exec
UPDATE website_domains
SET hostname = COALESCE(previous_hostname, hostname), previous_hostname = NULL,
    status = 'error', updated_at = ?
WHERE id = ?
`

type FailWebsiteDomainRenameParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) FailWebsiteDomainRename(ctx context.Context, arg FailWebsiteDomainRenameParams) error {
	_, err := q.db.ExecContext(ctx, failWebsiteDomainRename, arg.UpdatedAt, arg.ID)
	return err
}

const getWebsite = `-- name: GetWebsite :one
SELECT id, account_id, node_id, name, kind, document_root, web_driver, runtime_driver, runtime_version, status, enabled, created_at, updated_at FROM websites WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebsite(ctx context.Context, id string) (Website, error) {
	row := q.db.QueryRowContext(ctx, getWebsite, id)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.DocumentRoot,
		&i.WebDriver,
		&i.RuntimeDriver,
		&i.RuntimeVersion,
		&i.Status,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebsiteDomain = `-- name: GetWebsiteDomain :one
SELECT id, website_id, hostname, kind, status, enabled, previous_hostname, created_at, updated_at FROM website_domains WHERE id = ? LIMIT 1
`

func (q *Queries) GetWebsiteDomain(ctx context.Context, id string) (WebsiteDomain, error) {
	row := q.db.QueryRowContext(ctx, getWebsiteDomain, id)
	var i WebsiteDomain
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Hostname,
		&i.Kind,
		&i.Status,
		&i.Enabled,
		&i.PreviousHostname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebsitePrimaryDomain = `-- name: GetWebsitePrimaryDomain :one
SELECT id, website_id, hostname, kind, status, enabled, previous_hostname, created_at, updated_at FROM website_domains WHERE website_id = ? AND kind = 'primary' LIMIT 1
`

func (q *Queries) GetWebsitePrimaryDomain(ctx context.Context, websiteID string) (WebsiteDomain, error) {
	row := q.db.QueryRowContext(ctx, getWebsitePrimaryDomain, websiteID)
	var i WebsiteDomain
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Hostname,
		&i.Kind,
		&i.Status,
		&i.Enabled,
		&i.PreviousHostname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledWebsiteDomains = `-- name: ListEnabledWebsiteDomains :many
SELECT id, website_id, hostname, kind, status, enabled, previous_hostname, created_at, updated_at FROM website_domains
WHERE website_id = ? AND enabled = 1
ORDER BY kind DESC, hostname ASC
`

func (q *Queries) ListEnabledWebsiteDomains(ctx context.Context, websiteID string) ([]WebsiteDomain, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledWebsiteDomains, websiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebsiteDomain{}
	for rows.Next() {
		var i WebsiteDomain
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Hostname,
			&i.Kind,
			&i.Status,
			&i.Enabled,
			&i.PreviousHostname,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWebsites = `-- name: ListUserWebsites :many
SELECT websites.id, websites.account_id, websites.node_id, websites.name, websites.kind, websites.document_root, websites.web_driver, websites.runtime_driver, websites.runtime_version, websites.status, websites.enabled, websites.created_at, websites.updated_at FROM websites
JOIN account_members ON account_members.account_id = websites.account_id
WHERE account_members.user_id = ?
ORDER BY websites.created_at ASC
`

func (q *Queries) ListUserWebsites(ctx context.Context, userID string) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listUserWebsites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Website{}
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Kind,
			&i.DocumentRoot,
			&i.WebDriver,
			&i.RuntimeDriver,
			&i.RuntimeVersion,
			&i.Status,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWebsitesPage = `-- name: ListUserWebsitesPage :many
SELECT websites.id, websites.account_id, websites.node_id, websites.name, websites.kind, websites.document_root, websites.web_driver, websites.runtime_driver, websites.runtime_version, websites.status, websites.enabled, websites.created_at, websites.updated_at FROM websites
JOIN account_members ON account_members.account_id = websites.account_id
WHERE account_members.user_id = ?1
ORDER BY websites.created_at ASC
LIMIT ?3 OFFSET ?2
`

type ListUserWebsitesPageParams struct {
	UserID     string `json:"user_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) ListUserWebsitesPage(ctx context.Context, arg ListUserWebsitesPageParams) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listUserWebsitesPage, arg.UserID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Website{}
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Kind,
			&i.DocumentRoot,
			&i.WebDriver,
			&i.RuntimeDriver,
			&i.RuntimeVersion,
			&i.Status,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebsiteDomains = `-- name: ListWebsiteDomains :many
SELECT id, website_id, hostname, kind, status, enabled, previous_hostname, created_at, updated_at FROM website_domains WHERE website_id = ? ORDER BY kind DESC, hostname ASC
`

func (q *Queries) ListWebsiteDomains(ctx context.Context, websiteID string) ([]WebsiteDomain, error) {
	rows, err := q.db.QueryContext(ctx, listWebsiteDomains, websiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebsiteDomain{}
	for rows.Next() {
		var i WebsiteDomain
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Hostname,
			&i.Kind,
			&i.Status,
			&i.Enabled,
			&i.PreviousHostname,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebsiteDomainsByKindPage = `-- name: ListWebsiteDomainsByKindPage :many
SELECT website_domains.id, website_domains.website_id, website_domains.hostname, website_domains.kind, website_domains.status, website_domains.enabled, website_domains.previous_hostname, website_domains.created_at, website_domains.updated_at FROM website_domains
JOIN websites ON websites.id = website_domains.website_id
WHERE website_domains.kind = ?1
  AND (?2 OR EXISTS (
      SELECT 1 FROM account_members
      WHERE account_members.account_id = websites.account_id
        AND account_members.user_id = ?3
  ))
ORDER BY website_domains.created_at ASC
LIMIT ?5 OFFSET ?4
`

type ListWebsiteDomainsByKindPageParams struct {
	Kind       string      `json:"kind"`
	IsAdmin    interface{} `json:"is_admin"`
	UserID     string      `json:"user_id"`
	PageOffset int64       `json:"page_offset"`
	PageSize   int64       `json:"page_size"`
}

func (q *Queries) ListWebsiteDomainsByKindPage(ctx context.Context, arg ListWebsiteDomainsByKindPageParams) ([]WebsiteDomain, error) {
	rows, err := q.db.QueryContext(ctx, listWebsiteDomainsByKindPage,
		arg.Kind,
		arg.IsAdmin,
		arg.UserID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebsiteDomain{}
	for rows.Next() {
		var i WebsiteDomain
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Hostname,
			&i.Kind,
			&i.Status,
			&i.Enabled,
			&i.PreviousHostname,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebsites = `-- name: ListWebsites :many
SELECT id, account_id, node_id, name, kind, document_root, web_driver, runtime_driver, runtime_version, status, enabled, created_at, updated_at FROM websites ORDER BY created_at ASC
`

func (q *Queries) ListWebsites(ctx context.Context) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listWebsites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Website{}
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Kind,
			&i.DocumentRoot,
			&i.WebDriver,
			&i.RuntimeDriver,
			&i.RuntimeVersion,
			&i.Status,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebsitesPage = `-- name: ListWebsitesPage :many
SELECT id, account_id, node_id, name, kind, document_root, web_driver, runtime_driver, runtime_version, status, enabled, created_at, updated_at FROM websites ORDER BY created_at ASC
LIMIT ?2 OFFSET ?1
`

type ListWebsitesPageParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

func (q *Queries) ListWebsitesPage(ctx context.Context, arg ListWebsitesPageParams) ([]Website, error) {
	rows, err := q.db.QueryContext(ctx, listWebsitesPage, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Website{}
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.NodeID,
			&i.Name,
			&i.Kind,
			&i.DocumentRoot,
			&i.WebDriver,
			&i.RuntimeDriver,
			&i.RuntimeVersion,
			&i.Status,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueWebsiteAction = `-- name: QueueWebsiteAction :one
UPDATE websites SET enabled = ?, status = 'pending', updated_at = ?
WHERE id = ? AND status != 'pending'
RETURNING id, account_id, node_id, name, kind, document_root, web_driver, runtime_driver, runtime_version, status, enabled, created_at, updated_at
`

type QueueWebsiteActionParams struct {
	Enabled   int64  `json:"enabled"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueWebsiteAction(ctx context.Context, arg QueueWebsiteActionParams) (Website, error) {
	row := q.db.QueryRowContext(ctx, queueWebsiteAction, arg.Enabled, arg.UpdatedAt, arg.ID)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.DocumentRoot,
		&i.WebDriver,
		&i.RuntimeDriver,
		&i.RuntimeVersion,
		&i.Status,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueWebsiteDomainAction = `-- name: QueueWebsiteDomainAction :one
UPDATE website_domains SET enabled = ?, status = 'pending', updated_at = ?
WHERE id = ? AND kind = 'alias' AND status != 'pending'
RETURNING id, website_id, hostname, kind, status, enabled, previous_hostname, created_at, updated_at
`

type QueueWebsiteDomainActionParams struct {
	Enabled   int64  `json:"enabled"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueWebsiteDomainAction(ctx context.Context, arg QueueWebsiteDomainActionParams) (WebsiteDomain, error) {
	row := q.db.QueryRowContext(ctx, queueWebsiteDomainAction, arg.Enabled, arg.UpdatedAt, arg.ID)
	var i WebsiteDomain
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Hostname,
		&i.Kind,
		&i.Status,
		&i.Enabled,
		&i.PreviousHostname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueWebsiteDomainRename = `-- name: QueueWebsiteDomainRename :one
UPDATE website_domains
SET previous_hostname = hostname, hostname = ?, status = 'pending', updated_at = ?
WHERE id = ? AND status != 'pending'
RETURNING id, website_id, hostname, kind, status, enabled, previous_hostname, created_at, updated_at
`

type QueueWebsiteDomainRenameParams struct {
	Hostname  string `json:"hostname"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) QueueWebsiteDomainRename(ctx context.Context, arg QueueWebsiteDomainRenameParams) (WebsiteDomain, error) {
	row := q.db.QueryRowContext(ctx, queueWebsiteDomainRename, arg.Hostname, arg.UpdatedAt, arg.ID)
	var i WebsiteDomain
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Hostname,
		&i.Kind,
		&i.Status,
		&i.Enabled,
		&i.PreviousHostname,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebsiteDomainStatus = `-- name: UpdateWebsiteDomainStatus :exec
UPDATE website_domains SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateWebsiteDomainStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateWebsiteDomainStatus(ctx context.Context, arg UpdateWebsiteDomainStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWebsiteDomainStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateWebsiteStatus = `-- name: UpdateWebsiteStatus :exec
UPDATE websites SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateWebsiteStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateWebsiteStatus(ctx context.Context, arg UpdateWebsiteStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWebsiteStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const websiteHostnameExists = `-- name: WebsiteHostnameExists :one
SELECT EXISTS(
    SELECT 1 FROM website_domains
    WHERE hostname = ?1 COLLATE NOCASE
       OR previous_hostname = ?1 COLLATE NOCASE
)
`

func (q *Queries) WebsiteHostnameExists(ctx context.Context, hostname string) (bool, error) {
	row := q.db.QueryRowContext(ctx, websiteHostnameExists, hostname)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
