// Package publicapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package publicapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountStatus.
const (
	AccountStatusActive   AccountStatus = "active"
	AccountStatusDisabled AccountStatus = "disabled"
	AccountStatusError    AccountStatus = "error"
	AccountStatusPending  AccountStatus = "pending"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case AccountStatusActive:
		return true
	case AccountStatusDisabled:
		return true
	case AccountStatusError:
		return true
	case AccountStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for AccountOverviewStatus.
const (
	AccountOverviewStatusActive   AccountOverviewStatus = "active"
	AccountOverviewStatusDisabled AccountOverviewStatus = "disabled"
	AccountOverviewStatusError    AccountOverviewStatus = "error"
	AccountOverviewStatusPending  AccountOverviewStatus = "pending"
)

// Valid indicates whether the value is a known member of the AccountOverviewStatus enum.
func (e AccountOverviewStatus) Valid() bool {
	switch e {
	case AccountOverviewStatusActive:
		return true
	case AccountOverviewStatusDisabled:
		return true
	case AccountOverviewStatusError:
		return true
	case AccountOverviewStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for BackupRunStatus.
const (
	BackupRunStatusFailed    BackupRunStatus = "failed"
	BackupRunStatusQueued    BackupRunStatus = "queued"
	BackupRunStatusRunning   BackupRunStatus = "running"
	BackupRunStatusSucceeded BackupRunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the BackupRunStatus enum.
func (e BackupRunStatus) Valid() bool {
	switch e {
	case BackupRunStatusFailed:
		return true
	case BackupRunStatusQueued:
		return true
	case BackupRunStatusRunning:
		return true
	case BackupRunStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for CertificateKind.
const (
	CertificateKindPanel   CertificateKind = "panel"
	CertificateKindWebsite CertificateKind = "website"
)

// Valid indicates whether the value is a known member of the CertificateKind enum.
func (e CertificateKind) Valid() bool {
	switch e {
	case CertificateKindPanel:
		return true
	case CertificateKindWebsite:
		return true
	default:
		return false
	}
}

// Defines values for CertificateStatus.
const (
	CertificateStatusActive  CertificateStatus = "active"
	CertificateStatusError   CertificateStatus = "error"
	CertificateStatusPending CertificateStatus = "pending"
)

// Valid indicates whether the value is a known member of the CertificateStatus enum.
func (e CertificateStatus) Valid() bool {
	switch e {
	case CertificateStatusActive:
		return true
	case CertificateStatusError:
		return true
	case CertificateStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for CreateWebsiteRequestKind.
const (
	CreateWebsiteRequestKindPhp CreateWebsiteRequestKind = "php"
)

// Valid indicates whether the value is a known member of the CreateWebsiteRequestKind enum.
func (e CreateWebsiteRequestKind) Valid() bool {
	switch e {
	case CreateWebsiteRequestKindPhp:
		return true
	default:
		return false
	}
}

// Defines values for CreateWebsiteRequestRuntimeDriver.
const (
	CreateWebsiteRequestRuntimeDriverPhpfpm CreateWebsiteRequestRuntimeDriver = "phpfpm"
)

// Valid indicates whether the value is a known member of the CreateWebsiteRequestRuntimeDriver enum.
func (e CreateWebsiteRequestRuntimeDriver) Valid() bool {
	switch e {
	case CreateWebsiteRequestRuntimeDriverPhpfpm:
		return true
	default:
		return false
	}
}

// Defines values for CreateWebsiteRequestRuntimeVersion.
const (
	CreateWebsiteRequestRuntimeVersionN83 CreateWebsiteRequestRuntimeVersion = "8.3"
)

// Valid indicates whether the value is a known member of the CreateWebsiteRequestRuntimeVersion enum.
func (e CreateWebsiteRequestRuntimeVersion) Valid() bool {
	switch e {
	case CreateWebsiteRequestRuntimeVersionN83:
		return true
	default:
		return false
	}
}

// Defines values for CreateWebsiteRequestWebDriver.
const (
	CreateWebsiteRequestWebDriverNginx CreateWebsiteRequestWebDriver = "nginx"
)

// Valid indicates whether the value is a known member of the CreateWebsiteRequestWebDriver enum.
func (e CreateWebsiteRequestWebDriver) Valid() bool {
	switch e {
	case CreateWebsiteRequestWebDriverNginx:
		return true
	default:
		return false
	}
}

// Defines values for CronJobStatus.
const (
	CronJobStatusActive   CronJobStatus = "active"
	CronJobStatusDisabled CronJobStatus = "disabled"
	CronJobStatusError    CronJobStatus = "error"
	CronJobStatusPending  CronJobStatus = "pending"
)

// Valid indicates whether the value is a known member of the CronJobStatus enum.
func (e CronJobStatus) Valid() bool {
	switch e {
	case CronJobStatusActive:
		return true
	case CronJobStatusDisabled:
		return true
	case CronJobStatusError:
		return true
	case CronJobStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseStatus.
const (
	DatabaseStatusActive  DatabaseStatus = "active"
	DatabaseStatusError   DatabaseStatus = "error"
	DatabaseStatusPending DatabaseStatus = "pending"
)

// Valid indicates whether the value is a known member of the DatabaseStatus enum.
func (e DatabaseStatus) Valid() bool {
	switch e {
	case DatabaseStatusActive:
		return true
	case DatabaseStatusError:
		return true
	case DatabaseStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseGrantStatus.
const (
	DatabaseGrantStatusActive  DatabaseGrantStatus = "active"
	DatabaseGrantStatusError   DatabaseGrantStatus = "error"
	DatabaseGrantStatusPending DatabaseGrantStatus = "pending"
)

// Valid indicates whether the value is a known member of the DatabaseGrantStatus enum.
func (e DatabaseGrantStatus) Valid() bool {
	switch e {
	case DatabaseGrantStatusActive:
		return true
	case DatabaseGrantStatusError:
		return true
	case DatabaseGrantStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseUserStatus.
const (
	DatabaseUserStatusActive  DatabaseUserStatus = "active"
	DatabaseUserStatusError   DatabaseUserStatus = "error"
	DatabaseUserStatusPending DatabaseUserStatus = "pending"
)

// Valid indicates whether the value is a known member of the DatabaseUserStatus enum.
func (e DatabaseUserStatus) Valid() bool {
	switch e {
	case DatabaseUserStatusActive:
		return true
	case DatabaseUserStatusError:
		return true
	case DatabaseUserStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusFailed    JobStatus = "failed"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusFailed:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for JobStepStatus.
const (
	JobStepStatusFailed    JobStepStatus = "failed"
	JobStepStatusRunning   JobStepStatus = "running"
	JobStepStatusSucceeded JobStepStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStepStatus enum.
func (e JobStepStatus) Valid() bool {
	switch e {
	case JobStepStatusFailed:
		return true
	case JobStepStatusRunning:
		return true
	case JobStepStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for NodeKind.
const (
	Local  NodeKind = "local"
	Remote NodeKind = "remote"
)

// Valid indicates whether the value is a known member of the NodeKind enum.
func (e NodeKind) Valid() bool {
	switch e {
	case Local:
		return true
	case Remote:
		return true
	default:
		return false
	}
}

// Defines values for NodeStatus.
const (
	Offline NodeStatus = "offline"
	Online  NodeStatus = "online"
	Unknown NodeStatus = "unknown"
)

// Valid indicates whether the value is a known member of the NodeStatus enum.
func (e NodeStatus) Valid() bool {
	switch e {
	case Offline:
		return true
	case Online:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteKind.
const (
	WebsiteKindPhp WebsiteKind = "php"
)

// Valid indicates whether the value is a known member of the WebsiteKind enum.
func (e WebsiteKind) Valid() bool {
	switch e {
	case WebsiteKindPhp:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteRuntimeDriver.
const (
	WebsiteRuntimeDriverPhpfpm WebsiteRuntimeDriver = "phpfpm"
)

// Valid indicates whether the value is a known member of the WebsiteRuntimeDriver enum.
func (e WebsiteRuntimeDriver) Valid() bool {
	switch e {
	case WebsiteRuntimeDriverPhpfpm:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteRuntimeVersion.
const (
	WebsiteRuntimeVersionN83 WebsiteRuntimeVersion = "8.3"
)

// Valid indicates whether the value is a known member of the WebsiteRuntimeVersion enum.
func (e WebsiteRuntimeVersion) Valid() bool {
	switch e {
	case WebsiteRuntimeVersionN83:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteStatus.
const (
	WebsiteStatusActive   WebsiteStatus = "active"
	WebsiteStatusDisabled WebsiteStatus = "disabled"
	WebsiteStatusError    WebsiteStatus = "error"
	WebsiteStatusPending  WebsiteStatus = "pending"
)

// Valid indicates whether the value is a known member of the WebsiteStatus enum.
func (e WebsiteStatus) Valid() bool {
	switch e {
	case WebsiteStatusActive:
		return true
	case WebsiteStatusDisabled:
		return true
	case WebsiteStatusError:
		return true
	case WebsiteStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteWebDriver.
const (
	WebsiteWebDriverNginx WebsiteWebDriver = "nginx"
)

// Valid indicates whether the value is a known member of the WebsiteWebDriver enum.
func (e WebsiteWebDriver) Valid() bool {
	switch e {
	case WebsiteWebDriverNginx:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteDomainKind.
const (
	WebsiteDomainKindAlias   WebsiteDomainKind = "alias"
	WebsiteDomainKindPrimary WebsiteDomainKind = "primary"
)

// Valid indicates whether the value is a known member of the WebsiteDomainKind enum.
func (e WebsiteDomainKind) Valid() bool {
	switch e {
	case WebsiteDomainKindAlias:
		return true
	case WebsiteDomainKindPrimary:
		return true
	default:
		return false
	}
}

// Defines values for WebsiteDomainStatus.
const (
	WebsiteDomainStatusActive   WebsiteDomainStatus = "active"
	WebsiteDomainStatusDisabled WebsiteDomainStatus = "disabled"
	WebsiteDomainStatusError    WebsiteDomainStatus = "error"
	WebsiteDomainStatusPending  WebsiteDomainStatus = "pending"
)

// Valid indicates whether the value is a known member of the WebsiteDomainStatus enum.
func (e WebsiteDomainStatus) Valid() bool {
	switch e {
	case WebsiteDomainStatusActive:
		return true
	case WebsiteDomainStatusDisabled:
		return true
	case WebsiteDomainStatusError:
		return true
	case WebsiteDomainStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ListCertificatesParamsKind.
const (
	ListCertificatesParamsKindPanel   ListCertificatesParamsKind = "panel"
	ListCertificatesParamsKindWebsite ListCertificatesParamsKind = "website"
)

// Valid indicates whether the value is a known member of the ListCertificatesParamsKind enum.
func (e ListCertificatesParamsKind) Valid() bool {
	switch e {
	case ListCertificatesParamsKindPanel:
		return true
	case ListCertificatesParamsKindWebsite:
		return true
	default:
		return false
	}
}

// Defines values for ListWebsiteDomainsParamsKind.
const (
	ListWebsiteDomainsParamsKindAlias   ListWebsiteDomainsParamsKind = "alias"
	ListWebsiteDomainsParamsKindPrimary ListWebsiteDomainsParamsKind = "primary"
)

// Valid indicates whether the value is a known member of the ListWebsiteDomainsParamsKind enum.
func (e ListWebsiteDomainsParamsKind) Valid() bool {
	switch e {
	case ListWebsiteDomainsParamsKindAlias:
		return true
	case ListWebsiteDomainsParamsKindPrimary:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	CreatedAt  time.Time     `json:"createdAt"`
	Enabled    bool          `json:"enabled"`
	Id         string        `json:"id"`
	Name       string        `json:"name"`
	NodeId     string        `json:"nodeId"`
	Status     AccountStatus `json:"status"`
	SystemUser string        `json:"systemUser"`
	UpdatedAt  time.Time     `json:"updatedAt"`
}

// AccountStatus defines model for Account.Status.
type AccountStatus string

// AccountJobResponse defines model for AccountJobResponse.
type AccountJobResponse struct {
	Account Account `json:"account"`
	Job     Job     `json:"job"`
}

// AccountListResponse defines model for AccountListResponse.
type AccountListResponse struct {
	Items      []AccountOverview `json:"items"`
	Pagination Pagination        `json:"pagination"`
}

// AccountOverview defines model for AccountOverview.
type AccountOverview struct {
	CreatedAt  time.Time             `json:"createdAt"`
	Enabled    bool                  `json:"enabled"`
	Id         string                `json:"id"`
	Name       string                `json:"name"`
	NodeId     string                `json:"nodeId"`
	Package    Package               `json:"package"`
	Status     AccountOverviewStatus `json:"status"`
	SystemUser string                `json:"systemUser"`
	UpdatedAt  time.Time             `json:"updatedAt"`
	Usage      PackageUsage          `json:"usage"`
}

// AccountOverviewStatus defines model for AccountOverview.Status.
type AccountOverviewStatus string

// AssignAccountPackageRequest defines model for AssignAccountPackageRequest.
type AssignAccountPackageRequest struct {
	PackageId string `json:"packageId"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	CsrfToken string    `json:"csrfToken"`
	ExpiresAt time.Time `json:"expiresAt"`
	Timezone  string    `json:"timezone"`
	User      User      `json:"user"`
}

// BackupArtifact defines model for BackupArtifact.
type BackupArtifact struct {
	AccountId string         `json:"accountId"`
	Checksum  string         `json:"checksum"`
	CreatedAt time.Time      `json:"createdAt"`
	Id        string         `json:"id"`
	Manifest  BackupManifest `json:"manifest"`
	NodeId    string         `json:"nodeId"`
	RunId     string         `json:"runId"`
	Size      int64          `json:"size"`
}

// BackupArtifactListResponse defines model for BackupArtifactListResponse.
type BackupArtifactListResponse struct {
	Items      []BackupArtifact `json:"items"`
	Pagination Pagination       `json:"pagination"`
}

// BackupEntry defines model for BackupEntry.
type BackupEntry struct {
	Checksum string `json:"checksum"`
	Path     string `json:"path"`
	Size     int64  `json:"size"`
}

// BackupManifest defines model for BackupManifest.
type BackupManifest struct {
	AccountId string        `json:"accountId"`
	CreatedAt time.Time     `json:"createdAt"`
	Databases bool          `json:"databases"`
	Entries   []BackupEntry `json:"entries"`
	Files     bool          `json:"files"`
	Metadata  bool          `json:"metadata"`
	RunId     string        `json:"runId"`
	Version   int           `json:"version"`
}

// BackupPlan defines model for BackupPlan.
type BackupPlan struct {
	AccountId        string     `json:"accountId"`
	CreatedAt        time.Time  `json:"createdAt"`
	Enabled          bool       `json:"enabled"`
	Id               string     `json:"id"`
	IncludeDatabases bool       `json:"includeDatabases"`
	IncludeFiles     bool       `json:"includeFiles"`
	LastRunAt        *time.Time `json:"lastRunAt,omitempty"`
	Name             string     `json:"name"`
	NextRunAt        *time.Time `json:"nextRunAt,omitempty"`
	NodeId           string     `json:"nodeId"`
	RetentionCount   int        `json:"retentionCount"`
	Schedule         string     `json:"schedule"`
	UpdatedAt        time.Time  `json:"updatedAt"`
}

// BackupPlanListResponse defines model for BackupPlanListResponse.
type BackupPlanListResponse struct {
	Items      []BackupPlan `json:"items"`
	Pagination Pagination   `json:"pagination"`
}

// BackupRun defines model for BackupRun.
type BackupRun struct {
	AccountId  string          `json:"accountId"`
	CreatedAt  time.Time       `json:"createdAt"`
	Error      string          `json:"error"`
	FinishedAt *time.Time      `json:"finishedAt,omitempty"`
	Id         string          `json:"id"`
	NodeId     string          `json:"nodeId"`
	PlanId     string          `json:"planId"`
	StartedAt  *time.Time      `json:"startedAt,omitempty"`
	Status     BackupRunStatus `json:"status"`
}

// BackupRunStatus defines model for BackupRun.Status.
type BackupRunStatus string

// BackupRunListResponse defines model for BackupRunListResponse.
type BackupRunListResponse struct {
	Items      []BackupRun `json:"items"`
	Pagination Pagination  `json:"pagination"`
}

// BackupRunResponse defines model for BackupRunResponse.
type BackupRunResponse struct {
	Job Job       `json:"job"`
	Run BackupRun `json:"run"`
}

// Certificate defines model for Certificate.
type Certificate struct {
	CreatedAt     time.Time           `json:"createdAt"`
	Email         openapi_types.Email `json:"email"`
	Error         string              `json:"error"`
	ExpiresAt     *time.Time          `json:"expiresAt,omitempty"`
	Id            string              `json:"id"`
	Kind          CertificateKind     `json:"kind"`
	Name          string              `json:"name"`
	Names         []string            `json:"names"`
	NodeId        string              `json:"nodeId"`
	RedirectHttps bool                `json:"redirectHttps"`
	Status        CertificateStatus   `json:"status"`
	UpdatedAt     time.Time           `json:"updatedAt"`
	WebsiteId     *string             `json:"websiteId,omitempty"`
}

// CertificateKind defines model for Certificate.Kind.
type CertificateKind string

// CertificateStatus defines model for Certificate.Status.
type CertificateStatus string

// CertificateJobResponse defines model for CertificateJobResponse.
type CertificateJobResponse struct {
	Certificate Certificate `json:"certificate"`
	Job         Job         `json:"job"`
}

// CertificateListResponse defines model for CertificateListResponse.
type CertificateListResponse struct {
	Items      []Certificate `json:"items"`
	Pagination Pagination    `json:"pagination"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Name      string `json:"name"`
	NodeId    string `json:"nodeId"`
	PackageId string `json:"packageId"`
}

// CreateDatabaseRequest defines model for CreateDatabaseRequest.
type CreateDatabaseRequest struct {
	AccountId string `json:"accountId"`
	Name      string `json:"name"`
}

// CreateDatabaseUserRequest defines model for CreateDatabaseUserRequest.
type CreateDatabaseUserRequest struct {
	AccountId string `json:"accountId"`
	Name      string `json:"name"`
}

// CreateWebsiteDomainRequest defines model for CreateWebsiteDomainRequest.
type CreateWebsiteDomainRequest struct {
	Hostname string `json:"hostname"`
}

// CreateWebsiteRequest defines model for CreateWebsiteRequest.
type CreateWebsiteRequest struct {
	AccountId      string                             `json:"accountId"`
	Kind           CreateWebsiteRequestKind           `json:"kind"`
	Name           string                             `json:"name"`
	PrimaryDomain  string                             `json:"primaryDomain"`
	RuntimeDriver  CreateWebsiteRequestRuntimeDriver  `json:"runtimeDriver"`
	RuntimeVersion CreateWebsiteRequestRuntimeVersion `json:"runtimeVersion"`
	WebDriver      CreateWebsiteRequestWebDriver      `json:"webDriver"`
}

// CreateWebsiteRequestKind defines model for CreateWebsiteRequest.Kind.
type CreateWebsiteRequestKind string

// CreateWebsiteRequestRuntimeDriver defines model for CreateWebsiteRequest.RuntimeDriver.
type CreateWebsiteRequestRuntimeDriver string

// CreateWebsiteRequestRuntimeVersion defines model for CreateWebsiteRequest.RuntimeVersion.
type CreateWebsiteRequestRuntimeVersion string

// CreateWebsiteRequestWebDriver defines model for CreateWebsiteRequest.WebDriver.
type CreateWebsiteRequestWebDriver string

// CronJob defines model for CronJob.
type CronJob struct {
	AccountId string        `json:"accountId"`
	Command   string        `json:"command"`
	CreatedAt time.Time     `json:"createdAt"`
	Enabled   bool          `json:"enabled"`
	Id        string        `json:"id"`
	Name      string        `json:"name"`
	NodeId    string        `json:"nodeId"`
	Schedule  string        `json:"schedule"`
	Status    CronJobStatus `json:"status"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

// CronJobStatus defines model for CronJob.Status.
type CronJobStatus string

// CronJobListResponse defines model for CronJobListResponse.
type CronJobListResponse struct {
	Items      []CronJob  `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// CronJobResponse defines model for CronJobResponse.
type CronJobResponse struct {
	CronJob CronJob `json:"cronJob"`
	Job     Job     `json:"job"`
}

// Database defines model for Database.
type Database struct {
	AccountId  string         `json:"accountId"`
	CreatedAt  time.Time      `json:"createdAt"`
	Id         string         `json:"id"`
	Name       string         `json:"name"`
	NodeId     string         `json:"nodeId"`
	Status     DatabaseStatus `json:"status"`
	SystemName string         `json:"systemName"`
	UpdatedAt  time.Time      `json:"updatedAt"`
}

// DatabaseStatus defines model for Database.Status.
type DatabaseStatus string

// DatabaseGrant defines model for DatabaseGrant.
type DatabaseGrant struct {
	CreatedAt      time.Time           `json:"createdAt"`
	DatabaseId     string              `json:"databaseId"`
	DatabaseUserId string              `json:"databaseUserId"`
	Status         DatabaseGrantStatus `json:"status"`
	UpdatedAt      time.Time           `json:"updatedAt"`
}

// DatabaseGrantStatus defines model for DatabaseGrant.Status.
type DatabaseGrantStatus string

// DatabaseGrantJobResponse defines model for DatabaseGrantJobResponse.
type DatabaseGrantJobResponse struct {
	Grant DatabaseGrant `json:"grant"`
	Job   Job           `json:"job"`
}

// DatabaseGrantListResponse defines model for DatabaseGrantListResponse.
type DatabaseGrantListResponse struct {
	Items      []DatabaseGrant `json:"items"`
	Pagination Pagination      `json:"pagination"`
}

// DatabaseJobResponse defines model for DatabaseJobResponse.
type DatabaseJobResponse struct {
	Database Database `json:"database"`
	Job      Job      `json:"job"`
}

// DatabaseListResponse defines model for DatabaseListResponse.
type DatabaseListResponse struct {
	Items      []Database `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// DatabaseUser defines model for DatabaseUser.
type DatabaseUser struct {
	AccountId  string             `json:"accountId"`
	CreatedAt  time.Time          `json:"createdAt"`
	Id         string             `json:"id"`
	Name       string             `json:"name"`
	NodeId     string             `json:"nodeId"`
	Status     DatabaseUserStatus `json:"status"`
	SystemName string             `json:"systemName"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// DatabaseUserStatus defines model for DatabaseUser.Status.
type DatabaseUserStatus string

// DatabaseUserJobResponse defines model for DatabaseUserJobResponse.
type DatabaseUserJobResponse struct {
	DatabaseUser DatabaseUser `json:"databaseUser"`
	Job          Job          `json:"job"`

	// Password Returned only when a database user is created.
	Password *string `json:"password,omitempty"`
}

// DatabaseUserListResponse defines model for DatabaseUserListResponse.
type DatabaseUserListResponse struct {
	Items      []DatabaseUser `json:"items"`
	Pagination Pagination     `json:"pagination"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string             `json:"code"`
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Example: webycp-server
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`

	// Version Example: dev
	Version string `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IssueCertificateRequest defines model for IssueCertificateRequest.
type IssueCertificateRequest struct {
	Email openapi_types.Email `json:"email"`
}

// IssuePanelCertificateRequest defines model for IssuePanelCertificateRequest.
type IssuePanelCertificateRequest struct {
	Email    openapi_types.Email `json:"email"`
	Hostname string              `json:"hostname"`
}

// Job defines model for Job.
type Job struct {
	Attempts    int64                  `json:"attempts"`
	CreatedAt   time.Time              `json:"createdAt"`
	Error       *string                `json:"error,omitempty"`
	FinishedAt  *time.Time             `json:"finishedAt,omitempty"`
	Id          string                 `json:"id"`
	Kind        string                 `json:"kind"`
	MaxAttempts int64                  `json:"maxAttempts"`
	NodeId      *string                `json:"nodeId,omitempty"`
	Payload     map[string]interface{} `json:"payload"`
	StartedAt   *time.Time             `json:"startedAt,omitempty"`
	Status      JobStatus              `json:"status"`
	UserId      *string                `json:"userId,omitempty"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// JobDetail defines model for JobDetail.
type JobDetail struct {
	Job   Job       `json:"job"`
	Steps []JobStep `json:"steps"`
}

// JobListResponse defines model for JobListResponse.
type JobListResponse struct {
	Items      []Job      `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// JobStep defines model for JobStep.
type JobStep struct {
	FinishedAt *time.Time    `json:"finishedAt,omitempty"`
	Id         string        `json:"id"`
	Message    string        `json:"message"`
	Name       string        `json:"name"`
	StartedAt  time.Time     `json:"startedAt"`
	Status     JobStepStatus `json:"status"`
}

// JobStepStatus defines model for JobStep.Status.
type JobStepStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Node defines model for Node.
type Node struct {
	CreatedAt  time.Time  `json:"createdAt"`
	Endpoint   string     `json:"endpoint"`
	Id         string     `json:"id"`
	Kind       NodeKind   `json:"kind"`
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	Name       string     `json:"name"`
	Status     NodeStatus `json:"status"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

// NodeKind defines model for Node.Kind.
type NodeKind string

// NodeStatus defines model for Node.Status.
type NodeStatus string

// NodeListResponse defines model for NodeListResponse.
type NodeListResponse struct {
	Items []Node `json:"items"`
}

// Package defines model for Package.
type Package struct {
	AccountCount int64         `json:"accountCount"`
	CreatedAt    time.Time     `json:"createdAt"`
	Id           string        `json:"id"`
	Limits       PackageLimits `json:"limits"`
	Name         string        `json:"name"`
	UpdatedAt    time.Time     `json:"updatedAt"`
}

// PackageLimits defines model for PackageLimits.
type PackageLimits struct {
	Aliases         int64 `json:"aliases"`
	BackupPlans     int64 `json:"backupPlans"`
	BackupRetention int64 `json:"backupRetention"`
	DatabaseUsers   int64 `json:"databaseUsers"`
	Databases       int64 `json:"databases"`
	Domains         int64 `json:"domains"`
	ScheduledTasks  int64 `json:"scheduledTasks"`
	Websites        int64 `json:"websites"`
}

// PackageListResponse defines model for PackageListResponse.
type PackageListResponse struct {
	Items      []Package  `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// PackageUsage defines model for PackageUsage.
type PackageUsage struct {
	Aliases        int64 `json:"aliases"`
	BackupPlans    int64 `json:"backupPlans"`
	DatabaseUsers  int64 `json:"databaseUsers"`
	Databases      int64 `json:"databases"`
	Domains        int64 `json:"domains"`
	ScheduledTasks int64 `json:"scheduledTasks"`
	Websites       int64 `json:"websites"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page       int   `json:"page"`
	Size       int   `json:"size"`
	TotalItems int64 `json:"totalItems"`
	TotalPages int   `json:"totalPages"`
}

// RestoreBackupRequest defines model for RestoreBackupRequest.
type RestoreBackupRequest struct {
	Databases bool `json:"databases"`
	Files     bool `json:"files"`
	Metadata  bool `json:"metadata"`
}

// UpdateCertificateRequest defines model for UpdateCertificateRequest.
type UpdateCertificateRequest struct {
	RedirectHttps bool `json:"redirectHttps"`
}

// UpdateEnabledRequest defines model for UpdateEnabledRequest.
type UpdateEnabledRequest struct {
	Enabled bool `json:"enabled"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	CurrentPassword *string             `json:"currentPassword,omitempty"`
	Email           openapi_types.Email `json:"email"`
	Name            string              `json:"name"`
	Password        *string             `json:"password,omitempty"`
	Timezone        string              `json:"timezone"`
	Username        string              `json:"username"`
}

// UpdateWebsiteDomainRequest defines model for UpdateWebsiteDomainRequest.
type UpdateWebsiteDomainRequest struct {
	Enabled  *bool   `json:"enabled,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
}

// UpdateWebsiteRequest defines model for UpdateWebsiteRequest.
type UpdateWebsiteRequest struct {
	Enabled bool `json:"enabled"`
}

// User defines model for User.
type User struct {
	CreatedAt          time.Time           `json:"createdAt"`
	Email              openapi_types.Email `json:"email"`
	Id                 string              `json:"id"`
	MustChangePassword bool                `json:"mustChangePassword"`
	Name               string              `json:"name"`
	Role               UserRole            `json:"role"`
	Username           string              `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// Website defines model for Website.
type Website struct {
	AccountId      string                `json:"accountId"`
	CreatedAt      time.Time             `json:"createdAt"`
	DocumentRoot   string                `json:"documentRoot"`
	Enabled        bool                  `json:"enabled"`
	Id             string                `json:"id"`
	Kind           WebsiteKind           `json:"kind"`
	Name           string                `json:"name"`
	NodeId         string                `json:"nodeId"`
	RuntimeDriver  WebsiteRuntimeDriver  `json:"runtimeDriver"`
	RuntimeVersion WebsiteRuntimeVersion `json:"runtimeVersion"`
	Status         WebsiteStatus         `json:"status"`
	UpdatedAt      time.Time             `json:"updatedAt"`
	WebDriver      WebsiteWebDriver      `json:"webDriver"`
}

// WebsiteKind defines model for Website.Kind.
type WebsiteKind string

// WebsiteRuntimeDriver defines model for Website.RuntimeDriver.
type WebsiteRuntimeDriver string

// WebsiteRuntimeVersion defines model for Website.RuntimeVersion.
type WebsiteRuntimeVersion string

// WebsiteStatus defines model for Website.Status.
type WebsiteStatus string

// WebsiteWebDriver defines model for Website.WebDriver.
type WebsiteWebDriver string

// WebsiteDomain defines model for WebsiteDomain.
type WebsiteDomain struct {
	CreatedAt time.Time           `json:"createdAt"`
	Enabled   bool                `json:"enabled"`
	Hostname  string              `json:"hostname"`
	Id        string              `json:"id"`
	Kind      WebsiteDomainKind   `json:"kind"`
	Status    WebsiteDomainStatus `json:"status"`
	UpdatedAt time.Time           `json:"updatedAt"`
	WebsiteId string              `json:"websiteId"`
}

// WebsiteDomainKind defines model for WebsiteDomain.Kind.
type WebsiteDomainKind string

// WebsiteDomainStatus defines model for WebsiteDomain.Status.
type WebsiteDomainStatus string

// WebsiteDomainCollection defines model for WebsiteDomainCollection.
type WebsiteDomainCollection struct {
	Items []WebsiteDomain `json:"items"`
}

// WebsiteDomainJobResponse defines model for WebsiteDomainJobResponse.
type WebsiteDomainJobResponse struct {
	Domain WebsiteDomain `json:"domain"`
	Job    Job           `json:"job"`
}

// WebsiteDomainListResponse defines model for WebsiteDomainListResponse.
type WebsiteDomainListResponse struct {
	Items      []WebsiteDomain `json:"items"`
	Pagination Pagination      `json:"pagination"`
}

// WebsiteJobResponse defines model for WebsiteJobResponse.
type WebsiteJobResponse struct {
	Job     Job     `json:"job"`
	Website Website `json:"website"`
}

// WebsiteListResponse defines model for WebsiteListResponse.
type WebsiteListResponse struct {
	Items      []Website  `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// WriteBackupPlanRequest defines model for WriteBackupPlanRequest.
type WriteBackupPlanRequest struct {
	AccountId        string `json:"accountId"`
	Enabled          bool   `json:"enabled"`
	IncludeDatabases bool   `json:"includeDatabases"`
	IncludeFiles     bool   `json:"includeFiles"`
	Name             string `json:"name"`
	RetentionCount   int    `json:"retentionCount"`
	Schedule         string `json:"schedule"`
}

// WriteCronJobRequest defines model for WriteCronJobRequest.
type WriteCronJobRequest struct {
	AccountId string `json:"accountId"`
	Command   string `json:"command"`
	Enabled   bool   `json:"enabled"`
	Name      string `json:"name"`
	Schedule  string `json:"schedule"`
}

// WritePackageRequest defines model for WritePackageRequest.
type WritePackageRequest struct {
	Limits PackageLimits `json:"limits"`
	Name   string        `json:"name"`
}

// AccountID defines model for AccountID.
type AccountID = string

// BackupArtifactID defines model for BackupArtifactID.
type BackupArtifactID = string

// BackupPlanID defines model for BackupPlanID.
type BackupPlanID = string

// CSRFToken defines model for CSRFToken.
type CSRFToken = string

// CertificateID defines model for CertificateID.
type CertificateID = string

// CronJobID defines model for CronJobID.
type CronJobID = string

// DatabaseID defines model for DatabaseID.
type DatabaseID = string

// DatabaseUserID defines model for DatabaseUserID.
type DatabaseUserID = string

// JobID defines model for JobID.
type JobID = string

// NodeID defines model for NodeID.
type NodeID = string

// PackageID defines model for PackageID.
type PackageID = string

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// WebsiteDomainID defines model for WebsiteDomainID.
type WebsiteDomainID = string

// WebsiteID defines model for WebsiteID.
type WebsiteID = string

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// ConflictError defines model for ConflictError.
type ConflictError = ErrorResponse

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateAccountParams defines parameters for CreateAccount.
type CreateAccountParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteAccountParams defines parameters for DeleteAccount.
type DeleteAccountParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetAccountParams defines parameters for SetAccount.
type SetAccountParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// AssignAccountPackageParams defines parameters for AssignAccountPackage.
type AssignAccountPackageParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// UpdateProfileParams defines parameters for UpdateProfile.
type UpdateProfileParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListBackupArtifactsParams defines parameters for ListBackupArtifacts.
type ListBackupArtifactsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// DeleteBackupArtifactParams defines parameters for DeleteBackupArtifact.
type DeleteBackupArtifactParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RestoreBackupParams defines parameters for RestoreBackup.
type RestoreBackupParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListBackupPlansParams defines parameters for ListBackupPlans.
type ListBackupPlansParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateBackupPlanParams defines parameters for CreateBackupPlan.
type CreateBackupPlanParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteBackupPlanParams defines parameters for DeleteBackupPlan.
type DeleteBackupPlanParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetBackupPlanParams defines parameters for SetBackupPlan.
type SetBackupPlanParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RunBackupPlanParams defines parameters for RunBackupPlan.
type RunBackupPlanParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListBackupRunsParams defines parameters for ListBackupRuns.
type ListBackupRunsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// ListCertificatesParams defines parameters for ListCertificates.
type ListCertificatesParams struct {
	Kind *ListCertificatesParamsKind `form:"kind,omitempty" json:"kind,omitempty"`
	Page *Page                       `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize                   `form:"size,omitempty" json:"size,omitempty"`
}

// ListCertificatesParamsKind defines parameters for ListCertificates.
type ListCertificatesParamsKind string

// IssuePanelCertificateParams defines parameters for IssuePanelCertificate.
type IssuePanelCertificateParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetCertificateParams defines parameters for SetCertificate.
type SetCertificateParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RenewCertificateParams defines parameters for RenewCertificate.
type RenewCertificateParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListCronJobsParams defines parameters for ListCronJobs.
type ListCronJobsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateCronJobParams defines parameters for CreateCronJob.
type CreateCronJobParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteCronJobParams defines parameters for DeleteCronJob.
type DeleteCronJobParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetCronJobParams defines parameters for SetCronJob.
type SetCronJobParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListDatabaseGrantsParams defines parameters for ListDatabaseGrants.
type ListDatabaseGrantsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// ListDatabaseUsersParams defines parameters for ListDatabaseUsers.
type ListDatabaseUsersParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateDatabaseUserParams defines parameters for CreateDatabaseUser.
type CreateDatabaseUserParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDatabaseUserParams defines parameters for DeleteDatabaseUser.
type DeleteDatabaseUserParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListDatabasesParams defines parameters for ListDatabases.
type ListDatabasesParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateDatabaseParams defines parameters for CreateDatabase.
type CreateDatabaseParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDatabaseParams defines parameters for DeleteDatabase.
type DeleteDatabaseParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDatabaseGrantParams defines parameters for DeleteDatabaseGrant.
type DeleteDatabaseGrantParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CreateDatabaseGrantParams defines parameters for CreateDatabaseGrant.
type CreateDatabaseGrantParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// ProbeNodeParams defines parameters for ProbeNode.
type ProbeNodeParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListPackagesParams defines parameters for ListPackages.
type ListPackagesParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreatePackageParams defines parameters for CreatePackage.
type CreatePackageParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeletePackageParams defines parameters for DeletePackage.
type DeletePackageParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// UpdatePackageParams defines parameters for UpdatePackage.
type UpdatePackageParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListWebsiteDomainsParams defines parameters for ListWebsiteDomains.
type ListWebsiteDomainsParams struct {
	Kind ListWebsiteDomainsParamsKind `form:"kind" json:"kind"`
	Page *Page                        `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize                    `form:"size,omitempty" json:"size,omitempty"`
}

// ListWebsiteDomainsParamsKind defines parameters for ListWebsiteDomains.
type ListWebsiteDomainsParamsKind string

// DeleteWebsiteDomainParams defines parameters for DeleteWebsiteDomain.
type DeleteWebsiteDomainParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetWebsiteDomainParams defines parameters for SetWebsiteDomain.
type SetWebsiteDomainParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListWebsitesParams defines parameters for ListWebsites.
type ListWebsitesParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateWebsiteParams defines parameters for CreateWebsite.
type CreateWebsiteParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteWebsiteParams defines parameters for DeleteWebsite.
type DeleteWebsiteParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetWebsiteParams defines parameters for SetWebsite.
type SetWebsiteParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// IssueWebsiteCertificateParams defines parameters for IssueWebsiteCertificate.
type IssueWebsiteCertificateParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CreateWebsiteDomainParams defines parameters for CreateWebsiteDomain.
type CreateWebsiteDomainParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// SetAccountJSONRequestBody defines body for SetAccount for application/json ContentType.
type SetAccountJSONRequestBody = UpdateEnabledRequest

// AssignAccountPackageJSONRequestBody defines body for AssignAccountPackage for application/json ContentType.
type AssignAccountPackageJSONRequestBody = AssignAccountPackageRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest

// RestoreBackupJSONRequestBody defines body for RestoreBackup for application/json ContentType.
type RestoreBackupJSONRequestBody = RestoreBackupRequest

// CreateBackupPlanJSONRequestBody defines body for CreateBackupPlan for application/json ContentType.
type CreateBackupPlanJSONRequestBody = WriteBackupPlanRequest

// SetBackupPlanJSONRequestBody defines body for SetBackupPlan for application/json ContentType.
type SetBackupPlanJSONRequestBody = WriteBackupPlanRequest

// IssuePanelCertificateJSONRequestBody defines body for IssuePanelCertificate for application/json ContentType.
type IssuePanelCertificateJSONRequestBody = IssuePanelCertificateRequest

// SetCertificateJSONRequestBody defines body for SetCertificate for application/json ContentType.
type SetCertificateJSONRequestBody = UpdateCertificateRequest

// CreateCronJobJSONRequestBody defines body for CreateCronJob for application/json ContentType.
type CreateCronJobJSONRequestBody = WriteCronJobRequest

// SetCronJobJSONRequestBody defines body for SetCronJob for application/json ContentType.
type SetCronJobJSONRequestBody = WriteCronJobRequest

// CreateDatabaseUserJSONRequestBody defines body for CreateDatabaseUser for application/json ContentType.
type CreateDatabaseUserJSONRequestBody = CreateDatabaseUserRequest

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = CreateDatabaseRequest

// CreatePackageJSONRequestBody defines body for CreatePackage for application/json ContentType.
type CreatePackageJSONRequestBody = WritePackageRequest

// UpdatePackageJSONRequestBody defines body for UpdatePackage for application/json ContentType.
type UpdatePackageJSONRequestBody = WritePackageRequest

// SetWebsiteDomainJSONRequestBody defines body for SetWebsiteDomain for application/json ContentType.
type SetWebsiteDomainJSONRequestBody = UpdateWebsiteDomainRequest

// CreateWebsiteJSONRequestBody defines body for CreateWebsite for application/json ContentType.
type CreateWebsiteJSONRequestBody = CreateWebsiteRequest

// SetWebsiteJSONRequestBody defines body for SetWebsite for application/json ContentType.
type SetWebsiteJSONRequestBody = UpdateWebsiteRequest

// IssueWebsiteCertificateJSONRequestBody defines body for IssueWebsiteCertificate for application/json ContentType.
type IssueWebsiteCertificateJSONRequestBody = IssueCertificateRequest

// CreateWebsiteDomainJSONRequestBody defines body for CreateWebsiteDomain for application/json ContentType.
type CreateWebsiteDomainJSONRequestBody = CreateWebsiteDomainRequest
