// Package publicapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package publicapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountStatus.
const (
	AccountStatusActive   AccountStatus = "active"
	AccountStatusDisabled AccountStatus = "disabled"
	AccountStatusError    AccountStatus = "error"
	AccountStatusPending  AccountStatus = "pending"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case AccountStatusActive:
		return true
	case AccountStatusDisabled:
		return true
	case AccountStatusError:
		return true
	case AccountStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for BackupRunStatus.
const (
	BackupRunStatusFailed    BackupRunStatus = "failed"
	BackupRunStatusQueued    BackupRunStatus = "queued"
	BackupRunStatusRunning   BackupRunStatus = "running"
	BackupRunStatusSucceeded BackupRunStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the BackupRunStatus enum.
func (e BackupRunStatus) Valid() bool {
	switch e {
	case BackupRunStatusFailed:
		return true
	case BackupRunStatusQueued:
		return true
	case BackupRunStatusRunning:
		return true
	case BackupRunStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for CertificateKind.
const (
	CertificateKindDomain CertificateKind = "domain"
	CertificateKindPanel  CertificateKind = "panel"
)

// Valid indicates whether the value is a known member of the CertificateKind enum.
func (e CertificateKind) Valid() bool {
	switch e {
	case CertificateKindDomain:
		return true
	case CertificateKindPanel:
		return true
	default:
		return false
	}
}

// Defines values for CertificateStatus.
const (
	CertificateStatusActive  CertificateStatus = "active"
	CertificateStatusError   CertificateStatus = "error"
	CertificateStatusPending CertificateStatus = "pending"
)

// Valid indicates whether the value is a known member of the CertificateStatus enum.
func (e CertificateStatus) Valid() bool {
	switch e {
	case CertificateStatusActive:
		return true
	case CertificateStatusError:
		return true
	case CertificateStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for CronJobStatus.
const (
	CronJobStatusActive   CronJobStatus = "active"
	CronJobStatusDisabled CronJobStatus = "disabled"
	CronJobStatusError    CronJobStatus = "error"
	CronJobStatusPending  CronJobStatus = "pending"
)

// Valid indicates whether the value is a known member of the CronJobStatus enum.
func (e CronJobStatus) Valid() bool {
	switch e {
	case CronJobStatusActive:
		return true
	case CronJobStatusDisabled:
		return true
	case CronJobStatusError:
		return true
	case CronJobStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseStatus.
const (
	DatabaseStatusActive  DatabaseStatus = "active"
	DatabaseStatusError   DatabaseStatus = "error"
	DatabaseStatusPending DatabaseStatus = "pending"
)

// Valid indicates whether the value is a known member of the DatabaseStatus enum.
func (e DatabaseStatus) Valid() bool {
	switch e {
	case DatabaseStatusActive:
		return true
	case DatabaseStatusError:
		return true
	case DatabaseStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseGrantStatus.
const (
	DatabaseGrantStatusActive  DatabaseGrantStatus = "active"
	DatabaseGrantStatusError   DatabaseGrantStatus = "error"
	DatabaseGrantStatusPending DatabaseGrantStatus = "pending"
)

// Valid indicates whether the value is a known member of the DatabaseGrantStatus enum.
func (e DatabaseGrantStatus) Valid() bool {
	switch e {
	case DatabaseGrantStatusActive:
		return true
	case DatabaseGrantStatusError:
		return true
	case DatabaseGrantStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseUserStatus.
const (
	DatabaseUserStatusActive  DatabaseUserStatus = "active"
	DatabaseUserStatusError   DatabaseUserStatus = "error"
	DatabaseUserStatusPending DatabaseUserStatus = "pending"
)

// Valid indicates whether the value is a known member of the DatabaseUserStatus enum.
func (e DatabaseUserStatus) Valid() bool {
	switch e {
	case DatabaseUserStatusActive:
		return true
	case DatabaseUserStatusError:
		return true
	case DatabaseUserStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DomainStatus.
const (
	DomainStatusActive   DomainStatus = "active"
	DomainStatusDisabled DomainStatus = "disabled"
	DomainStatusError    DomainStatus = "error"
	DomainStatusPending  DomainStatus = "pending"
)

// Valid indicates whether the value is a known member of the DomainStatus enum.
func (e DomainStatus) Valid() bool {
	switch e {
	case DomainStatusActive:
		return true
	case DomainStatusDisabled:
		return true
	case DomainStatusError:
		return true
	case DomainStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for DomainAliasStatus.
const (
	DomainAliasStatusActive   DomainAliasStatus = "active"
	DomainAliasStatusDisabled DomainAliasStatus = "disabled"
	DomainAliasStatusError    DomainAliasStatus = "error"
	DomainAliasStatusPending  DomainAliasStatus = "pending"
)

// Valid indicates whether the value is a known member of the DomainAliasStatus enum.
func (e DomainAliasStatus) Valid() bool {
	switch e {
	case DomainAliasStatusActive:
		return true
	case DomainAliasStatusDisabled:
		return true
	case DomainAliasStatusError:
		return true
	case DomainAliasStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusFailed    JobStatus = "failed"
	JobStatusQueued    JobStatus = "queued"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusFailed:
		return true
	case JobStatusQueued:
		return true
	case JobStatusRunning:
		return true
	case JobStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for JobStepStatus.
const (
	JobStepStatusFailed    JobStepStatus = "failed"
	JobStepStatusRunning   JobStepStatus = "running"
	JobStepStatusSucceeded JobStepStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStepStatus enum.
func (e JobStepStatus) Valid() bool {
	switch e {
	case JobStepStatusFailed:
		return true
	case JobStepStatusRunning:
		return true
	case JobStepStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for NodeKind.
const (
	Local  NodeKind = "local"
	Remote NodeKind = "remote"
)

// Valid indicates whether the value is a known member of the NodeKind enum.
func (e NodeKind) Valid() bool {
	switch e {
	case Local:
		return true
	case Remote:
		return true
	default:
		return false
	}
}

// Defines values for NodeStatus.
const (
	Offline NodeStatus = "offline"
	Online  NodeStatus = "online"
	Unknown NodeStatus = "unknown"
)

// Valid indicates whether the value is a known member of the NodeStatus enum.
func (e NodeStatus) Valid() bool {
	switch e {
	case Offline:
		return true
	case Online:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	CreatedAt  time.Time     `json:"createdAt"`
	Enabled    bool          `json:"enabled"`
	Id         string        `json:"id"`
	Name       string        `json:"name"`
	NodeId     string        `json:"nodeId"`
	Status     AccountStatus `json:"status"`
	SystemUser string        `json:"systemUser"`
	UpdatedAt  time.Time     `json:"updatedAt"`
}

// AccountStatus defines model for Account.Status.
type AccountStatus string

// AccountJobResponse defines model for AccountJobResponse.
type AccountJobResponse struct {
	Account Account `json:"account"`
	Job     Job     `json:"job"`
}

// AccountListResponse defines model for AccountListResponse.
type AccountListResponse struct {
	Items      []Account  `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	CsrfToken string    `json:"csrfToken"`
	ExpiresAt time.Time `json:"expiresAt"`
	Timezone  string    `json:"timezone"`
	User      User      `json:"user"`
}

// BackupArtifact defines model for BackupArtifact.
type BackupArtifact struct {
	AccountId string         `json:"accountId"`
	Checksum  string         `json:"checksum"`
	CreatedAt time.Time      `json:"createdAt"`
	Id        string         `json:"id"`
	Manifest  BackupManifest `json:"manifest"`
	NodeId    string         `json:"nodeId"`
	RunId     string         `json:"runId"`
	Size      int64          `json:"size"`
}

// BackupArtifactListResponse defines model for BackupArtifactListResponse.
type BackupArtifactListResponse struct {
	Items      []BackupArtifact `json:"items"`
	Pagination Pagination       `json:"pagination"`
}

// BackupEntry defines model for BackupEntry.
type BackupEntry struct {
	Checksum string `json:"checksum"`
	Path     string `json:"path"`
	Size     int64  `json:"size"`
}

// BackupManifest defines model for BackupManifest.
type BackupManifest struct {
	AccountId string        `json:"accountId"`
	CreatedAt time.Time     `json:"createdAt"`
	Databases bool          `json:"databases"`
	Entries   []BackupEntry `json:"entries"`
	Files     bool          `json:"files"`
	Metadata  bool          `json:"metadata"`
	RunId     string        `json:"runId"`
	Version   int           `json:"version"`
}

// BackupPlan defines model for BackupPlan.
type BackupPlan struct {
	AccountId        string     `json:"accountId"`
	CreatedAt        time.Time  `json:"createdAt"`
	Enabled          bool       `json:"enabled"`
	Id               string     `json:"id"`
	IncludeDatabases bool       `json:"includeDatabases"`
	IncludeFiles     bool       `json:"includeFiles"`
	LastRunAt        *time.Time `json:"lastRunAt,omitempty"`
	Name             string     `json:"name"`
	NextRunAt        *time.Time `json:"nextRunAt,omitempty"`
	NodeId           string     `json:"nodeId"`
	RetentionCount   int        `json:"retentionCount"`
	Schedule         string     `json:"schedule"`
	UpdatedAt        time.Time  `json:"updatedAt"`
}

// BackupPlanListResponse defines model for BackupPlanListResponse.
type BackupPlanListResponse struct {
	Items      []BackupPlan `json:"items"`
	Pagination Pagination   `json:"pagination"`
}

// BackupRun defines model for BackupRun.
type BackupRun struct {
	AccountId  string          `json:"accountId"`
	CreatedAt  time.Time       `json:"createdAt"`
	Error      string          `json:"error"`
	FinishedAt *time.Time      `json:"finishedAt,omitempty"`
	Id         string          `json:"id"`
	NodeId     string          `json:"nodeId"`
	PlanId     string          `json:"planId"`
	StartedAt  *time.Time      `json:"startedAt,omitempty"`
	Status     BackupRunStatus `json:"status"`
}

// BackupRunStatus defines model for BackupRun.Status.
type BackupRunStatus string

// BackupRunListResponse defines model for BackupRunListResponse.
type BackupRunListResponse struct {
	Items      []BackupRun `json:"items"`
	Pagination Pagination  `json:"pagination"`
}

// BackupRunResponse defines model for BackupRunResponse.
type BackupRunResponse struct {
	Job Job       `json:"job"`
	Run BackupRun `json:"run"`
}

// Certificate defines model for Certificate.
type Certificate struct {
	CreatedAt     time.Time           `json:"createdAt"`
	DomainId      *string             `json:"domainId,omitempty"`
	Email         openapi_types.Email `json:"email"`
	Error         string              `json:"error"`
	ExpiresAt     *time.Time          `json:"expiresAt,omitempty"`
	Id            string              `json:"id"`
	Kind          CertificateKind     `json:"kind"`
	Name          string              `json:"name"`
	Names         []string            `json:"names"`
	NodeId        string              `json:"nodeId"`
	RedirectHttps bool                `json:"redirectHttps"`
	Status        CertificateStatus   `json:"status"`
	UpdatedAt     time.Time           `json:"updatedAt"`
}

// CertificateKind defines model for Certificate.Kind.
type CertificateKind string

// CertificateStatus defines model for Certificate.Status.
type CertificateStatus string

// CertificateJobResponse defines model for CertificateJobResponse.
type CertificateJobResponse struct {
	Certificate Certificate `json:"certificate"`
	Job         Job         `json:"job"`
}

// CertificateListResponse defines model for CertificateListResponse.
type CertificateListResponse struct {
	Items      []Certificate `json:"items"`
	Pagination Pagination    `json:"pagination"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Name   string `json:"name"`
	NodeId string `json:"nodeId"`
}

// CreateDatabaseRequest defines model for CreateDatabaseRequest.
type CreateDatabaseRequest struct {
	AccountId string `json:"accountId"`
	Name      string `json:"name"`
}

// CreateDatabaseUserRequest defines model for CreateDatabaseUserRequest.
type CreateDatabaseUserRequest struct {
	AccountId string `json:"accountId"`
	Name      string `json:"name"`
}

// CreateDomainAliasRequest defines model for CreateDomainAliasRequest.
type CreateDomainAliasRequest struct {
	Name string `json:"name"`
}

// CreateDomainRequest defines model for CreateDomainRequest.
type CreateDomainRequest struct {
	AccountId string `json:"accountId"`
	Name      string `json:"name"`
}

// CronJob defines model for CronJob.
type CronJob struct {
	AccountId string        `json:"accountId"`
	Command   string        `json:"command"`
	CreatedAt time.Time     `json:"createdAt"`
	Enabled   bool          `json:"enabled"`
	Id        string        `json:"id"`
	Name      string        `json:"name"`
	NodeId    string        `json:"nodeId"`
	Schedule  string        `json:"schedule"`
	Status    CronJobStatus `json:"status"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

// CronJobStatus defines model for CronJob.Status.
type CronJobStatus string

// CronJobListResponse defines model for CronJobListResponse.
type CronJobListResponse struct {
	Items      []CronJob  `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// CronJobResponse defines model for CronJobResponse.
type CronJobResponse struct {
	CronJob CronJob `json:"cronJob"`
	Job     Job     `json:"job"`
}

// Database defines model for Database.
type Database struct {
	AccountId  string         `json:"accountId"`
	CreatedAt  time.Time      `json:"createdAt"`
	Id         string         `json:"id"`
	Name       string         `json:"name"`
	NodeId     string         `json:"nodeId"`
	Status     DatabaseStatus `json:"status"`
	SystemName string         `json:"systemName"`
	UpdatedAt  time.Time      `json:"updatedAt"`
}

// DatabaseStatus defines model for Database.Status.
type DatabaseStatus string

// DatabaseGrant defines model for DatabaseGrant.
type DatabaseGrant struct {
	CreatedAt      time.Time           `json:"createdAt"`
	DatabaseId     string              `json:"databaseId"`
	DatabaseUserId string              `json:"databaseUserId"`
	Status         DatabaseGrantStatus `json:"status"`
	UpdatedAt      time.Time           `json:"updatedAt"`
}

// DatabaseGrantStatus defines model for DatabaseGrant.Status.
type DatabaseGrantStatus string

// DatabaseGrantJobResponse defines model for DatabaseGrantJobResponse.
type DatabaseGrantJobResponse struct {
	Grant DatabaseGrant `json:"grant"`
	Job   Job           `json:"job"`
}

// DatabaseGrantListResponse defines model for DatabaseGrantListResponse.
type DatabaseGrantListResponse struct {
	Items      []DatabaseGrant `json:"items"`
	Pagination Pagination      `json:"pagination"`
}

// DatabaseJobResponse defines model for DatabaseJobResponse.
type DatabaseJobResponse struct {
	Database Database `json:"database"`
	Job      Job      `json:"job"`
}

// DatabaseListResponse defines model for DatabaseListResponse.
type DatabaseListResponse struct {
	Items      []Database `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// DatabaseUser defines model for DatabaseUser.
type DatabaseUser struct {
	AccountId  string             `json:"accountId"`
	CreatedAt  time.Time          `json:"createdAt"`
	Id         string             `json:"id"`
	Name       string             `json:"name"`
	NodeId     string             `json:"nodeId"`
	Status     DatabaseUserStatus `json:"status"`
	SystemName string             `json:"systemName"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// DatabaseUserStatus defines model for DatabaseUser.Status.
type DatabaseUserStatus string

// DatabaseUserJobResponse defines model for DatabaseUserJobResponse.
type DatabaseUserJobResponse struct {
	DatabaseUser DatabaseUser `json:"databaseUser"`
	Job          Job          `json:"job"`

	// Password Returned only when a database user is created.
	Password *string `json:"password,omitempty"`
}

// DatabaseUserListResponse defines model for DatabaseUserListResponse.
type DatabaseUserListResponse struct {
	Items      []DatabaseUser `json:"items"`
	Pagination Pagination     `json:"pagination"`
}

// Domain defines model for Domain.
type Domain struct {
	AccountId  string       `json:"accountId"`
	CreatedAt  time.Time    `json:"createdAt"`
	Enabled    bool         `json:"enabled"`
	Id         string       `json:"id"`
	Name       string       `json:"name"`
	NodeId     string       `json:"nodeId"`
	PhpVersion string       `json:"phpVersion"`
	Status     DomainStatus `json:"status"`
	UpdatedAt  time.Time    `json:"updatedAt"`
}

// DomainStatus defines model for Domain.Status.
type DomainStatus string

// DomainAlias defines model for DomainAlias.
type DomainAlias struct {
	CreatedAt time.Time         `json:"createdAt"`
	DomainId  string            `json:"domainId"`
	Enabled   bool              `json:"enabled"`
	Id        string            `json:"id"`
	Name      string            `json:"name"`
	Status    DomainAliasStatus `json:"status"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

// DomainAliasStatus defines model for DomainAlias.Status.
type DomainAliasStatus string

// DomainAliasJobResponse defines model for DomainAliasJobResponse.
type DomainAliasJobResponse struct {
	Alias DomainAlias `json:"alias"`
	Job   Job         `json:"job"`
}

// DomainAliasListResponse defines model for DomainAliasListResponse.
type DomainAliasListResponse struct {
	Items      []DomainAlias `json:"items"`
	Pagination Pagination    `json:"pagination"`
}

// DomainJobResponse defines model for DomainJobResponse.
type DomainJobResponse struct {
	Domain Domain `json:"domain"`
	Job    Job    `json:"job"`
}

// DomainListResponse defines model for DomainListResponse.
type DomainListResponse struct {
	Items      []Domain   `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string             `json:"code"`
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Example: webycp-server
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`

	// Version Example: dev
	Version string `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IssueCertificateRequest defines model for IssueCertificateRequest.
type IssueCertificateRequest struct {
	Email openapi_types.Email `json:"email"`
}

// IssuePanelCertificateRequest defines model for IssuePanelCertificateRequest.
type IssuePanelCertificateRequest struct {
	Email    openapi_types.Email `json:"email"`
	Hostname string              `json:"hostname"`
}

// Job defines model for Job.
type Job struct {
	Attempts    int64                  `json:"attempts"`
	CreatedAt   time.Time              `json:"createdAt"`
	Error       *string                `json:"error,omitempty"`
	FinishedAt  *time.Time             `json:"finishedAt,omitempty"`
	Id          string                 `json:"id"`
	Kind        string                 `json:"kind"`
	MaxAttempts int64                  `json:"maxAttempts"`
	NodeId      *string                `json:"nodeId,omitempty"`
	Payload     map[string]interface{} `json:"payload"`
	StartedAt   *time.Time             `json:"startedAt,omitempty"`
	Status      JobStatus              `json:"status"`
	UserId      *string                `json:"userId,omitempty"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// JobDetail defines model for JobDetail.
type JobDetail struct {
	Job   Job       `json:"job"`
	Steps []JobStep `json:"steps"`
}

// JobListResponse defines model for JobListResponse.
type JobListResponse struct {
	Items      []Job      `json:"items"`
	Pagination Pagination `json:"pagination"`
}

// JobStep defines model for JobStep.
type JobStep struct {
	FinishedAt *time.Time    `json:"finishedAt,omitempty"`
	Id         string        `json:"id"`
	Message    string        `json:"message"`
	Name       string        `json:"name"`
	StartedAt  time.Time     `json:"startedAt"`
	Status     JobStepStatus `json:"status"`
}

// JobStepStatus defines model for JobStep.Status.
type JobStepStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Node defines model for Node.
type Node struct {
	CreatedAt  time.Time  `json:"createdAt"`
	Endpoint   string     `json:"endpoint"`
	Id         string     `json:"id"`
	Kind       NodeKind   `json:"kind"`
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	Name       string     `json:"name"`
	Status     NodeStatus `json:"status"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

// NodeKind defines model for Node.Kind.
type NodeKind string

// NodeStatus defines model for Node.Status.
type NodeStatus string

// NodeListResponse defines model for NodeListResponse.
type NodeListResponse struct {
	Items []Node `json:"items"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page       int   `json:"page"`
	Size       int   `json:"size"`
	TotalItems int64 `json:"totalItems"`
	TotalPages int   `json:"totalPages"`
}

// RestoreBackupRequest defines model for RestoreBackupRequest.
type RestoreBackupRequest struct {
	Databases bool `json:"databases"`
	Files     bool `json:"files"`
	Metadata  bool `json:"metadata"`
}

// UpdateCertificateRequest defines model for UpdateCertificateRequest.
type UpdateCertificateRequest struct {
	RedirectHttps bool `json:"redirectHttps"`
}

// UpdateDomainRequest defines model for UpdateDomainRequest.
type UpdateDomainRequest struct {
	Enabled *bool   `json:"enabled,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// UpdateEnabledRequest defines model for UpdateEnabledRequest.
type UpdateEnabledRequest struct {
	Enabled bool `json:"enabled"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	CurrentPassword *string             `json:"currentPassword,omitempty"`
	Email           openapi_types.Email `json:"email"`
	Name            string              `json:"name"`
	Password        *string             `json:"password,omitempty"`
	Timezone        string              `json:"timezone"`
	Username        string              `json:"username"`
}

// User defines model for User.
type User struct {
	CreatedAt          time.Time           `json:"createdAt"`
	Email              openapi_types.Email `json:"email"`
	Id                 string              `json:"id"`
	MustChangePassword bool                `json:"mustChangePassword"`
	Name               string              `json:"name"`
	Role               UserRole            `json:"role"`
	Username           string              `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// WriteBackupPlanRequest defines model for WriteBackupPlanRequest.
type WriteBackupPlanRequest struct {
	AccountId        string `json:"accountId"`
	Enabled          bool   `json:"enabled"`
	IncludeDatabases bool   `json:"includeDatabases"`
	IncludeFiles     bool   `json:"includeFiles"`
	Name             string `json:"name"`
	RetentionCount   int    `json:"retentionCount"`
	Schedule         string `json:"schedule"`
}

// WriteCronJobRequest defines model for WriteCronJobRequest.
type WriteCronJobRequest struct {
	AccountId string `json:"accountId"`
	Command   string `json:"command"`
	Enabled   bool   `json:"enabled"`
	Name      string `json:"name"`
	Schedule  string `json:"schedule"`
}

// AccountID defines model for AccountID.
type AccountID = string

// AliasID defines model for AliasID.
type AliasID = string

// BackupArtifactID defines model for BackupArtifactID.
type BackupArtifactID = string

// BackupPlanID defines model for BackupPlanID.
type BackupPlanID = string

// CSRFToken defines model for CSRFToken.
type CSRFToken = string

// CertificateID defines model for CertificateID.
type CertificateID = string

// CronJobID defines model for CronJobID.
type CronJobID = string

// DatabaseID defines model for DatabaseID.
type DatabaseID = string

// DatabaseUserID defines model for DatabaseUserID.
type DatabaseUserID = string

// DomainID defines model for DomainID.
type DomainID = string

// JobID defines model for JobID.
type JobID = string

// NodeID defines model for NodeID.
type NodeID = string

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// ConflictError defines model for ConflictError.
type ConflictError = ErrorResponse

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// ListAccountsParams defines parameters for ListAccounts.
type ListAccountsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateAccountParams defines parameters for CreateAccount.
type CreateAccountParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteAccountParams defines parameters for DeleteAccount.
type DeleteAccountParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetAccountParams defines parameters for SetAccount.
type SetAccountParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// UpdateProfileParams defines parameters for UpdateProfile.
type UpdateProfileParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListBackupArtifactsParams defines parameters for ListBackupArtifacts.
type ListBackupArtifactsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// DeleteBackupArtifactParams defines parameters for DeleteBackupArtifact.
type DeleteBackupArtifactParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RestoreBackupParams defines parameters for RestoreBackup.
type RestoreBackupParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListBackupPlansParams defines parameters for ListBackupPlans.
type ListBackupPlansParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateBackupPlanParams defines parameters for CreateBackupPlan.
type CreateBackupPlanParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteBackupPlanParams defines parameters for DeleteBackupPlan.
type DeleteBackupPlanParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetBackupPlanParams defines parameters for SetBackupPlan.
type SetBackupPlanParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RunBackupPlanParams defines parameters for RunBackupPlan.
type RunBackupPlanParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListBackupRunsParams defines parameters for ListBackupRuns.
type ListBackupRunsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// ListCertificatesParams defines parameters for ListCertificates.
type ListCertificatesParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// IssuePanelCertificateParams defines parameters for IssuePanelCertificate.
type IssuePanelCertificateParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetCertificateParams defines parameters for SetCertificate.
type SetCertificateParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RenewCertificateParams defines parameters for RenewCertificate.
type RenewCertificateParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListCronJobsParams defines parameters for ListCronJobs.
type ListCronJobsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateCronJobParams defines parameters for CreateCronJob.
type CreateCronJobParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteCronJobParams defines parameters for DeleteCronJob.
type DeleteCronJobParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetCronJobParams defines parameters for SetCronJob.
type SetCronJobParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListDatabaseGrantsParams defines parameters for ListDatabaseGrants.
type ListDatabaseGrantsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// ListDatabaseUsersParams defines parameters for ListDatabaseUsers.
type ListDatabaseUsersParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateDatabaseUserParams defines parameters for CreateDatabaseUser.
type CreateDatabaseUserParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDatabaseUserParams defines parameters for DeleteDatabaseUser.
type DeleteDatabaseUserParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListDatabasesParams defines parameters for ListDatabases.
type ListDatabasesParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateDatabaseParams defines parameters for CreateDatabase.
type CreateDatabaseParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDatabaseParams defines parameters for DeleteDatabase.
type DeleteDatabaseParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDatabaseGrantParams defines parameters for DeleteDatabaseGrant.
type DeleteDatabaseGrantParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CreateDatabaseGrantParams defines parameters for CreateDatabaseGrant.
type CreateDatabaseGrantParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListDomainsParams defines parameters for ListDomains.
type ListDomainsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateDomainParams defines parameters for CreateDomain.
type CreateDomainParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDomainParams defines parameters for DeleteDomain.
type DeleteDomainParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetDomainParams defines parameters for SetDomain.
type SetDomainParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListDomainAliasesParams defines parameters for ListDomainAliases.
type ListDomainAliasesParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// CreateDomainAliasParams defines parameters for CreateDomainAlias.
type CreateDomainAliasParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDomainAliasParams defines parameters for DeleteDomainAlias.
type DeleteDomainAliasParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// SetDomainAliasParams defines parameters for SetDomainAlias.
type SetDomainAliasParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// IssueDomainCertificateParams defines parameters for IssueDomainCertificate.
type IssueDomainCertificateParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Page *Page     `form:"page,omitempty" json:"page,omitempty"`
	Size *PageSize `form:"size,omitempty" json:"size,omitempty"`
}

// ProbeNodeParams defines parameters for ProbeNode.
type ProbeNodeParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// SetAccountJSONRequestBody defines body for SetAccount for application/json ContentType.
type SetAccountJSONRequestBody = UpdateEnabledRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest

// RestoreBackupJSONRequestBody defines body for RestoreBackup for application/json ContentType.
type RestoreBackupJSONRequestBody = RestoreBackupRequest

// CreateBackupPlanJSONRequestBody defines body for CreateBackupPlan for application/json ContentType.
type CreateBackupPlanJSONRequestBody = WriteBackupPlanRequest

// SetBackupPlanJSONRequestBody defines body for SetBackupPlan for application/json ContentType.
type SetBackupPlanJSONRequestBody = WriteBackupPlanRequest

// IssuePanelCertificateJSONRequestBody defines body for IssuePanelCertificate for application/json ContentType.
type IssuePanelCertificateJSONRequestBody = IssuePanelCertificateRequest

// SetCertificateJSONRequestBody defines body for SetCertificate for application/json ContentType.
type SetCertificateJSONRequestBody = UpdateCertificateRequest

// CreateCronJobJSONRequestBody defines body for CreateCronJob for application/json ContentType.
type CreateCronJobJSONRequestBody = WriteCronJobRequest

// SetCronJobJSONRequestBody defines body for SetCronJob for application/json ContentType.
type SetCronJobJSONRequestBody = WriteCronJobRequest

// CreateDatabaseUserJSONRequestBody defines body for CreateDatabaseUser for application/json ContentType.
type CreateDatabaseUserJSONRequestBody = CreateDatabaseUserRequest

// CreateDatabaseJSONRequestBody defines body for CreateDatabase for application/json ContentType.
type CreateDatabaseJSONRequestBody = CreateDatabaseRequest

// CreateDomainJSONRequestBody defines body for CreateDomain for application/json ContentType.
type CreateDomainJSONRequestBody = CreateDomainRequest

// SetDomainJSONRequestBody defines body for SetDomain for application/json ContentType.
type SetDomainJSONRequestBody = UpdateDomainRequest

// CreateDomainAliasJSONRequestBody defines body for CreateDomainAlias for application/json ContentType.
type CreateDomainAliasJSONRequestBody = CreateDomainAliasRequest

// SetDomainAliasJSONRequestBody defines body for SetDomainAlias for application/json ContentType.
type SetDomainAliasJSONRequestBody = UpdateDomainRequest

// IssueDomainCertificateJSONRequestBody defines body for IssueDomainCertificate for application/json ContentType.
type IssueDomainCertificateJSONRequestBody = IssueCertificateRequest
